inspirehep/inspirehep

- .pre-commit-config.yaml
- MANIFEST.in
- inspirehep/pidstore/providers/recid.py
- inspirehep/records/api/base.py
> Fix missing entires in MAIFEST.in

- tests/integration/conftest.py
- tests/integration/records/serializers/test_json.py
- tests/integration/records/test_views.py
> tests: addition of api client

- README.md
> global: fix documentation

- inspirehep/__init__.py
- inspirehep/celery.py
- inspirehep/cli.py
- inspirehep/config.py
- inspirehep/records/__init__.py
- inspirehep/records/ext.py
- inspirehep/records/mappings/__init__.py
- inspirehep/records/mappings/v5/__init__.py
- inspirehep/search/__init__.py
- inspirehep/search/api.py
- inspirehep/search/factories/__init__.py
- inspirehep/version.py
- inspirehep/wsgi.py
> global: remove __future__ imports

- inspirehep/pidstore/__init__.py
- inspirehep/pidstore/api/__init__.py
- inspirehep/pidstore/api/base.py
- inspirehep/pidstore/api/literature.py
- inspirehep/pidstore/errors.py
- inspirehep/pidstore/minters/__init__.py
- inspirehep/pidstore/minters/arxiv.py
- inspirehep/pidstore/minters/control_number.py
- inspirehep/pidstore/minters/doi.py
- inspirehep/pidstore/providers/__init__.py
- inspirehep/pidstore/providers/recid.py
- inspirehep/records/api/__init__.py
- inspirehep/records/api/base.py
- inspirehep/records/api/literature.py
- tests/conftest.py
- tests/helpers/providers/faker.py
- tests/helpers/providers/record_provider.py
- tests/integration/conftest.py
- tests/integration/helpers/factories/models/base.py
- tests/integration/helpers/factories/models/pidstore.py
- tests/integration/helpers/factories/models/records.py
- tests/integration/pidstore/minters/test_minters_control_number.py
- tests/integration/pidstore/providers/pid_from_legacy/conftest.py
- tests/integration/pidstore/providers/pid_from_legacy/test_get_pid_from_legacy.py
- tests/integration/pidstore/providers/test_providers_recid.py
- tests/integration/pidstore/test_pidstore_api_base.py
- tests/integration/records/test_api_base.py
- tests/unit/pidstore/api/test_pidstore_base.py
> global: fix the license

- .travis.yml
- run-tests.sh
- setup.cfg
> global: compatible isort config with black

- inspirehep/config.py
- inspirehep/submissions/loaders.py
- inspirehep/submissions/marshmallow/__init__.py
- inspirehep/submissions/marshmallow/author.py
- inspirehep/submissions/serializers.py
- inspirehep/submissions/utils.py
- inspirehep/submissions/views.py
- setup.py
- tests/helpers/providers/record_provider.py
- tests/integration/conftest.py
- tests/integration/helpers/factories/models/records.py
- tests/integration/helpers/factories/models/user_access_token.py
- tests/integration/records/test_api_literature.py
- tests/integration/submissions/test_submissions_views.py
- tests/unit/records/test_base.py
- tests/unit/submissions/test_authors.py
- tests/unit/submissions/test_literature.py
> submissions: added author submission

- ui/src/home/components/HowToSearch.jsx
- ui/src/home/components/__tests__/__snapshots__/HowToSearch.test.jsx.snap
> HowToSearch: addition of ``date``

- inspirehep/records/serializers/json.py
> searializers: json add proper content-type to literature

- Pipfile
- Pipfile.lock
It was updated automatically by pipenv without any reason to an INCOMPATIBLE version.
> pin virtualenv

- inspirehep/accounts/fixtures.py
- inspirehep/cli/fixtures.py
- inspirehep/config.py
- inspirehep/submissions/views.py
- scripts/setup
INSPIR-1992 
Added fixture to initialize authentication token
Added authentication token to call to inspire-next
> Added authentication token

- inspirehep/config.py
- inspirehep/records/api/base.py
- inspirehep/records/marshmallow/literature/authors.py
- inspirehep/records/marshmallow/literature/common/reference_item.py
- inspirehep/records/marshmallow/literature/references.py
- inspirehep/records/serializers/__init__.py
- inspirehep/records/serializers/json.py
- inspirehep/records/serializers/latex.py
- tests/integration/records/serializers/test_bibtex.py
- tests/integration/records/serializers/test_json.py
- tests/integration/records/serializers/test_latex.py
- tests/unit/records/marshmallow/literature/common/test_reference_item.py
> serializers: addition of tests for json

- ui/src/common/components/EventTracker.jsx
- ui/src/common/components/TabNameWithCount/__tests__/__snapshots__/TabNameWithCount.test.jsx.snap
- ui/src/common/components/__tests__/EventTracker.test.jsx
- ui/src/common/components/__tests__/__snapshots__/AggregationFilters.test.jsx.snap
- ui/src/literature/components/CiteModalAction.jsx
- ui/src/literature/components/__tests__/__snapshots__/ArxivEprintLink.test.jsx.snap
- ui/src/literature/components/__tests__/__snapshots__/ArxivPdfDownloadAction.test.jsx.snap
- ui/src/literature/components/__tests__/__snapshots__/CiteModalAction.test.jsx.snap
- ui/src/literature/components/__tests__/__snapshots__/DOILink.test.jsx.snap
- ui/src/literature/components/__tests__/__snapshots__/LiteratureItem.test.jsx.snap
* Also refactors EventTracker to forward selected event arguments to
tracker
> ui: track cite format change

- inspirehep/accounts/api.py
- inspirehep/submissions/views.py
- tests/integration/accounts/test_api.py
- tests/integration/conftest.py
- tests/integration/submissions/test_submissions_views.py
Replaced token authentication with session authentication for submission views
> Added session authentication for submission views

- ui/src/App.jsx
- ui/src/__tests__/App.test.jsx
- ui/src/__tests__/tracker.test.js
- ui/src/middlewares/__tests__/actionTracker.test.js
- ui/src/middlewares/actionTracker.js
- ui/src/store.js
- ui/src/tracker.js
* Also introduces middleware to track redux action if necessary in the
future
> ui: attach user info to tracker

- Pipfile.lock
Also updates other packages since pipenv is sort of retarded
> bump inspire-query-parser (among others)

- inspirehep/search/factories/search.py
- tests/integration/records/test_views.py
- tests/integration/search/test_factories_search.py
* Facets didn't update because we didn't run filter and post filter.
> facets: fix facet update bug

- inspirehep/records/serializers/latex.py
> serializers: latex add relative path instead of pkg_resource

- Pipfile
- Pipfile.lock
- inspirehep/config.py
> Use pickle protocol 2

- inspirehep/submissions/views.py
> Add authentication header to lit submission request to inspire-next

- README.md
- docker-compose.yml
- docker-services.yml
- inspirehep/config.py
> docker: add inspire-next service - INSPIR-2098

- tests/integration/submissions/test_submissions_views.py
Updated integration tests for submissions to assert data sent to inspire-next
INSPIR-2152
> Updated integration tests for submissions

- inspirehep/records/indexer/base.py
- inspirehep/records/indexer/tasks.py
- inspirehep/records/marshmallow/literature/bibtex.py
- inspirehep/records/marshmallow/literature/common/abstract.py
- tests/integration-async/records/conftest.py
- tests/integration-async/records/indexer/test_literature.py
- tests/integration/records/conftest.py
- tests/integration/records/test_api_literature.py
- tests/integration/search/test_factories_search.py
- tests/unit/records/indexer/base.py
- tests/unit/records/marshmallow/literature/common/test_abstract_source.py
- tests/unit/records/marshmallow/literature/common/test_author.py
- tests/unit/records/marshmallow/literature/test_base_schema.py
- tests/unit/records/marshmallow/literature/test_bibtex_schema.py
- tests/unit/records/marshmallow/literature/test_references_schema.py
- tests/unit/records/test_base.py
> global: fix license

- inspirehep/records/api/__init__.py
- inspirehep/records/ext.py
- inspirehep/records/receivers.py
- tests/integration-async/records/indexer/test_literature.py
> records: move receivers outside of api

- inspirehep/config.py
- inspirehep/records/api/literature.py
- tests/integration/conftest.py
- tests/integration/records/test_api_literature.py
Add support for files feature flag
Add fixture to enable/disable files feature flag
Update tests
Add new tests
> INSPIRE-2209 - Files flag

- ui/src/submissions/literature/schemas/article.js
- ui/src/submissions/literature/schemas/book.js
- ui/src/submissions/literature/schemas/bookChapter.js
- ui/src/submissions/literature/schemas/thesis.js
> submissions: fix a typo in the literature form

- inspirehep/submissions/views.py
- tests/integration/submissions/test_submissions_views.py
> submissions: add acquisition source for literature

- e2e/tests/submissions/literature.test.js
- e2e/utils/dom.js
- e2e/utils/form.js
- e2e/utils/routes.js
- e2e/utils/user.js
> e2e: add tests for literature submissions

- data/records/literature/1721418.json
> data: fix record metadata

- inspirehep/records/serializers/bibtex.py
- inspirehep/records/serializers/json.py
- inspirehep/records/serializers/latex.py
- inspirehep/records/serializers/response.py
- tests/integration/records/serializers/test_bibtex.py
- tests/integration/records/serializers/test_latex.py
* Override to record_responsify to remove/modify headers that are
cauising miscaching.
* INSPIR-2280
> records: fix browser caching issue

- inspirehep/config.py
- inspirehep/search/mappings/v5/records/hep.json
- tests/integration/records/test_views.py
*Removed the experiment facet from literature.
*INSPIR-2255
> facets: remove experiment facet

- e2e/tests/submissions/author.test.js
- inspirehep/submissions/marshmallow/author.py
> submission: fill name_variants from alternate_name in author form

- poetry.lock
- pyproject.toml
* Updated invenio, inspire-dojson and invenio_app
* INSPIR-2202
> Update invenio to 3.1.0

- ui/src/submissions/authors/components/AuthorSubmission.jsx
- ui/src/submissions/authors/containers/AuthorSubmissionPage.jsx
- ui/src/submissions/authors/containers/__tests__/__snapshots__/AuthorSubmissionPage.test.jsx.snap
- ui/src/submissions/authors/schemas/author.js
* Only validates if orcid exist or not, for NEW author submissions
* INSPIR-2304
> ui: remove unique orcid validation for updates

- e2e/tests/submissions/literature.test.js
- inspirehep/submissions/marshmallow/literature.py
> literature submissions bugs (publication_place and supervisors)

- inspirehep/config.py
* Move facet_collaboration to be after doc_type
* INSPIR-2256
> Make facet collaboration after doc_type

- inspirehep/config.py
- tests/integration/records/test_views.py
* Added facet collaboration in authors facets
* INSPIR-2256
> Add facet collaboration in authors facets

- inspirehep/records/cli.py
- tests/integration/records/serializers/test_json/1.json
- tests/integration/records/serializers/test_json/1108739.json
- tests/integration/records/serializers/test_json/1185692.json
- tests/integration/records/serializers/test_json/1212042.json
- tests/integration/records/serializers/test_json/902852.json
- tests/integration/records/serializers/test_json/955427.json
* Fixed wrong record data
* Used InspireRecord.create for cli record creation
> Fix wrong record data and add all collections to record importer cli

- ui/src/common/components/InlineList/InlineList.jsx
- ui/src/common/components/InlineList/InlineList.scss
- ui/src/literature/components/PublicNotesList.jsx
- ui/src/literature/components/__tests__/PublicNotesList.test.jsx
- ui/src/literature/components/__tests__/__snapshots__/PublicNotesList.test.jsx.snap
- ui/src/literature/containers/DetailPage/DetailPage.jsx
* Displayed public notes under abstract in an inLineList with middle dot as a separator
* INSPIR-1830
> ui: display public_notes

- inspirehep/records/marshmallow/literature/common/publication_info_item.py
- tests/unit/records/marshmallow/literature/common/test_publication_info_item.py
* Filtered out publication_info which are conferences
* INSPIR-2069
> serializers: filter conferences from publication_info

- inspirehep/config.py
- inspirehep/search/facets.py
- tests/integration/records/test_views.py
* Added facet_name citation_summary with the aggregation for the summary of citations
* INSPIR-2250
> Add citation-summary endpoint

- .travis.yml
- Dockerfile
- README.md
- pyproject.toml
due to https://github.com/sdispater/poetry/issues/1060 error
> Pinning poetry to 0.12.11 as last working version

- inspirehep/records/views.py
- tests/integration/records/test_views.py
> import_article: serialize properly imported article for submission

- inspirehep/config.py
- inspirehep/search/api.py
- inspirehep/search/factories/search.py
- tests/integration/search/test_factories_search.py
* Also refactors how we handle source.includes based on the content and
record type.
* INSPIR-2333
> search: support source.excludes

- ui/src/authors/containers/DetailPage.jsx
- ui/src/common/components/EmbeddedSearch.jsx
- ui/src/common/components/__tests__/EmbeddedSearch.test.jsx
> ui: avoid reduntant author's pubs request

- tests/integration/records/test_views.py
* Added some tests for the hIndex
* INSPIR-2250
> Add more tests to hIndex

- .pre-commit-config.yaml
> global: addition of isort in pre-commit

- inspirehep/submissions/marshmallow/literature.py
- inspirehep/submissions/views.py
- poetry.lock
- pyproject.toml
- tests/integration/records/test_views.py
- tests/integration/submissions/test_submissions_views.py
> submission: merge submission with crossref paper if doi is available

- README.md
- docker-compose.services.yml
> docker: add login in the backend

- inspirehep/access_control.py
- inspirehep/config.py
- inspirehep/pidstore/minters/base.py
- inspirehep/records/api/base.py
- inspirehep/records/loaders/json.py
- inspirehep/records/marshmallow/authors/base.py
- inspirehep/records/marshmallow/literature/base.py
- tests/integration-async/records/indexer/test_authors.py
- tests/integration-async/records/indexer/test_literature.py
- tests/integration/records/test_views.py
API is protected by Bearer token, allows to create and update new Author and Literature records
*INSPIR-2311
> records: Enable API for creating and updating records

- ui/src/authors/components/CitationSummaryTable/CitationSummaryTable.jsx
- ui/src/authors/components/__tests__/__snapshots__/CitationSummaryTable.test.jsx.snap
* INSPIR-2359
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.comk>
> ui: use proper sentence in citesummary table

- ui/package.json
- ui/src/authors/containers/DetailPage.jsx
- ui/src/common/components/CitationSummaryGraph/CitationSummaryGraph.jsx
- ui/src/common/components/CitationSummaryGraph/CitationSummaryGraph.scss
- ui/src/common/components/__tests__/CitationSummaryGraph.test.jsx
- ui/src/common/components/__tests__/__snapshots__/CitationSummaryGraph.test.jsx.snap
- ui/src/common/containers/CitationSummaryGraphContainer.jsx
- ui/src/common/containers/__tests__/CitationSummaryGraphContainer.test.jsx
- ui/src/common/containers/__tests__/__snapshots__/CitationSummaryGraphContainer.test.jsx.snap
- ui/src/styleVariables.js
- ui/yarn.lock
* Added citation summary graph
* Updated react-vis
* INSPIR-2301
> ui: Added citation summary graph

- inspirehep/config.py
- tests/integration/records/test_views.py
* Added citation_count filter to the hep common filters
* This is needed for the citation summary graph interactivity
* INSPIR-2388
> facets: Added citation count filter

- inspirehep/config.py
- inspirehep/search/facets.py
- tests/integration/records/test_views.py
* Added citeable and refereed filters for search in literature and authors
* Excluded citeable, refereed and citation_count filters from the citation summary facet. This is needed for the table interactivity as the table must not update with those filters
* INSPIR-2388
> facets: added citeable and refereed filters

- e2e/tests/submissions/author.test.js
- e2e/utils/form.js
- scripts/setup
- ui/src/submissions/common/__tests__/__snapshots__/withFormItem.test.jsx.snap
- ui/src/submissions/common/withFormItem.jsx
> e2e: test author submission with existing orcid

- inspirehep/config.py
- inspirehep/factory.py
- tests/integration-async/records/conftest.py
- tests/integration/config/test_views_suggesters.py
- tests/integration/conftest.py
* Note: only literature and authors are tested
* INSPIR-2364
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.comk>
> config: add suggesters for all collections

- inspirehep/search/facets.py
- tests/integration/records/test_views.py
* Added key to citation summary citation count ranges with citation_count query for each range
* INSPIR-2388
> Added key to citation summary citation count ranges

- ui/src/authors/containers/DetailPage.jsx
- ui/src/common/authorization.js
- ui/src/common/containers/AuthorizedContainer.jsx
- ui/src/common/containers/__tests__/AuthorizedContainer.test.jsx
- ui/src/common/containers/__tests__/__snapshots__/AuthorizedContainer.test.jsx.snap
* Adds AuthorizedContainer to display parts of the UI based on user's
roles
* Displays CitationsSummaryTable and Grap for only superusers
> ui: add AuthorizedContainer to hide [WIP] features

- inspirehep/records/api/base.py
- tests/integration/records/api/test_api_literature.py
> citations: Remove non Literature collections from citations

- inspirehep/orcid/utils.py
- inspirehep/records/marshmallow/literature/base.py
- inspirehep/search/api.py
- inspirehep/search/mappings/v5/records/hep.json
- tests/integration/records/views/test_views_literature.py
> mappings: update hep mappings to tokenize $ref

- inspirehep/config.py
- inspirehep/migrator/tasks.py
> migrator: add special queue for continious migration

- inspirehep/config.py
- inspirehep/migrator/tasks.py
> migrator: fix typos

- inspirehep/alembic/c6570e49b7b2_change_record_citations_to_records_.py
- inspirehep/config.py
- inspirehep/records/api/mixins.py
- inspirehep/records/marshmallow/literature/base.py
- inspirehep/records/models.py
- inspirehep/records/views.py
- inspirehep/search/facets.py
- inspirehep/search/mappings/v5/records/hep.json
- tests/integration/records/api/test_api_base.py
- tests/integration/records/serializers/test_json.py
- tests/integration/records/views/test_views_literature.py
- tests/integration/test_alembic.py
* ADD: citations-by-year facet which returns json with summary of all citations for specified author
* INSPIR-2300
> facets: Add citations by year facet

- .gitignore
- inspirehep/search/mappings/v5/records/jobs.json
* INSPIR-2419
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.comk>
> mappings: update job mapping

- ui/src/authors/components/PositionsTimeline.jsx
- ui/src/authors/components/__tests__/PositionsTimeline.test.jsx
- ui/src/authors/components/__tests__/__snapshots__/PositionsTimeline.test.jsx.snap
- ui/src/authors/containers/DetailPage.jsx
- ui/src/common/components/CitationSummaryGraph/CitationSummaryGraph.jsx
- ui/src/common/components/CitationSummaryGraph/CitationSummaryGraph.scss
- ui/src/common/components/CitationSummaryTable/CitationSummaryTable.jsx
- ui/src/common/components/CitationSummaryTable/CitationSummaryTable.scss
- ui/src/common/components/CitationSummaryTable/__tests__/__snapshots__/CitationSummaryTable.test.jsx.snap
- ui/src/common/components/CitationsByYearGraph/CitationsByYearGraph.jsx
- ui/src/common/components/CitationsByYearGraph/__tests__/__snapshots__/CitationsByYearGraph.test.jsx.snap
- ui/src/common/components/__tests__/__snapshots__/CitationSummaryGraph.test.jsx.snap
* Changes UI of citations graphs and table
> ui: change author detail page layout

- inspirehep/config.py
- inspirehep/records/marshmallow/jobs/base.py
- inspirehep/records/serializers/__init__.py
- inspirehep/records/serializers/json.py
- tests/integration/records/views/test_views_jobs.py
* Added AcceleratorExperimentSchemaV1 to jobs
* This is needed for INSPIR-2339
> serializers: Use AcceleratorExperimentSchemaV1 for jobs

- inspirehep/config.py
- inspirehep/orcid/tasks.py
> orcid: add MIGRATION_REDIS_URL

- inspirehep/config.py
- poetry.lock
- pyproject.toml
* Adds SQLAlchemy-Continuum.
* INSPIR-2453
> setup: install `invenio-db` with versioning

- ui/src/common/components/CitationsByYearGraph/CitationsByYearGraph.jsx
- ui/src/common/components/CitationsByYearGraph/__tests__/CitationsByYearGraph.test.jsx
- ui/src/common/components/CitationsByYearGraph/__tests__/__snapshots__/CitationsByYearGraph.test.jsx.snap
* Added 0 for missing years in the citations by year graph
* INSPIR-2458
> ui: add 0 for missing years in the citations by year graph

- ui/src/authors/components/PositionsTimeline.jsx
- ui/src/authors/components/__tests__/__snapshots__/PositionsTimeline.test.jsx.snap
- ui/src/common/components/CitationSummaryGraph/CitationSummaryGraph.jsx
- ui/src/common/components/CitationSummaryGraph/CitationSummaryGraph.scss
- ui/src/common/components/ExpandListToggle.jsx
- ui/src/common/components/ExpandableInlineList/__tests__/__snapshots__/ExpandableInlineList.test.jsx.snap
- ui/src/common/components/RangeAggregation/RangeAggregation.jsx
- ui/src/common/components/RangeAggregation/__tests__/__snapshots__/RangeAggregation.test.jsx.snap
- ui/src/common/components/__tests__/AggregationFilter.test.jsx
- ui/src/common/components/__tests__/__snapshots__/AggregationFilter.test.jsx.snap
- ui/src/common/components/__tests__/__snapshots__/CitationSummaryGraph.test.jsx.snap
* Added a prop for the ExpandableListToggle label and used show all positions for author positions in the author profile
*  INSPIR-2440
* Add prop to the RangeAggregation for rendering the hovered tooltip
* INSPIR-2438
* Added pointer cursor when hovering citation summary graph bar
* INSPIR-2439
> Author profile changes

- tests/integration/migrator/test_migrator_cli.py
> migrator: fix flaky debug

- .travis.yml
- deploy-inspirehep.sh
- deploy-ui.sh
> travis: add inspirehep deployment

- inspirehep/submissions/loaders.py
- inspirehep/submissions/marshmallow/__init__.py
- inspirehep/submissions/marshmallow/job.py
- inspirehep/submissions/serializers.py
- poetry.lock
- tests/unit/submissions/test_jobs.py
Add: serializer and loader for job submission
*INSPIR-2430
> marshmallow: Add submission serializer for job

- poetry.lock
> setup: bump inspire-schemas

- inspirehep/search/mappings/v5/records/hep.json
> mappings: hep remove ``doc_values``

- inspirehep/pidstore/minters/base.py
- tests/integration/conftest.py
- tests/integration/pidstore/minters/test_minters_arxiv.py
- tests/integration/pidstore/minters/test_minters_doi.py
- tests/unit/pidstore/test_minters_base.py
> minters: dedup values

- inspirehep/search/factories/search.py
- tests/integration/records/views/test_views_authors.py
- tests/integration/records/views/test_views_citations.py
- tests/integration/records/views/test_views_jobs.py
- tests/integration/records/views/test_views_literature.py
- tests/integration/submissions/test_submissions_views.py
* added size to the search factory with only aggs so that it doesn't retrieve also search results INSPIR-2463
* Used freezegun in submission tests INSPIR-2277
> Don't get search results on facets endpoints

- Dockerfile
> docker: remove duplicate dependencies

- .travis.yml
- docker-compose.travis.yml
> travis: cleanup

- inspirehep/submissions/views.py
- tests/integration/submissions/test_submissions_views.py
* Does not create ticket when a job updated by a curator
> submissions: skip ticket for job update if curator

- .travis.yml
- build-docker-inspirehep-image.sh
- build-docker-ui-image.sh
- docker-compose.travis.yml
> travis: separate scripts for ui and inspirehep

- inspirehep/records/api/base.py
- inspirehep/records/api/literature.py
- tests/integration-async/records/indexer/test_indexer_cli.py
- tests/integration/records/api/test_api_base.py
> literature: fix for ``earliest_date``

- inspirehep/submissions/views.py
> jobs: fix link for update submissions in RT ticket

- Dockerfile
This reverts commit fcdb26874592ecc0299997d6aa989909ec5e4470.
> Revert "docker: remove duplicate dependencies"

- inspirehep/records/indexer/tasks.py
- inspirehep/search/api.py
- poetry.lock
- tests/integration-async/records/indexer/test_literature.py
- tests/integration/records/views/test_views_literature.py
* Added a check for _collections Literature in the ES citations query
* Fix the required positional argument error for the batch_index and make it use the request_timeout
* INSPIR-2477
> Add check for collections literature in the es citations query

- e2e/package.json
- e2e/tests/submissions/job.test.js
- e2e/utils/form.js
- e2e/utils/routes.js
- e2e/yarn.lock
- ui/src/submissions/common/components/RichTextEditor/RichTextEditor.jsx
- ui/src/submissions/common/components/RichTextEditor/__tests__/__snapshots__/RichTextEditor.test.jsx.snap
* Added e2e tests for job submission and update
* Added tests for StatusFieldContainer
* INSPIR-2493
> Add e2e tests for job submission

- inspirehep/rt/tickets.py
- inspirehep/submissions/tasks.py
- inspirehep/submissions/views.py
- tests/integration/submissions/test_submissions_views.py
- tests/unit/submissions/test_tasks.py
> submissions: make ticket creation async

- inspirehep/config.py
- tests/integration/records/serializers/test_json.py
- tests/integration/records/views/test_views_jobs.py
* Removed best-match sort for Literature
* Ordered deadline sort for jobs by latest first
* INSPIR-2504
* INSPIR-2509
> Remove best match sort and make deadline sort asc

- inspirehep/submissions/views.py
- tests/integration/submissions/test_submissions_views.py
* INSPIR-2508
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.comk>
> jobs: don't overwrite status if cataloger

- inspirehep/records/api/base.py
- tests/integration-async/records/api/test_base.py
> records: fix record versioning

- tests/integration/migrator/test_migrator_cli.py
> tests: fix the rest migration flaky tests

- ui/src/common/containers/SearchScopeSelectContainer.jsx
> ui: fix search scope select `...` bug

- ui/src/common/components/SelectBox.jsx
- ui/src/common/components/__tests__/__snapshots__/SelectBox.test.jsx.snap
- ui/src/common/containers/SearchScopeSelectContainer.jsx
* Also capitalizes 'O' for `other` rank value.
> ui: apply ... select option fix for all SelectBoxes

- inspirehep/config.py
- tests/integration/records/views/test_views_jobs/es_aggregations_cataloger_for_1735925.json
- tests/integration/records/views/test_views_jobs/es_aggregations_for_1735925.json
- ui/src/submissions/jobs/schemas/__tests__/job.test.js
- ui/src/submissions/jobs/schemas/job.js
> ui: rename "field of research" to "field of interest"

- ui/src/submissions/common/components/RichTextEditor/RichTextEditor.jsx
- ui/src/submissions/common/components/RichTextEditor/__tests__/__snapshots__/RichTextEditor.test.jsx.snap
> ui: fix RichTextEditor error icon

- ui/package.json
- ui/src/common/components/CitationsByYearGraph/CitationsByYearGraph.jsx
- ui/src/common/components/CitationsByYearGraph/__tests__/CitationsByYearGraph.test.jsx
- ui/yarn.lock
* Abbreviates numbers (1123 => 1.1K)
* INSPIR-2442
> ui: format citations by year graph Y axis

- inspirehep/records/marshmallow/literature/base.py
- tests/integration/migrator/test_migrator_cli.py
- tests/integration/records/indexer/test_indexer_literature.py
- tests/integration/records/indexer/test_indexer_literature/1503270.json
- tests/integration/records/views/test_views_literature.py
- tests/unit/records/marshmallow/literature/test_base_schema.py
> serializers: addition of ``related_records``

- inspirehep/config.py
- tests/integration/records/views/test_views_jobs.py
> jobs: change Deadline to Earliest Deadline

- poetry.lock
> setup: bump inspire-dojson

- ui/src/common/components/CitationSummaryGraph/CitationSummaryGraph.jsx
- ui/src/common/components/__tests__/__snapshots__/CitationSummaryGraph.test.jsx.snap
> ui: add tooltip for citation summary graph

- .gitignore
- README.md
- docker-compose.core.yml
- docker-compose.services.yml
- e2e/docker-compose.e2e.yml
- inspirehep/config.py
- inspirehep/utils.py
- run-e2e.sh
- scripts/setup
- tests/integration-async/records/conftest.py
- tests/integration/alembic/conftest.py
- tests/integration/alembic/test_alembic.py
- tests/integration/conftest.py
> alembic: migrations cleanup

- inspirehep/cli/__init__.py
- inspirehep/migrator/api.py
- inspirehep/migrator/cli.py
- inspirehep/migrator/config.py
- inspirehep/migrator/tasks.py
- inspirehep/migrator/utils.py
- inspirehep/orcid/cli.py
- tests/integration/migrator/test_migrator_cli.py
- tests/integration/orcid/test_orcid_cli.py
> cli: add continuous migration and orcid tokens import

- inspirehep/migrator/tasks.py
- inspirehep/records/api/base.py
- tests/integration/migrator/test_migrator_tasks.py
- tests/integration/records/api/test_api_base.py
- tests/integration/records/api/test_api_literature.py
> records/migrator: handle PID deletions correctly

- ui/src/actions/__tests__/submissions.test.js
- ui/src/actions/submissions.js
- ui/src/submissions/__tests__/__snapshots__/index.test.jsx.snap
- ui/src/submissions/__tests__/index.test.jsx
- ui/src/submissions/common/components/SubmissionSuccess.jsx
- ui/src/submissions/common/components/SubmissionSuccessPage.jsx
- ui/src/submissions/common/components/__tests__/SubmissionSuccess.test.jsx
- ui/src/submissions/common/components/__tests__/SubmissionSuccessPage.test.jsx
- ui/src/submissions/common/components/__tests__/__snapshots__/SubmissionSuccess.test.jsx.snap
- ui/src/submissions/common/components/__tests__/__snapshots__/SubmissionSuccessPage.test.jsx.snap
- ui/src/submissions/index.jsx
- ui/src/submissions/jobs/components/JobUpdateSubmissionSuccessPage.jsx
- ui/src/submissions/jobs/components/__tests__/JobUpdateSubmissionSuccessPage.test.jsx
- ui/src/submissions/jobs/components/__tests__/__snapshots__/JobUpdateSubmissionSuccessPage.test.jsx.snap
* Displays link to job detail page in the job update submission success
page.
* INSPIR-2517
> ui: dipslay record link on job update sub

- ui/src/App.scss
* Make vertical scrollbar always show
* INSPIR-2511
> Fix citation graph flickering

- ui/src/common/containers/AggregationFiltersContainer.jsx
- ui/src/common/containers/SortByContainer.jsx
- ui/src/common/containers/__tests__/AggregationFiltersContainer.test.jsx
- ui/src/common/containers/__tests__/SortByContainer.test.jsx
> ui: reset page selection on aggregation change

- ui/src/common/constants.js
- ui/src/common/containers/CitationSummaryGraphContainer.jsx
> ui: fix citations summ table query link bug

- inspirehep/submissions/tasks.py
- inspirehep/submissions/views.py
- tests/integration/submissions/test_submissions_views.py
* Broken by 5e1bb8642ca992b244136207e70027eca1cde347
> jobs: create ticket on new job submission

- ui/src/submissions/jobs/components/__tests__/__snapshots__/StatusField.test.jsx.snap
- ui/src/submissions/jobs/schemas/constants.js
* Added open option to status options users see when updating their open job
* INSPIR-2557
> Regular users should see also open option when updating job

- inspirehep/migrator/tasks.py
- tests/integration/migrator/test_migrator_tasks.py
* Replaces custom logging from inspire_utils with the
python build-in logging module.
* Validation errors are logged as warnings don't go to sentry any longer.
* PIDStore errors are formatted properly in the exception dashboard.
> migrator: improve logging

- ui/src/submissions/jobs/schemas/__tests__/job.test.js
- ui/src/submissions/jobs/schemas/job.js
> ui: allow past deadline if job status is closed

- inspirehep/records/marshmallow/base.py
- inspirehep/records/marshmallow/literature/base.py
- tests/integration/records/serializers/test_json.py
* Renamed id_ to uuid
* INSPIR-2572
* Added _collections to public schemas. This is needed for the record importer by url
* INSPIR-2575
> serializers: rename id_ to uuid and add _collections to publich schemas

- inspirehep/records/api/base.py
- tests/integration/records/api/test_api_base.py
* removed the InspireQueryBuilder
* INSPIR-2560
> records: Remove InspireQueryBuilder

- inspirehep/migrator/api.py
- inspirehep/migrator/tasks.py
- inspirehep/migrator/utils.py
- inspirehep/orcid/api.py
- inspirehep/orcid/converter.py
- inspirehep/orcid/domain_models.py
- inspirehep/orcid/putcode_getter.py
- inspirehep/orcid/tasks.py
- inspirehep/orcid/utils.py
- inspirehep/pidstore/api/base.py
- inspirehep/records/api/base.py
- inspirehep/records/api/literature.py
- inspirehep/records/api/mixins.py
- inspirehep/records/cli.py
- inspirehep/records/indexer/base.py
- inspirehep/records/indexer/cli.py
- inspirehep/records/indexer/tasks.py
- inspirehep/records/indexer/utils.py
- inspirehep/records/models.py
- inspirehep/records/receivers.py
- inspirehep/records/tasks.py
- inspirehep/rt/tickets.py
- inspirehep/search/api.py
- inspirehep/search/factories/search.py
- inspirehep/submissions/tasks.py
- inspirehep/submissions/views.py
> logging: make all loggers more consistent

- inspirehep/factory.py
- inspirehep/logger/ext.py
> logger: change default prefix

- inspirehep/records/config.py
* Sets size explicitly to 166 to include all arxiv_categories for Field
Of Interested facet.
* INSPIR-2585
> jobs: return all arxiv categories on facets

- inspirehep/records/api/literature.py
- inspirehep/records/marshmallow/literature/ui.py
- inspirehep/records/utils.py
- tests/integration/records/serializers/json/test_literature.py
> serializers: fix date issue

- ui/src/submissions/__tests__/__snapshots__/index.test.jsx.snap
- ui/src/submissions/__tests__/index.test.jsx
- ui/src/submissions/index.jsx
> submissions: make lit form accesiable to all users

- README.md
- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/utils.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/records/api/test_api_literature.py
- backend/tests/integration/records/serializers/json/test_literature.py
> disambiguation: add phonetic blocks and uuids to authors in lit records

- ui/src/App.scss
- ui/src/common/components/AggregationFilters.jsx
- ui/src/common/components/__tests__/__snapshots__/AggregationFilters.test.jsx.snap
- ui/src/styleVariables.js
> ui: add pb for inline agg filters upto lg screens

- ui/src/common/constants.js
- ui/src/submissions/common/components/FieldInfoAlert.jsx
- ui/src/submissions/common/components/__tests__/FieldInfoAlert.test.jsx
- ui/src/submissions/common/components/__tests__/__snapshots__/FieldInfoAlert.test.jsx.snap
- ui/src/submissions/jobs/components/JobForm.jsx
> ui: add deadline info for postdoc submissions

- ui/src/authors/containers/DetailPageContainer.jsx
> ui: give betausers access to author profile feats

- backend/inspirehep/records/api/literature.py
- backend/tests/integration/config/test_views_suggesters.py
- backend/tests/integration/conftest.py
- backend/tests/integration/records/api/test_api_literature.py
- backend/tests/integration/records/serializers/json/test_literature.py
- backend/tests/integration/records/serializers/test_bibtex.py
- backend/tests/integration/records/views/test_views_literature.py
> disambiguation: push phonetic blocks to redis on update/create

- backend/Dockerfile
> docker: speedup requirements installation

- backend/poetry.lock
- backend/pyproject.toml
> setup: drop invenio dependency

- backend/poetry.lock
- backend/pyproject.toml
> setup: bump inspire-utils

- ui/src/jobs/components/SubscribeJobsModalButton.jsx
- ui/src/jobs/components/__tests__/SubscribeJobsModalButton.test.jsx
- ui/src/jobs/components/__tests__/__snapshots__/SubscribeJobsModalButton.test.jsx.snap
- ui/src/jobs/containers/SearchPageContainer.jsx
- ui/src/jobs/subscribeJobMailingList.js
> ui: add subscribe jobs link and modal

- backend/inspirehep/logger/config.py
- backend/inspirehep/logger/ext.py
- backend/inspirehep/migrator/api.py
- backend/inspirehep/migrator/tasks.py
- backend/inspirehep/migrator/utils.py
- backend/inspirehep/orcid/api.py
- backend/inspirehep/orcid/converter.py
- backend/inspirehep/orcid/domain_models.py
- backend/inspirehep/orcid/putcode_getter.py
- backend/inspirehep/orcid/tasks.py
- backend/inspirehep/orcid/utils.py
- backend/inspirehep/pidstore/api/base.py
- backend/inspirehep/pidstore/minters/base.py
- backend/inspirehep/pidstore/providers/recid.py
- backend/inspirehep/records/api/base.py
- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/api/mixins.py
- backend/inspirehep/records/cli.py
- backend/inspirehep/records/indexer/base.py
- backend/inspirehep/records/indexer/tasks.py
- backend/inspirehep/records/indexer/utils.py
- backend/inspirehep/records/receivers.py
- backend/inspirehep/records/tasks.py
- backend/inspirehep/search/factories/search.py
- backend/inspirehep/submissions/views.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/migrator/test_migrator_tasks.py
This commit introduces the structlog library and modifies the way
we log information. It also adds the structlog-sentry extension
in order to properly send structured logs to sentry.
* INSPIR-2564
> logs: add structlog library and changed logging

- backend/inspirehep/logger/config.py
- backend/inspirehep/logger/ext.py
> logger: remove the default flask logger handler

- backend/tests/integration/mailing/test_providers_mailchimp.py
> mailing: fix flaky tests

- backend/tests/integration/mailing/conftest.py
- backend/tests/integration/mailing/test_cli.py
- backend/tests/integration/records/serializers/json/test_jobs.py
> tests: fix flaky test on jobs api

- backend/inspirehep/mailing/api/jobs.py
- backend/inspirehep/mailing/config.py
- backend/inspirehep/mailing/loaders.py
- backend/inspirehep/mailing/providers/mailchimp.py
- backend/inspirehep/mailing/views.py
- backend/tests/integration/mailing/cassettes/test_subscirbe_to_the_list.yaml
- backend/tests/integration/mailing/cassettes/test_view_subscribe_to_list.yaml
- backend/tests/integration/mailing/test_api_jobs.py
- backend/tests/integration/mailing/test_providers_mailchimp.py
- backend/tests/integration/mailing/test_views.py
- ui/src/jobs/subscribeJobMailingList.js
> mailing: add subscribe endpoint for jobs weekly

- backend/inspirehep/records/config.py
- backend/inspirehep/records/marshmallow/experiments/es.py
- backend/tests/integration/records/indexer/test_indexer_experiments.py
- backend/tests/unit/records/marshmallow/experiments/test_es.py
> suggesters: add weights for experiment suggester

- backend/tests/unit/submissions/test_jobs.py
- ui/src/submissions/jobs/components/JobForm.jsx
- ui/src/submissions/jobs/schemas/constants.js
- ui/src/submissions/jobs/schemas/job.js
> submissions: handle "other" for field of interest

- ui/src/common/layouts/Header/HeaderMenu.jsx
- ui/src/common/layouts/Header/__tests__/__snapshots__/HeaderMenu.test.jsx.snap
> ui: make job submission link public

- ui/src/authors/components/AuthorName.jsx
- ui/src/authors/containers/DetailPageContainer.jsx
- ui/src/authors/utils.js
- ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx
- ui/ui-tests/tests/authors/detail.test.js
- ui/ui-tests/tests/jobs/detail.test.js
- ui/ui-tests/tests/literature/detail.test.js
* Also adds tests for all detail pages
> ui: fix doc title for author and literature

- backend/inspirehep/records/config.py
- backend/tests/integration/records/views/test_views_jobs.py
> jobs: hide sorting

- backend/inspirehep/mailing/api/jobs.py
- backend/inspirehep/mailing/config.py
- backend/inspirehep/mailing/providers/mailtrain.py
- backend/tests/integration/mailing/cassettes/test_mailtrain_subscribe_user_to_list.yaml
- backend/tests/integration/mailing/cassettes/test_subscirbe_to_the_list.yaml
- backend/tests/integration/mailing/conftest.py
- backend/tests/integration/mailing/test_providers_mailtrain.py
> subscription: MailChimp replaced for Mailtrain

- backend/inspirehep/records/config.py
- backend/tests/integration/records/views/test_views_jobs.py
> jobs: only sort by most recent

- backend/inspirehep/mailing/api/jobs.py
- backend/inspirehep/mailing/cli.py
- backend/inspirehep/mailing/config.py
- backend/inspirehep/mailing/errors.py
- backend/inspirehep/mailing/providers/sendgrid.py
- backend/inspirehep/mailing/templates/mailing/jobs/deadline_passed/base.html
- backend/inspirehep/records/api/jobs.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/mailing/cassettes/test_send_email.yaml
- backend/tests/integration/mailing/conftest.py
- backend/tests/integration/mailing/data/1735925.json
- backend/tests/integration/mailing/data/1745106.json
- backend/tests/integration/mailing/test_api_jobs.py
- backend/tests/integration/mailing/test_cli.py
- backend/tests/integration/mailing/test_providers_sendgrid.py
- backend/tests/integration/records/api/test_api_jobs.py
> cli: add command to send emails for expired jobs

- ui/src/jobs/components/Description.jsx
- ui/src/jobs/components/JobItem.jsx
- ui/src/jobs/components/JobTitle.jsx
- ui/src/jobs/components/__tests__/JobTitle.test.jsx
- ui/src/jobs/components/__tests__/__snapshots__/JobItem.test.jsx.snap
- ui/src/jobs/components/__tests__/__snapshots__/JobTitle.test.jsx.snap
- ui/src/jobs/containers/DetailPageContainer.jsx
> ui: display external job id for catalogers

- ui/src/common/__tests__/utils.test.js
- ui/src/common/utils.js
- ui/src/literature/__tests__/citeArticle.test.js
- ui/src/literature/citeArticle.js
- ui/src/literature/components/CiteModalAction.jsx
- ui/src/literature/components/__tests__/CiteModalAction.test.jsx
- ui/src/literature/components/__tests__/__snapshots__/CiteModalAction.test.jsx.snap
> ui: improved error handling for cite

- backend/inspirehep/mailing/views.py
- backend/tests/integration/mailing/data/rss.xml
- backend/tests/integration/mailing/test_cli.py
- backend/tests/integration/mailing/test_views.py
> jobs: add rss feed for weekly jobs

- backend/inspirehep/mailing/views.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/mailing/data/rss.xml
- backend/tests/integration/mailing/test_cli.py
> mailing: change from atom to rss feed

- backend/inspirehep/mailing/templates/mailing/jobs/weekly/base.html
> mailing: replace mailchimp tags with mailtrain tags

- backend/inspirehep/mailing/api/jobs.py
- backend/tests/integration/mailing/conftest.py
- backend/tests/integration/mailing/data/1234567.json
- backend/tests/integration/mailing/data/1234568.json
> mailing: send weekly mail only for open jobs

- ui/src/authors/components/AuthorLinkedinAction.jsx
- ui/src/authors/components/AuthorTwitterAction.jsx
- ui/src/authors/components/AuthorWebsitesAction.jsx
- ui/src/authors/components/__tests__/__snapshots__/AuthorLinkedinAction.test.jsx.snap
- ui/src/authors/components/__tests__/__snapshots__/AuthorTwitterAction.test.jsx.snap
- ui/src/authors/components/__tests__/__snapshots__/AuthorWebsitesAction.test.jsx.snap
> ui: add tooltips on links

- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/views.py
- backend/tests/integration/records/views/test_views_article.py
- ui/src/submissions/literature/components/DataImporter.jsx
- ui/src/submissions/literature/components/__tests__/DataImporter.test.jsx
- ui/src/submissions/literature/components/__tests__/__snapshots__/DataImporter.test.jsx.snap
> submissions: better error message when paper exists

- ui/public/outdated-browser.html
Which will be used by INSPIR-2729
* INSPIR-2726
> ui: add outdated-browser page

- ui/src/authors/components/AuthorEmailsAction.jsx
- ui/src/authors/components/__tests__/__snapshots__/AuthorEmailsAction.test.jsx.snap
> ui: add tooltip for author emails

- backend/inspirehep/records/api/base.py
- backend/inspirehep/records/indexer/tasks.py
- backend/inspirehep/records/receivers.py
- backend/tests/integration-async/records/indexer/test_literature.py
- backend/tests/integration/records/api/test_api_base.py
> records: minor fixes in ``hard_delete``

- backend/inspirehep/records/marshmallow/literature/latex.py
- backend/tests/integration/records/serializers/test_latex.py
> serializers: Latex serializer won't display supervisors as authors

- backend/inspirehep/mailing/api/jobs.py
- backend/inspirehep/mailing/config.py
- backend/inspirehep/mailing/providers/mailtrain.py
- backend/tests/integration/mailing/test_providers_mailtrain.py
> mailing: fix jobs email title and size

- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/marshmallow/literature/common/reference_item.py
- backend/inspirehep/search/api.py
- backend/tests/integration/search/test_api.py
- backend/tests/unit/records/marshmallow/literature/common/test_abstract_source.py
- backend/tests/unit/records/marshmallow/literature/common/test_reference_item.py
> serializers: Get referenced records from ES

- ui/src/common/layouts/Header/HeaderMenu.jsx
- ui/src/common/layouts/Header/__tests__/__snapshots__/HeaderMenu.test.jsx.snap
> ui: Enable new literature forms

- backend/inspirehep/records/api/base.py
- backend/inspirehep/records/indexer/base.py
- backend/inspirehep/records/indexer/tasks.py
- backend/inspirehep/records/receivers.py
- backend/tests/integration/conftest.py
- backend/tests/integration/mailing/conftest.py
- backend/tests/integration/records/indexer/test_indexer_authors.py
- backend/tests/integration/records/indexer/test_indexer_conferences.py
- backend/tests/integration/records/indexer/test_indexer_data.py
- backend/tests/integration/records/indexer/test_indexer_experiments.py
- backend/tests/integration/records/indexer/test_indexer_institutions.py
- backend/tests/integration/records/indexer/test_indexer_jobs.py
- backend/tests/integration/records/indexer/test_indexer_journals.py
- backend/tests/integration/records/indexer/test_indexer_literature.py
- backend/tests/integration/records/views/test_views_literature.py
- backend/tests/unit/records/api/test_base.py
> record: centralize indexing records

- backend/poetry.lock
- backend/pyproject.toml
Use hepcrawl version 13.0.5 which solves the repeated inspire_categories issue
> global: bump hepcrawl

- backend/inspirehep/mailing/api/jobs.py
- backend/tests/integration/mailing/test_api_jobs.py
- backend/tests/integration/mailing/test_cli.py
> mailing: use right args for send_email

- backend/inspirehep/records/marshmallow/literature/es.py
- backend/inspirehep/records/marshmallow/utils.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
- backend/tests/integration/disambiguation/test_tasks.py
- backend/tests/integration/migrator/test_migrator_cli.py
- backend/tests/integration/records/serializers/json/test_authors.py
- backend/tests/integration/records/views/test_views_citations.py
- backend/tests/unit/records/marshmallow/author/test_ui.py
> serializers: use control_number instead of BAI on facet_author_name

- backend/inspirehep/config.py
- backend/inspirehep/factory.py
- backend/inspirehep/views.py
- backend/setup.py
- backend/tests/integration/config/test_views_suggesters.py
- backend/tests/integration/conftest.py
- backend/tests/integration/migrator/test_migrator_cli.py
- backend/tests/integration/records/views/cassettes/test_import_article_view_404_non_existing_doi.yaml
- backend/tests/integration/records/views/test_views_article.py
- backend/tests/integration/records/views/test_views_citations.py
- backend/tests/integration/records/views/test_views_literature.py
- backend/tests/integration/test_factory.py
- backend/tests/integration/test_views.py
- docker-compose.services.yml
> app: add displatcher middleware without host name checking

- ui/src/actions/__tests__/user.test.js
- ui/src/actions/user.js
> ui: soft-reload on logout

- backend/inspirehep/disambiguation/tasks.py
- backend/inspirehep/disambiguation/utils.py
> disambiguation: Add counters for disambiguation stats

- backend/inspirehep/migrator/api.py
> migrator: change log to contain the number of records

- ui/src/jobs/components/ContactList.jsx
- ui/src/jobs/components/__tests__/__snapshots__/ContactList.test.jsx.snap
> ui: change separator in job detail contacts

- backend/inspirehep/mailing/templates/mailing/jobs/deadline_passed/base.html
> mailing: add https to deadline passed

- ui/src/home/components/HowToSearch.jsx
- ui/src/home/components/__tests__/__snapshots__/HowToSearch.test.jsx.snap
> ui: remove author-count from the search tips table

- backend/inspirehep/records/config.py
- backend/inspirehep/search/facets.py
- backend/tests/integration/search/test_facets.py
> facets: display 'arxiv category' & 'subject' for curators in profiles

- backend/inspirehep/submissions/views.py
- backend/tests/integration/submissions/test_submissions_views.py
> views: fix job updates without acquisition_source

- ui/src/user/components/LoginPage/LoginPage.jsx
- ui/src/user/components/LoginPage/__tests__/__snapshots__/LoginPage.test.jsx.snap
* INSPIR-2798
Also changed the 'What is ORCID' link from `a` to `ExternalLink` for uniformity.
> ui: change text in login

- backend/inspirehep/records/marshmallow/literature/common/external_system_identifier.py
- backend/inspirehep/records/marshmallow/literature/ui.py
- backend/tests/integration/conftest.py
- backend/tests/integration/records/indexer/test_indexer_literature.py
- backend/tests/integration/records/serializers/json/test_literature.py
- backend/tests/unit/records/marshmallow/literature/test_ui.py
> literature: Add fulltext_links

- backend/inspirehep/config.py
> config: files change sotrage path dimensions

- backend/inspirehep/celery.py
* INSPIR-2795
Same as https://github.com/inspirehep/inspire-next/pull/3896.
> celery: kill process on OperationalError

- backend/inspirehep/submissions/marshmallow/literature.py
- backend/tests/integration/submissions/test_submissions_views.py
- backend/tests/unit/submissions/test_literature.py
> submissions: add preprint_date to form data

- backend/inspirehep/records/marshmallow/literature/es.py
- backend/tests/integration/records/api/test_api_literature.py
* Handle exception for the bibtex and latex display fields so the indexing doesn't fail
* INSPIR-2663
> cite: handle exception for the bibtex and latex display fields

- backend/inspirehep/logger/ext.py
- ui/src/index.js
> global: add release tags for sentry

- ui/src/common/components/CitationList.jsx
- ui/src/common/components/EmptyOrChildren.jsx
- ui/src/common/components/__tests__/EmptyOrChildren.test.jsx
- ui/src/common/components/__tests__/__snapshots__/CitationList.test.jsx.snap
- ui/src/common/components/__tests__/__snapshots__/EmptyOrChildren.test.jsx.snap
- ui/src/literature/components/ReferenceList.jsx
- ui/src/literature/components/__tests__/__snapshots__/ReferenceList.test.jsx.snap
> ui: display empty message for citations and refs

- backend/inspirehep/celery.py
- backend/inspirehep/disambiguation/tasks.py
- backend/inspirehep/disambiguation/utils.py
- backend/poetry.lock
- backend/pyproject.toml
> worker: expose prometheus metrics on worker.

- backend/poetry.lock
> bump: inspire-dojson v62.1.1

- backend/inspirehep/records/serializers/bibtex.py
- backend/inspirehep/records/serializers/latex.py
> cite: Fallback to empty string if display fields are missing

- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/api/mixins.py
- backend/tests/integration/records/api/cassettes/test_regression_add_original_url_if_it_is_external.yaml
- backend/tests/integration/records/api/cassettes/test_regression_do_not_add_original_url_if_it_is_not_external.yaml
- backend/tests/integration/records/api/test_api_mixins.py
* In inspire-schema ``original_url`` the ``original_url``
should be a valid ``uri``.
> records: do not add original_url if it is a local url

- ui/src/common/__tests__/utils.test.js
- ui/src/common/components/EmbeddedSearch.jsx
- ui/src/common/components/__tests__/__snapshots__/EmbeddedSearch.test.jsx.snap
- ui/src/common/utils.js
- ui/src/literature/components/CiteAllAction.jsx
- ui/src/literature/components/CiteModalAction.jsx
- ui/src/literature/components/__tests__/CiteAllAction.test.jsx
- ui/src/literature/components/__tests__/__snapshots__/CiteAllAction.test.jsx.snap
- ui/src/literature/constants.js
- ui/src/literature/containers/CiteAllActionContainer.jsx
- ui/src/literature/containers/SearchPageContainer.jsx
- ui/src/literature/containers/__tests__/CiteAllActionContainer.test.jsx
* Remove page from the cite query in the author profile
* Update cite limit to 1000
* INSPIR-2844
> cite: remove page from cite query in author profile and update limit

- backend/inspirehep/records/config.py
- backend/inspirehep/search/facets.py
- backend/tests/integration/records/views/test_views_conferences.py
- backend/tests/integration/search/test_facets.py
> facets: Add contributions facets

- ui/package.json
- ui/src/App.jsx
- ui/src/common/config.js
- ui/src/common/hooks/__tests__/__snapshots__/usePrevious.test.jsx.snap
- ui/src/common/hooks/__tests__/usePrevious.test.jsx
- ui/src/common/hooks/usePrevious.js
- ui/src/common/layouts/Header/BetaInfoBanner.jsx
- ui/src/common/layouts/Header/Header.jsx
- ui/src/common/layouts/Header/Header.scss
- ui/src/common/layouts/Header/InterventionBanner.jsx
- ui/src/common/layouts/Header/__tests__/Header.test.jsx
- ui/src/common/layouts/Header/__tests__/HeaderContainer.test.jsx
- ui/src/common/layouts/Header/__tests__/InterventionBanner.test.jsx
- ui/src/common/layouts/Header/__tests__/__snapshots__/Header.test.jsx.snap
- ui/src/common/layouts/Header/__tests__/__snapshots__/InterventionBanner.test.jsx.snap
- ui/src/setupTests.js
- ui/yarn.lock
> ui: add banner on top of the menu bar to display messages

- backend/inspirehep/alembic/e5e43ad8f861_add_index_for_objectversion_key.py
- backend/inspirehep/records/api/mixins.py
- backend/tests/integration/alembic/test_alembic.py
- backend/tests/integration/records/api/cassettes/test_add_same_file_twice_do_not_update_updated_column_on_file_instance_table.yaml
- backend/tests/integration/records/api/test_api_mixins.py
* Remove signal for Timestamp.before_update event for all invenio_files_rest.model models
* Add index for files_object table on key and is_head columns
> files: Quick fixes for files

- backend/inspirehep/alembic/f563233434cd_add_conference_literature_table.py
- backend/inspirehep/migrator/tasks.py
- backend/inspirehep/records/api/base.py
- backend/inspirehep/records/api/conferences.py
- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/api/mixins.py
- backend/inspirehep/records/cli.py
- backend/inspirehep/records/models.py
- backend/inspirehep/records/tasks.py
- backend/tests/integration-async/conftest.py
- backend/tests/integration-async/migrator/test_migrator_tasks.py
- backend/tests/integration/alembic/test_alembic.py
- backend/tests/integration/migrator/test_migrator_tasks.py
- backend/tests/integration/records/api/test_api_conferences.py
- backend/tests/integration/records/api/test_api_literature.py
- backend/tests/integration/records/api/test_api_mixins.py
- backend/tests/integration/records/test_tasks.py
> conferences_relation_table: Add conference_literature table

- backend/inspirehep/mailing/api/jobs.py
- backend/tests/integration/mailing/test_api_jobs.py
> mailing: don't use null CC from contact_details

- ui/src/actions/__tests__/citations.test.js
- ui/src/actions/citations.js
- ui/src/common/components/CitationList.jsx
- ui/src/common/components/__tests__/CitationList.test.jsx
- ui/src/common/components/__tests__/__snapshots__/CitationList.test.jsx.snap
- ui/src/common/containers/CitationListContainer.jsx
- ui/src/common/containers/__tests__/CitationListContainer.test.jsx
- ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx
- ui/src/reducers/__tests__/citations.test.js
- ui/src/reducers/citations.js
> citations: refactor CitationList pagination

- backend/inspirehep/records/api/base.py
- backend/inspirehep/records/api/conferences.py
- backend/inspirehep/records/api/data.py
- backend/inspirehep/records/api/mixins.py
- backend/inspirehep/records/indexer/tasks.py
- backend/inspirehep/records/marshmallow/base.py
- backend/inspirehep/records/marshmallow/common/mixins.py
- backend/inspirehep/records/marshmallow/conferences/base.py
- backend/inspirehep/records/marshmallow/conferences/common/proceeding_info_item.py
- backend/inspirehep/records/marshmallow/conferences/es.py
- backend/inspirehep/records/marshmallow/conferences/ui.py
- backend/inspirehep/records/marshmallow/literature/common/publication_info_item.py
- backend/inspirehep/records/marshmallow/literature/ui.py
- backend/tests/integration-async/records/api/test_literature.py
- backend/tests/integration-async/records/indexer/test_conferences.py
- backend/tests/integration/records/api/test_api_conferences.py
- backend/tests/integration/records/api/test_api_mixins.py
- backend/tests/integration/records/indexer/test_indexer_conferences.py
- backend/tests/integration/records/serializers/json/test_conferences.py
- backend/tests/unit/records/marshmallow/conferences/common/test_proceeding_info_item.py
- backend/tests/unit/records/marshmallow/conferences/test_base.py
- backend/tests/unit/records/marshmallow/literature/common/test_publication_info_item.py
- backend/tests/unit/records/marshmallow/test_marshmallow_base.py
Little cleanup in the serializers code
* INSPIR-2850
> serializers: add serializers for conferences

- backend/inspirehep/records/marshmallow/literature/es.py
- backend/inspirehep/records/serializers/bibtex.py
- backend/tests/integration/records/api/test_api_literature.py
- backend/tests/unit/records/test_bibtex.py
> bibtex: Fix error when serializing broken data

- backend/inspirehep/records/config.py
> conferences: enable PUT

- ui/src/conferences/components/ConferenceContributions.jsx
- ui/src/conferences/components/__tests__/ConferenceContributions.test.jsx
- ui/src/conferences/components/__tests__/__snapshots__/ConferenceContributions.test.jsx.snap
- ui/src/conferences/containers/DetailPageContainer.jsx
- ui/src/reducers/search.js
Adds conference contributions search/display to conference detail page.
> ui: add conference contributions search

- backend/inspirehep/migrator/tasks.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/migrator/fixtures/1695012.xml
- backend/tests/integration/migrator/test_migrator_tasks.py
> migrator: job record migration doesn't raise anymore

- ui/src/literature/containers/LiteratureSearchContainer.jsx
> ui: fix typo in 0 results message

- backend/inspirehep/records/api/literature.py
- backend/tests/integration-async/records/indexer/test_literature.py
> citation_count: reindex references when un-superseded

- backend/inspirehep/logger/config.py
- backend/inspirehep/migrator/tasks.py
- backend/inspirehep/records/cli.py
- backend/inspirehep/records/indexer/cli.py
- backend/inspirehep/records/indexer/utils.py
- backend/inspirehep/records/tasks.py
- backend/tests/integration-async/conftest.py
> migrator: Trying to fix few errors on migration

- backend/inspirehep/logger/ext.py
> logger: handle generation of metrics for 404

- backend/inspirehep/records/config.py
- backend/inspirehep/records/serializers/json/conferences.py
- backend/tests/integration/records/views/test_views_conferences.py
- ui/package.json
- ui/src/common/components/AggregationFilter.jsx
- ui/src/common/components/AggregationFilters.jsx
- ui/src/common/components/DateRangeAggregation.jsx
- ui/src/common/components/RangeAggregation/RangeAggregation.jsx
- ui/src/common/components/__tests__/AggregationFilter.test.jsx
- ui/src/common/components/__tests__/AggregationFilters.test.jsx
- ui/src/common/components/__tests__/DateRangeAggregation.test.jsx
- ui/src/common/components/__tests__/__snapshots__/AggregationFilter.test.jsx.snap
- ui/src/common/components/__tests__/__snapshots__/AggregationFilters.test.jsx.snap
- ui/src/common/components/__tests__/__snapshots__/DateRangeAggregation.test.jsx.snap
- ui/src/common/components/__tests__/__snapshots__/SearchScopeSelect.test.jsx.snap
- ui/src/common/constants.js
- ui/src/conferences/components/ConferenceItem.jsx
- ui/src/conferences/components/ConferenceWebsitesAction.jsx
- ui/src/conferences/components/__tests__/ConferenceItem.test.jsx
- ui/src/conferences/components/__tests__/__snapshots__/ConferenceItem.test.jsx.snap
- ui/src/conferences/components/__tests__/__snapshots__/ConferenceWebsitesAction.test.jsx.snap
- ui/src/conferences/containers/DetailPageContainer.jsx
- ui/src/conferences/containers/SearchPageContainer.jsx
- ui/src/reducers/search.js
* Added search  conferences
* INSPIR-2857
> conferences: search

- ui/src/reducers/__tests__/search.test.js
- ui/src/reducers/search.js
> ui: do not override query with baseQuery

- ui/src/authors/containers/AuthorPublicationsContainer.jsx
- ui/src/conferences/components/ConferenceContributions.jsx
- ui/src/conferences/components/__tests__/__snapshots__/ConferenceContributions.test.jsx.snap
- ui/src/literature/containers/LiteratureSearchContainer.jsx
- ui/src/literature/containers/SearchPage.jsx
> ui: empty box w/ 0 results in lit search, conf contrib & author pub

- ui/src/authors/containers/AuthorPublicationsContainer.jsx
> ui: rename '0 publications' to '0 research works'

- ui/src/middlewares/__tests__/logoutUser.test.jsx
- ui/src/middlewares/logoutUserOn401.js
- ui/src/store.js
> submissions: Change the submission forms to dispatch logout for 401

- ui/src/jobs/components/SubscribeJobsForm.jsx
- ui/src/jobs/components/SubscribeJobsModalButton.jsx
- ui/src/jobs/components/__tests__/SubscribeJobsForm.test.jsx
- ui/src/jobs/components/__tests__/SubscribeJobsModalButton.test.jsx
- ui/src/jobs/components/__tests__/__snapshots__/SubscribeJobsForm.test.jsx.snap
- ui/src/jobs/components/__tests__/__snapshots__/SubscribeJobsModalButton.test.jsx.snap
- ui/src/jobs/subscribeJobMailingList.js
Also uses Formik and yup for the form, as in submission forms
INSPIR-2694
> ui: validate jobs subscribe form on client side

- backend/inspirehep/logger/config.py
> logger: fix logging of celery failed tasks

- ui/src/submissions/common/schemas/constants.js
- ui/src/submissions/conferences/components/ConferenceForm.jsx
- ui/src/submissions/conferences/schemas/__tests__/conference.test.js
- ui/src/submissions/conferences/schemas/conference.js
- ui/src/submissions/jobs/components/JobForm.jsx
- ui/src/submissions/jobs/schemas/__tests__/job.test.js
- ui/src/submissions/jobs/schemas/constants.js
- ui/src/submissions/jobs/schemas/job.js
- ui/src/submissions/literature/components/BasicInfoFields.jsx
- ui/src/submissions/literature/schemas/constants.js
- ui/src/submissions/literature/schemas/sections/__tests__/basicInfo.test.js
- ui/src/submissions/literature/schemas/sections/basicInfo.js
ConferenceForm, `field_of_interest` field accepts inspire categories
unlike JobForm's arxiv_categories
INSPIR-2858
> ui: use inspire_categories for conference FoI.

- backend/inspirehep/records/config.py
- backend/inspirehep/search/facets.py
- backend/tests/integration/records/views/test_views_conferences.py
* start_date range filter that handles special values like `upcoming`
and `all`
INSPIR-2969
> conferences: custom start_date range filter

- backend/inspirehep/records/config.py
- backend/inspirehep/search/facets.py
> facets: new option for single author in number of authors facet

- e2e/tests/submissions/author.test.js
- ui/src/submissions/common/components/SubmitButton.jsx
- ui/src/submissions/common/components/__tests__/SubmitButton.test.jsx
- ui/src/submissions/common/components/__tests__/__snapshots__/SubmitButton.test.jsx.snap
> submission: make submit button always enabled

- backend/Dockerfile
- backend/poetry.lock
- backend/pyproject.toml
> setup: add oauth2server fork and remove xrootd deps

- backend/inspirehep/migrator/tasks.py
- backend/tests/integration-async/migrator/test_migrator_tasks.py
> migrator: reindex conferences when lit record updates in migration step

- backend/inspirehep/submissions/loaders.py
- backend/inspirehep/submissions/marshmallow/__init__.py
- backend/inspirehep/submissions/marshmallow/conferences.py
- backend/inspirehep/submissions/marshmallow/job.py
- backend/inspirehep/submissions/serializers.py
- backend/inspirehep/submissions/views.py
- backend/tests/integration/submissions/test_submissions_views.py
This commit is adding a new endpoint for conferences submission and related serializer.
* INSPIR-2853
> submission: add view and serializer for conference

- ui/src/submissions/conferences/components/ConferenceForm.jsx
> ui: make conference country select searchable

- ui/src/common/components/SearchScopeSelect.jsx
- ui/src/common/components/__tests__/__snapshots__/SearchScopeSelect.test.jsx.snap
> conferences: display conferences in dropdown

- backend/inspirehep/records/config.py
- backend/inspirehep/search/mappings/v5/records/conferences.json
- backend/tests/integration/config/test_views_suggesters.py
This commit to properly run needs:
* Remap con
* Reindex con
* INSPIR-2853
> conferences: add series suggester

- backend/inspirehep/records/cli.py
> global: fix F401 errors

- backend/inspirehep/cli.py
- backend/inspirehep/records/cli.py
- backend/tests/integration/records/test_cli.py
> cli: add cli to close jobs with a deadline_date before the given date

- build-docker-backend-image.sh
- build-docker-ui-image.sh
> deploy: update deployment scripts

- ui/src/submissions/literature/components/CommentsField.jsx
> ui: add missing tooltip to Comments field in lit submission

- backend/tests/helpers/cleanups.py
Tries to catch ES exception about wrong records when deleting index content.
> tests: fix random async test failure

- .travis.yml
- README.md
- backend/Dockerfile
- backend/poetry.lock
- backend/pyproject.toml
Let's try this :crossed_fingers:
> deps: update celery to v4.4.0

- ui/src/common/components/InlineList/InlineList.jsx
- ui/src/conferences/components/ConferenceSeries.jsx
- ui/src/conferences/components/__tests__/ConferenceSeries.test.jsx
- ui/src/conferences/components/__tests__/__snapshots__/ConferenceSeries.test.jsx.snap
> ui: display several series

- backend/inspirehep/records/config.py
- backend/inspirehep/search/facets.py
- backend/poetry.lock
- backend/tests/integration/records/views/test_views_authors.py
- backend/tests/integration/records/views/test_views_literature.py
- backend/tests/integration/search/test_facets.py
> facets: add a facet on _collections for curators

- ui/src/conferences/containers/DetailPageContainer.jsx
> ui: fix series display

- backend/inspirehep/records/api/mixins.py
- backend/inspirehep/search/api.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/conftest.py
- backend/tests/integration/records/api/test_api_literature.py
- backend/tests/integration/search/test_api.py
> records: don't allow record to cite itself

- backend/inspirehep/rt/templates/rt/new_conference.html
- backend/inspirehep/submissions/views.py
- backend/inspirehep/utils.py
- backend/tests/integration/submissions/test_submissions_views.py
> submissions: send rt ticket when user submits conference

- backend/inspirehep/errors.py
- backend/inspirehep/pidstore/errors.py
- backend/inspirehep/pidstore/minters/base.py
- backend/inspirehep/records/config.py
- backend/tests/integration/pidstore/minters/test_minters_arxiv.py
- backend/tests/integration/pidstore/minters/test_minters_cnum.py
- backend/tests/integration/pidstore/minters/test_minters_doi.py
- backend/tests/integration/pidstore/minters/test_minters_orcid.py
- backend/tests/integration/records/api/test_api_jobs.py
- backend/tests/integration/records/views/test_views.py
> pidstore: proper HTTP error if PID is already exists

- backend/inspirehep/records/api/authors.py
- backend/inspirehep/records/api/base.py
- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/api/mixins.py
- backend/inspirehep/records/indexer/tasks.py
- backend/inspirehep/search/api.py
- backend/tests/integration-async/records/api/test_base.py
- backend/tests/integration-async/records/indexer/test_authors.py
- backend/tests/integration/records/api/test_api_authors.py
> indexer: reindex authors papers when his name changes

- backend/inspirehep/records/api/base.py
- backend/inspirehep/records/indexer/tasks.py
> indexer: stop waiting for results

- backend/inspirehep/mailing/cli.py
- backend/inspirehep/mailing/templates/mailing/jobs/deadline_passed/base.html
- backend/tests/integration/mailing/test_cli.py
> jobs: send email to submitter only 2 times

- ui/src/authors/containers/NumberOfCiteablePapersContainer.jsx
- ui/src/authors/containers/NumberOfPublishedPapersContainer.jsx
- ui/src/authors/containers/__tests__/NumberOfCiteablePapersContainer.test.jsx
- ui/src/authors/containers/__tests__/NumberOfPublishedPapersContainer.test.jsx
- ui/src/common/containers/CitationSummaryGraphContainer.jsx
- ui/src/common/containers/__tests__/CitationSummaryGraphContainer.test.jsx
Resets page to 1 for author publications search, when query is changed
from citation summary components
* INSPIR-3046
> ui: reset author publications pagination

- backend/inspirehep/mailing/api/conferences.py
- backend/inspirehep/mailing/config.py
- backend/inspirehep/mailing/templates/mailing/conferences/submission_confirmation/base.html
- backend/inspirehep/mailing/templates/mailing/jobs/deadline_passed/base.html
- backend/inspirehep/submissions/views.py
- backend/tests/integration/mailing/test_api_conferences.py
- backend/tests/integration/submissions/test_submissions_views.py
> conferences: send confirmation email at user submission

- backend/inspirehep/submissions/views.py
- backend/tests/integration/submissions/test_submissions_views.py
- ui/src/actions/__tests__/submissions.test.js
- ui/src/reducers/__tests__/submissions.test.js
- ui/src/reducers/submissions.js
- ui/src/submissions/jobs/components/StatusField.jsx
- ui/src/submissions/jobs/components/__tests__/StatusField.test.jsx
- ui/src/submissions/jobs/components/__tests__/__snapshots__/StatusField.test.jsx.snap
- ui/src/submissions/jobs/containers/StatusFieldContainer.jsx
> jobs: disallow status change after 30 days

- backend/inspirehep/records/config.py
- backend/tests/integration/records/views/test_views_conferences.py
- ui/src/reducers/search.js
> conferences: change conferences sorting options

- backend/inspirehep/records/config.py
- backend/tests/integration/records/views/test_views_jobs.py
> jobs: add deadline sort option back

- ui/src/user/components/LoginPage/LoginPage.jsx
- ui/src/user/components/LoginPage/__tests__/__snapshots__/LoginPage.test.jsx.snap
> ui: change login text

- backend/inspirehep/records/marshmallow/literature/ui.py
- backend/tests/unit/records/marshmallow/literature/test_ui.py
> literature: add ads links for arxiv papers

- .travis.yml
- backend/inspirehep/records/config.py
- backend/tests/integration/config/test_views_suggesters.py
fix travis.yml on 'after_script'
INSPIR-3036
> config: ignore duplicates on series suggester

- ui/public/config.js
- ui/src/common/layouts/Header/Header.jsx
> ui: simplify & fix Header.onHeightChange

- backend/demofile.txt
- backend/inspirehep/files/__init__.py
- backend/inspirehep/files/api/__init__.py
- backend/inspirehep/files/api/s3.py
- backend/inspirehep/files/config.py
- backend/inspirehep/files/ext.py
- backend/inspirehep/files/proxies.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/setup.py
- backend/tests/integration/conftest.py
- backend/tests/integration/files/fixtures/file.txt
- backend/tests/integration/files/test_api_s3.py
- backend/tests/integration/files/test_ext.py
> files: integrate boto to inspirehep

- backend/inspirehep/search/api.py
- backend/tests/integration/search/test_factories_search.py
> search: fix 10k limit on total

- backend/inspirehep/search/facets.py
> search: slight improvement of scripted aggregation

- ui/src/jobs/components/JobStatusAlert.jsx
- ui/src/jobs/components/__tests__/JobStatusAlert.test.jsx
- ui/src/jobs/components/__tests__/__snapshots__/JobStatusAlert.test.jsx.snap
- ui/src/jobs/containers/DetailPageContainer.jsx
> ui: display banner when job is pending

- ui/src/authors/containers/DetailPageContainer.jsx
> ui: fix stale citations-by-year data

- ui/src/user/loginInNewTab.js
> ui: login prefix with ``/api``

- backend/inspirehep/accounts/views.py
- backend/inspirehep/config.py
- ui/docker/nginx/config/local.conf
- ui/src/actions/__tests__/user.test.js
- ui/src/actions/user.js
- ui/src/user/logout.js
- ui/ui-tests/__api_recordings__/Login_1441655762/recording.har
- ui/ui-tests/server.js
> accounts: move local login and logout to hep

- ui/src/submissions/common/components/SubmissionSuccess.jsx
- ui/src/submissions/common/components/__tests__/__snapshots__/SubmissionSuccess.test.jsx.snap
- ui/src/submissions/common/components/__tests__/__snapshots__/SubmissionSuccessPage.test.jsx.snap
> ui: change job submission success text

- backend/inspirehep/accounts/config.py
> accounts: update ORCID config

- backend/inspirehep/records/api/literature.py
- backend/tests/integration/records/views/test_views_article.py
> records: update import view to be case insensitive for DOIs

- backend/inspirehep/migrator/api.py
- backend/inspirehep/migrator/tasks.py
- backend/tests/integration-async/migrator/test_migrator_api.py
- backend/tests/integration/migrator/test_migrator_api.py
> Use explicit end in continuous migration

- ui/docker/nginx/config/nginx.conf
> ui: add rendertron rules in nginx

- ui/src/common/components/UserFeedback/UserFeedback.jsx
- ui/src/common/components/UserFeedback/__tests__/__snapshots__/UserFeedback.test.jsx.snap
- ui/src/common/constants.js
- ui/src/common/layouts/Footer/Footer.jsx
> ui: update text in user feedback form when there is adblock

- ui/src/App.jsx
- ui/src/__tests__/App.test.jsx
- ui/src/__tests__/tracker.test.js
- ui/src/authors/containers/AuthorPublicationsContainer.jsx
- ui/src/common/PrivateRoute.jsx
- ui/src/common/__tests__/PrivateRoute.test.jsx
- ui/src/common/__tests__/authorization.test.js
- ui/src/common/authorization.js
- ui/src/common/components/__tests__/Suggester.test.jsx
- ui/src/common/containers/AuthorizedContainer.jsx
- ui/src/common/containers/__tests__/AuthorizedContainer.test.jsx
- ui/src/common/layouts/Header/HeaderMenu.jsx
- ui/src/common/layouts/Header/HeaderMenuContainer.jsx
- ui/src/common/layouts/Header/__tests__/HeaderMenu.test.jsx
- ui/src/common/layouts/Header/__tests__/HeaderMenuContainer.test.jsx
- ui/src/jobs/components/__tests__/__snapshots__/JobTitle.test.jsx.snap
- ui/src/middlewares/__tests__/actionTracker.test.js
- ui/src/middlewares/actionTracker.js
- ui/src/submissions/jobs/containers/StatusFieldContainer.jsx
> ui: do not convert user roles to Set

- backend/inspirehep/search/api.py
- backend/tests/integration/search/test_factories_search.py
> search: add default_operator AND

- backend/inspirehep/orcid/cli.py
I've been doing this manually a few times in the last couple of days following user requests, a CLI command makes it easier.
> orcid: add push-records CLI

- ui/src/conferences/containers/ConferenceStartDateFilterContainer.jsx
- ui/src/conferences/containers/__tests__/ConferenceStartDateFilterContainer.test.jsx
> ui: change conf sort based on start_date

- ui/src/conferences/components/ConferenceSeries.jsx
- ui/src/conferences/components/__tests__/ConferenceSeries.test.jsx
- ui/src/conferences/components/__tests__/__snapshots__/ConferenceSeries.test.jsx.snap
> ui: fix conferences series query

- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/utils.py
- backend/tests/integration/records/api/test_api_literature.py
- backend/tests/integration/records/test_utils.py
> literature: add $ref for conferences in literature

- backend/inspirehep/orcid/domain_models.py
- backend/inspirehep/orcid/putcode_getter.py
> orcid: don't log responses

- backend/inspirehep/records/indexer/cli.py
- backend/tests/integration/records/indexer/test_remap_cli.py
> cli: Add CLI for remaping indexes

- backend/inspirehep/search/mappings/v7/records/conferences.json
> mappings: case insensitive search in conferences

- backend/inspirehep/accounts/views.py
- backend/inspirehep/orcid/tasks.py
- backend/tests/helpers/factories/models/user_access_token.py
- backend/tests/integration/accounts/test_views.py
- backend/tests/integration/conftest.py
- backend/tests/integration/orcid/test_orcid_tasks.py
> orcid: push user literature when setting enabled

- backend/inspirehep/records/marshmallow/jobs/base.py
- backend/inspirehep/submissions/marshmallow/job.py
- backend/inspirehep/submissions/utils.py
- backend/inspirehep/submissions/views.py
- backend/tests/integration/records/serializers/json/test_jobs.py
> submissions: fix job to be editable

- backend/inspirehep/records/api/mixins.py
- backend/inspirehep/records/utils.py
- backend/poetry.lock
- backend/tests/integration/records/views/test_views_literature.py
> records: fix issues with incorrect date displayed in records

- ui/src/jobs/containers/DetailPageContainer.jsx
> jobs: fix missing control number

- ui/src/middlewares/syncLocationWithSearch.js
> ui: fix bug with trailing slash in search pages

- backend/inspirehep/pidstore/api/authors.py
- backend/inspirehep/pidstore/minters/bai.py
- backend/tests/helpers/providers/record_provider.py
- backend/tests/integration/pidstore/minters/test_minters_bai.py
> minter: add BAI minter

- backend/inspirehep/search/mappings/v7/records/authors.json
- backend/inspirehep/search/mappings/v7/records/conferences.json
- backend/inspirehep/search/mappings/v7/records/data.json
- backend/inspirehep/search/mappings/v7/records/experiments.json
- backend/inspirehep/search/mappings/v7/records/hep.json
- backend/inspirehep/search/mappings/v7/records/institutions.json
- backend/inspirehep/search/mappings/v7/records/journals.json
> mappings: Add _created and _updated mappings

- backend/inspirehep/pidstore/providers/cnum.py
- backend/tests/integration/pidstore/minters/test_minters_cnum.py
> cnum_provider: fix issues with wrong cnums when holes in cnums sequence

- ui/src/common/layouts/Footer/Footer.jsx
- ui/src/common/layouts/Footer/__tests__/__snapshots__/Footer.test.jsx.snap
> ui: link to privacy policy and terms of use pages

- backend/inspirehep/migrator/cli.py
- backend/inspirehep/records/marshmallow/literature/bibtex.py
- backend/tests/integration/records/api/test_api_literature.py
- backend/tests/unit/records/marshmallow/literature/test_bibtex_schema.py
- ui/package.json
> BibTeX: add "\ " after "." in journal title

- ui/package.json
- ui/yarn.lock
Fixes broken pages due to problematic latex
https://github.com/harunurhan/react-latex-next/pull/11
* INSPIR-3248
> ui: bump latex package

- ui/src/literature/components/LiteratureItem.jsx
- ui/src/literature/components/__tests__/LiteratureItem.test.jsx
- ui/src/literature/components/__tests__/__snapshots__/LiteratureItem.test.jsx.snap
> ui: display links for literature search

- backend/poetry.lock
- backend/pyproject.toml
Reverts inspirehep/inspirehep#785
> Revert "setup: temp query parser testing"

- backend/inspirehep/records/marshmallow/literature/bibtex.py
- backend/tests/unit/records/marshmallow/literature/test_bibtex_schema.py
> bibtex: change doc_type of cof. papers with journal title to article

- ui/craco.config.js
PR: #784 introduced a bug for dev webpack config.
> ui: fix `yarn start`

- backend/inspirehep/search/facets.py
- backend/tests/integration/search/test_facets.py
> facets: reoder doc type facet

- ui/src/literature/containers/SearchPage.jsx
- ui/src/reducers/__tests__/search.test.js
- ui/src/reducers/search.js
> ui: fix cit sum for lit search as initial route

- ui/src/literature/containers/LiteratureSearchContainer.jsx
- ui/src/literature/containers/SearchPage.jsx
- ui/src/reducers/__tests__/search.test.js
- ui/src/reducers/search.js
As discovered the bug fixed on #791, was happening for citation summary
for author's publication and conference's contributions. Therefore this
fixes all cases.
> ui: fix inconsistent cite summary display

- backend/inspirehep/search/aggregations.py
- backend/tests/integration/search/test_aggregations.py
> facets: rename date facet

- backend/inspirehep/records/serializers/bibtex.py
- backend/tests/integration/records/serializers/test_bibtex.py
> bibtex: remove escaping from math expressions

- backend/inspirehep/records/config.py
- backend/inspirehep/search/aggregations.py
- backend/inspirehep/search/facets.py
- backend/inspirehep/serializers.py
- backend/tests/integration/records/views/test_views_authors.py
- backend/tests/integration/records/views/test_views_literature.py
- backend/tests/integration/search/test_aggregations.py
- backend/tests/integration/search/test_facets.py
- backend/tests/unit/test_serializers.py
> facets: Add exclude RPP facet

- README.md
- backend/poetry.lock
- backend/pyproject.toml
* Bumps python version to 3.7
* Bumps celery to v4.4.1
* Bumps invenio-base to v1.2.2
* Bumps invenio-i18n to v1.2.0
* Bumps invenio-pidstore to v1.2.0
> setup: update dependencies

- backend/inspirehep/records/api/base.py
- backend/inspirehep/records/marshmallow/literature/bibtex.py
- backend/tests/integration/orcid/cassettes/TestOrcidPushTask.test_push_new_work_already_existing.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPushTask.test_push_new_work_happy_flow.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPushTask.test_push_new_work_invalid_data_orcid.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherDuplicatedIdentifier.test_duplicated_external_identifier_pusher_exception.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherDuplicatedIdentifier.test_exc_in_apply_celery_task_with_retry.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherDuplicatedIdentifier.test_happy_flow_post.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherDuplicatedIdentifier.test_happy_flow_put.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_already_existing.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_already_existing_putcode_exception.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_already_existing_with_recids.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_happy_flow.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_invalid_data_orcid.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_invalid_data_token.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherPutUpdatedWork.test_push_updated_work_happy_flow.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherPutUpdatedWork.test_push_updated_work_invalid_data_orcid.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherPutUpdatedWork.test_push_updated_work_invalid_data_putcode.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherPutUpdatedWork.test_push_updated_work_invalid_data_token.yaml
- backend/tests/integration/orcid/cassettes/TestOrcidPusherRecordDBVersion.test_happy_flow.yaml
- backend/tests/integration/records/api/test_api_base.py
- backend/tests/unit/records/marshmallow/literature/test_bibtex_schema.py
> bibtex: get year from earliest date too

- backend/inspirehep/records/marshmallow/literature/ui.py
- backend/tests/unit/records/marshmallow/literature/test_ui.py
> marshmallow: Include all links which are not hidden to fulltext_links

- backend/poetry.lock
- backend/tests/integration/migrator/test_migrator_tasks/1313624.xml
* INSPIR-3291
* Needs remigrating
> setup: bump inspire-dosjon

- ui/package.json
- ui/yarn.lock
* Solves INSPIR-3276
This is a bit of workaround because antd wants to release this as a
minor release so they are still waiting (2 weeks already). So this
enforces sub dependency upgrade to fixes the issue.
> ui: do not truncate select dropdown width

- ui/src/common/components/CitationSummaryTable/CitationSummaryTable.jsx
- ui/src/common/components/CitationSummaryTable/__tests__/CitationSummaryTable.test.jsx
- ui/src/common/components/CitationSummaryTable/__tests__/__snapshots__/CitationSummaryTable.test.jsx.snap
https://sentry.inspirehep.net/inspire-prod/ui/issues/17676/
> ui: Fix error when numbers in the CitationSummaryTable are null

- backend/inspirehep/search/aggregations.py
- backend/tests/integration/search/test_facets.py
> facets: show more authors

- ui/src/submissions/literature/containers/LiteratureSubmissionPageContainer.jsx
> ui: change the selection policy in lit submission

- backend/inspirehep/legacy/views.py
- backend/tests/integration/legacy/test_views.py
> views: fix redirect from legacy search when query is empty

- backend/inspirehep/access_control.py
- backend/inspirehep/accounts/decorators.py
- backend/inspirehep/records/config.py
- backend/tests/integration/accounts/test_decorators.py
- backend/tests/integration/records/views/test_views_authors.py
- backend/tests/integration/records/views/test_views_literature.py
> literature: hide hidden collections from non curators

- ui/src/App.scss
> ui: fix modal overlapping

- backend/inspirehep/search/aggregations.py
- backend/tests/integration/records/views/test_views_literature.py
- backend/tests/integration/search/test_aggregations.py
- ui/src/common/components/CitationSummaryTable/CitationSummaryTable.jsx
- ui/src/common/components/CitationSummaryTable/__tests__/__snapshots__/CitationSummaryTable.test.jsx.snap
- ui/src/common/constants.js
> urls: Change published url

- ui/src/App.scss
- ui/src/common/layouts/Footer/Footer.scss
- ui/src/styleVariables.js
> ui: fix dropdowns in modals

- ui/src/authors/containers/DetailPageContainer.jsx
- ui/src/conferences/containers/DetailPageContainer.jsx
- ui/src/jobs/containers/DetailPageContainer.jsx
- ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx
> ui: fix pending or closed jobs and deleted banners width

- ui/src/App.scss
- ui/src/common/components/GuideModal.jsx
This is naive solution which we will revert when we have implement a
new Carousel that doesn't use Modal
> ui: increase modal padding for big modal + banner

- backend/inspirehep/records/marshmallow/literature/bibtex.py
- backend/tests/unit/records/marshmallow/literature/test_bibtex_schema.py
> bibtex: use article type for report

- ui/src/submissions/common/components/DateField.jsx
> ui: disable browser autocomplete for DateField

- ui/package.json
- ui/yarn.lock
> ui: bump sentry client major version

- ui/src/common/components/CarouselModal/CarouselModal.jsx
- ui/src/common/components/CarouselModal/CarouselModal.scss
- ui/src/literature/components/Figures/Figure.scss
* also fixes figure border color
> ui: make big figures scrollable

- ui/src/index.js
> ui: polyfill Object.entries

- backend/inspirehep/config.py
- backend/inspirehep/legacy/views.py
- backend/tests/integration/legacy/test_views.py
> views: redirect /collection and profile management from/to legacy

- ui/package.json
- ui/src/home/components/WhatsNew.jsx
- ui/yarn.lock
This is the initial UI, that's why it not displayed at the moment
> ui: add what's new section with blog posts

- backend/inspirehep/config.py
- backend/inspirehep/search/factories/query.py
- backend/inspirehep/search/utils.py
- backend/tests/integration/search/test_factories_query.py
- backend/tests/integration/search/test_utils.py
> search: increase maxrecursiondepth for resolving query string

- backend/inspirehep/submissions/marshmallow/conferences.py
- backend/tests/integration/submissions/test_submissions_views.py
> submission: check also official_name of country not only 'name'

- ui/package.json
- ui/src/App.jsx
- ui/src/index.js
- ui/src/tracker.js
- ui/yarn.lock
> ui: improve user count tracking for sentry issues

- ui/src/institutions/components/InstitutionsHistoricalDataList.jsx
- ui/src/institutions/components/__tests__/InstitutionsHistoricalDataList.test.jsx
- ui/src/institutions/components/__tests__/__snapshots__/InstitutionsHistoricalDataList.test.jsx.snap
- ui/src/institutions/containers/DetailPageContainer.jsx
> institutions: display public notes and historical data

- backend/inspirehep/alembic/cea5fa2e5d2c_add_institution_literature_table.py
- backend/inspirehep/indexer/tasks.py
- backend/inspirehep/migrator/tasks.py
- backend/inspirehep/records/api/base.py
- backend/inspirehep/records/api/institutions.py
- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/api/mixins.py
- backend/inspirehep/records/marshmallow/institutions/base.py
- backend/inspirehep/records/models.py
- backend/inspirehep/records/tasks.py
- backend/inspirehep/search/mappings/v7/records/institutions.json
- backend/inspirehep/utils.py
- backend/tests/integration-async/migrator/test_migrator_tasks.py
- backend/tests/integration-async/records/indexer/test_institutions.py
- backend/tests/integration/alembic/test_alembic.py
- backend/tests/integration/indexer/test_indexer_institutions.py
- backend/tests/integration/records/api/test_api_institutions.py
- backend/tests/integration/records/api/test_api_mixins.py
- backend/tests/integration/records/serializers/json/test_institutions.py
- backend/tests/integration/records/test_tasks.py
- backend/tests/unit/records/marshmallow/institutions/test_es.py
- ui/src/institutions/components/InstitutionItem.jsx
- ui/src/institutions/components/__tests__/InstitutionItem.test.jsx
- ui/src/institutions/components/__tests__/__snapshots__/InstitutionItem.test.jsx.snap
* INSPIR-3312
* Needs institution remapping
* Needs alembic upgrade
* Needs remigration
> institutions: add institution literature table and papers count

- backend/inspirehep/files/api/s3.py
- backend/tests/integration/files/test_api_s3.py
- backend/tests/integration/records/api/test_api_literature.py
So that they can be display inside browsers, not downloaded immediately.
> files: make `inline`

- ui/src/institutions/__tests__/utils.test.js
- ui/src/institutions/components/InstitutionAddress.jsx
- ui/src/institutions/components/InstitutionAddressList.jsx
- ui/src/institutions/components/InstitutionItem.jsx
- ui/src/institutions/components/__tests__/InstitutionAddress.test.jsx
- ui/src/institutions/components/__tests__/InstitutionAddressList.test.jsx
- ui/src/institutions/components/__tests__/__snapshots__/InstitutionAddress.test.jsx.snap
- ui/src/institutions/components/__tests__/__snapshots__/InstitutionAddressList.test.jsx.snap
- ui/src/institutions/components/__tests__/__snapshots__/InstitutionItem.test.jsx.snap
- ui/src/institutions/containers/DetailPageContainer.jsx
- ui/src/institutions/utils.js
> institutions: modify address display

- backend/inspirehep/records/marshmallow/literature/bibtex.py
- backend/tests/unit/records/marshmallow/literature/test_bibtex_schema.py
> bibtex: add editors from parent record

- backend/poetry.lock
> setup: bump inspire-query-parser and inspire-schemas

- backend/inspirehep/orcid/domain_models.py
- backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_already_existing_and_delete_duplicated_records_different_putcodes.yaml
- backend/tests/integration/orcid/fixtures/test_orcid_domain_models_TestOrcidPusherPostNewWork_conflicting_no_recid.xml
- backend/tests/integration/orcid/test_orcid_domain_models.py
> orcid: handle multiple ORCID putcodes for the same record

- backend/inspirehep/records/marshmallow/literature/common/reference_item.py
- backend/tests/integration/records/serializers/json/test_literature.py
- backend/tests/unit/records/marshmallow/literature/common/test_reference_item.py
> literature: refactor reference_item schema

- backend/inspirehep/editor/__init__.py
- backend/inspirehep/editor/errors.py
- backend/inspirehep/editor/views.py
- backend/setup.py
- backend/tests/integration-async/conftest.py
- backend/tests/integration-async/editor/test_editor_api.py
> views: move revision endpoints to hep

- backend/inspirehep/alembic/595c36d68964_add_authors_to_records_table_and_update_.py
- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/api/mixins.py
- backend/inspirehep/records/models.py
- backend/tests/integration/alembic/test_alembic.py
- backend/tests/integration/records/api/test_api_literature.py
> record.models: add authors_records table

- ui/src/common/components/SearchBox/SearchBox.jsx
nd an empty message aborts the commit.
> ui: fix search history bug when input is null

- ui/src/common/constants.js
- ui/src/holdingpen/components/ExceptionsTable.jsx
> ui: fix exceptions dashboard edit links

- backend/inspirehep/search/mappings/v7/records/hep.json
- backend/tests/integration/records/serializers/json/test_literature.py
> mappings: case insensitive search for dois in hep mapping

- backend/inspirehep/records/marshmallow/literature/common/author.py
- backend/inspirehep/records/marshmallow/literature/es.py
- backend/inspirehep/records/marshmallow/literature/ui.py
- backend/inspirehep/search/mappings/v7/records/hep.json
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/indexer/test_indexer_literature.py
- backend/tests/unit/records/marshmallow/literature/common/test_author.py
* INSPIR-3397
* Needs remapping and reindexing of lit
> search: add first_author

- ui/src/common/containers/PaginationContainer.jsx
> ui: scroll to top after page/size change

- backend/inspirehep/records/api/base.py
- backend/inspirehep/records/api/mixins.py
- backend/inspirehep/records/marshmallow/literature/common/author.py
- backend/inspirehep/records/marshmallow/literature/es.py
- backend/inspirehep/search/mappings/v7/records/hep.json
- backend/poetry.lock
- backend/tests/integration-async/migrator/test_migrator_tasks.py
- backend/tests/integration/indexer/test_indexer_literature.py
- backend/tests/integration/records/api/test_api_mixins.py
- ui/src/institutions/components/__tests__/__snapshots__/InstitutionItem.test.jsx.snap
- ui/src/institutions/utils.js
* INSPIR-3443
* Needs remigration
> institutions: use more fields for number of papers

- backend/inspirehep/indexer/cli.py
> indexer: change error message when provided wrong pid type to be easier to understand

- ui/src/authors/components/Advisors/Advisor.jsx
- ui/src/authors/components/Advisors/Advisors.jsx
- ui/src/authors/components/Advisors/AdvisorsOfDegree.jsx
- ui/src/authors/components/Advisors/__tests__/Advisor.test.jsx
- ui/src/authors/components/Advisors/__tests__/Advisors.test.jsx
- ui/src/authors/components/Advisors/__tests__/AdvisorsOfDegree.test.jsx
- ui/src/authors/components/Advisors/__tests__/__snapshots__/Advisor.test.jsx.snap
- ui/src/authors/components/Advisors/__tests__/__snapshots__/Advisors.test.jsx.snap
- ui/src/authors/components/Advisors/__tests__/__snapshots__/AdvisorsOfDegree.test.jsx.snap
- ui/src/authors/components/Advisors/index.js
- ui/src/authors/containers/DetailPageContainer.jsx
- ui/src/common/constants.js
- ui/src/submissions/common/schemas/constants.js
> ui: display advisors

- ui/ui-tests/tests/institutions/detail.test.js
- ui/ui-tests/tests/institutions/search.test.js
- ui/ui-tests/utils/constants.js
> institutions: add ui tests

- backend/inspirehep/records/marshmallow/literature/common/reference_item.py
- backend/tests/integration/records/serializers/json/test_literature.py
> literature: fix empty reference bug

- backend/inspirehep/migrator/tasks.py
> migrator: fix legacy url

- backend/poetry.lock
> setup: bump query parser

- backend/inspirehep/search/aggregations.py
- backend/tests/integration/search/test_aggregations.py
> facets: rename "papers per year" to "date of paper"

- backend/inspirehep/records/marshmallow/literature/common/author.py
- backend/inspirehep/search/mappings/v7/records/authors.json
- backend/inspirehep/search/mappings/v7/records/hep.json
- backend/tests/unit/records/marshmallow/literature/common/test_author.py
> remove name variations

- backend/inspirehep/cli.py
- backend/inspirehep/indexer/cli.py
- backend/tests/integration/indexer/test_cli.py
> cli: overwrite Invenio reindex and remap with Inspire commands

- backend/inspirehep/search/facets.py
- backend/inspirehep/search/mappings/v7/records/hep.json
- backend/tests/integration/records/views/test_views_citations.py
*FIX: citation_summary is not reading 'exclude-self-citations' parameter properly
*mappings: Remove unnecessary mapping for citations_by_year_without_self_citations
> facets: fix citation_summary facet

- backend/inspirehep/records/config.py
- backend/tests/integration/records/views/test_views_institutions.py
- ui/src/common/components/EditRecordAction.jsx
- ui/src/common/components/__tests__/EditRecordAction.test.jsx
- ui/src/common/components/__tests__/__snapshots__/EditRecordAction.test.jsx.snap
- ui/src/common/constants.js
- ui/src/common/routes.js
- ui/src/institutions/components/InstitutionItem.jsx
- ui/src/institutions/components/__tests__/__snapshots__/InstitutionItem.test.jsx.snap
- ui/src/institutions/containers/DetailPageContainer.jsx
> institutions: enable editor

- ui/src/common/components/DocumentHead.jsx
- ui/src/common/components/__tests__/DocumentHead.test.jsx
- ui/src/common/components/__tests__/__snapshots__/DocumentHead.test.jsx.snap
- ui/src/conferences/components/ConferenceDates.jsx
- ui/src/literature/components/LiteratureDocumentHead.jsx
- ui/src/literature/components/__tests__/LiteratureDocumentHead.test.jsx
- ui/src/literature/components/__tests__/__snapshots__/LiteratureDocumentHead.test.jsx.snap
- ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx
(Used by Google Scholar)
INSPIR-3479
> ui: add citation_* meta tags for literature

- backend/inspirehep/alembic/020b99d0beb7_add_index_to_records_authors_table.py
- backend/inspirehep/records/marshmallow/literature/es.py
- backend/inspirehep/search/mappings/v7/records/hep.json
- backend/poetry.lock
- backend/tests/integration/alembic/test_alembic.py
- backend/tests/integration/indexer/test_indexer_literature.py
- backend/tests/unit/records/indexer/test_base.py
- backend/tests/unit/records/marshmallow/literature/common/test_abstract_source.py
- backend/tests/unit/records/marshmallow/literature/test_es_schema.py
* INSPIR-3368
* Needs remapping (adding new field) and reindexing of lit
> refersto: Add referenced authors bais to es for querying refersto a

- backend/inspirehep/config.py
- backend/inspirehep/indexer/cli.py
- backend/inspirehep/pidstore/api/__init__.py
- backend/inspirehep/pidstore/api/seminars.py
- backend/inspirehep/pidstore/minters/control_number.py
- backend/inspirehep/records/api/__init__.py
- backend/inspirehep/records/api/seminars.py
- backend/inspirehep/records/config.py
- backend/inspirehep/records/marshmallow/seminars/base.py
- backend/inspirehep/records/marshmallow/seminars/es.py
- backend/inspirehep/records/serializers/__init__.py
- backend/inspirehep/records/serializers/json/__init__.py
- backend/inspirehep/records/serializers/json/seminars.py
- backend/inspirehep/search/api.py
- backend/inspirehep/search/mappings/v7/records/seminars.json
- backend/poetry.lock
- backend/setup.py
- backend/tests/helpers/providers/record_provider.py
- backend/tests/integration/indexer/test_indexer_seminars.py
- backend/tests/integration/indexer/test_indexer_seminars/1.json
- backend/tests/integration/pidstore/minters/test_minters_control_number.py
- backend/tests/integration/records/api/test_api_seminars.py
- backend/tests/integration/records/serializers/json/test_seminars.py
- backend/tests/integration/records/serializers/json/test_seminars/1.json
- backend/tests/integration/records/views/test_views_seminars.py
- backend/tests/unit/records/api/test_base.py
- ui/src/common/constants.js
- ui/src/common/routes.js
> seminars: Base work (minters, constants, record class, mappings, views)

- ui/src/common/containers/PaginationContainer.jsx
> ui: change scrollTo arguments for browser support

- backend/poetry.lock
> setup: bump query-parser

- backend/poetry.lock
> setup: bump hepcrawl

- backend/inspirehep/search/mappings/v7/records/hep.json
* INSPIR-3459
* requires reindexing
> mappings: search authors with several surnames

- backend/inspirehep/mailing/api/seminars.py
- backend/inspirehep/mailing/config.py
- backend/inspirehep/mailing/templates/mailing/seminars/confirmation_new.html
- backend/inspirehep/rt/templates/rt/new_seminar.html
- backend/inspirehep/rt/templates/rt/update_seminar.html
- backend/inspirehep/submissions/views.py
- backend/tests/integration/mailing/test_api_seminars.py
- backend/tests/integration/submissions/test_submissions_views.py
* Also sends confirmation email to the user when a new seminar is submitted.
> seminars: create tickets for submissions

- backend/inspirehep/migrator/tasks.py
- backend/inspirehep/records/tasks.py
> migrator: autoretry on OperationalError in update_relations task

- backend/inspirehep/submissions/marshmallow/seminars.py
- backend/tests/integration/submissions/test_submissions_views.py
Also adds tests for submitting and updating only with minimum amount of fields (required)
> seminars: fix addressless update bug

- backend/inspirehep/records/config.py
- backend/inspirehep/records/marshmallow/authors/es.py
- backend/poetry.lock
- backend/tests/integration/config/test_views_suggesters.py
- backend/tests/integration/records/api/test_api_authors.py
- ui/src/submissions/authors/components/AuthorForm.jsx
- ui/src/submissions/common/components/AuthorSuggesterField.jsx
- ui/src/submissions/common/components/ContactsField.jsx
- ui/src/submissions/common/getSuggestionSourceNameValue.js
- ui/src/submissions/jobs/components/JobForm.jsx
- ui/src/submissions/literature/components/LiteratureAuthorsField.jsx
- ui/src/submissions/seminars/components/SeminarForm.jsx
> submissions: improve author suggester

- backend/inspirehep/records/marshmallow/literature/common/author.py
- backend/inspirehep/records/marshmallow/seminars/common/__init__.py
- backend/inspirehep/records/marshmallow/seminars/common/speaker.py
- backend/inspirehep/records/marshmallow/seminars/ui.py
- backend/inspirehep/records/marshmallow/utils.py
- backend/tests/integration/indexer/test_indexer_seminars/1.json
- backend/tests/integration/records/serializers/json/test_seminars.py
- backend/tests/integration/records/serializers/json/test_seminars/1.json
- backend/tests/unit/records/marshmallow/seminars/common/test_speaker.py
> seminars: add first_name and last_name to ui serializers

- backend/inspirehep/access_control.py
- backend/inspirehep/records/config.py
- backend/tests/helpers/factories/models/user_access_token.py
- backend/tests/helpers/utils.py
- backend/tests/integration/records/views/test_views_literature.py
> authentication: token authentication check for roles

- backend/inspirehep/migrator/tasks.py
- backend/tests/integration/migrator/test_migrator_cli.py
> migrator: fix stop_after_one_step fails as task_uuid is passed

- backend/inspirehep/indexer/cli.py
- backend/tests/integration/indexer/test_cli.py
> indexer: add cli to add aliases without prefix if prefix is set

- backend/inspirehep/sitemap/collections.py
- backend/tests/integration/sitemap/test_cli.py
> seminars: add to sitemap generation

- backend/inspirehep/legacy/views.py
- backend/tests/integration/legacy/test_views.py
> views: redirect data record to legacy

- backend/inspirehep/records/config.py
- backend/inspirehep/search/aggregations.py
- backend/inspirehep/search/facets.py
- backend/inspirehep/serializers.py
- backend/tests/integration/search/test_aggregations.py
- backend/tests/integration/search/test_facets.py
- ui/src/authors/containers/AuthorCitationsContainer.jsx
- ui/src/authors/containers/DetailPageContainer/DetailPage.scss
- ui/src/authors/containers/DetailPageContainer/DetailPageContainer.jsx
- ui/src/authors/containers/DetailPageContainer/index.js
- ui/src/authors/containers/__tests__/AuthorCitationsContainer.test.jsx
- ui/src/common/components/NewFeatureTag/NewFeatureTag.jsx
- ui/src/common/components/NewFeatureTag/NewFeatureTag.scss
- ui/src/common/components/NewFeatureTag/index.js
- ui/src/common/components/__tests__/NewFeatureTag.test.jsx
- ui/src/common/components/__tests__/__snapshots__/NewFeatureTag.test.jsx.snap
- ui/src/common/layouts/CollectionsMenu/CollectionLink.jsx
- ui/src/common/layouts/CollectionsMenu/CollectionLink.scss
- ui/src/common/layouts/CollectionsMenu/__tests__/__snapshots__/CollectionLink.test.jsx.snap
- ui/src/literature/containers/LiteratureSearchContainer.jsx
- ui/src/reducers/search.js
* INSPIR-3430
Also modified the title of the date facet to Papers per year everywhere except in literature search (and in this new tab) after discussing with Stella.
Added the `New` feature tag to the new tab.
> refersto: refersto tab in author profile

- ui/src/common/components/ListWithPagination.jsx
- ui/src/common/components/__tests__/ListWithPagination.test.jsx
- ui/src/common/components/__tests__/__snapshots__/ListWithPagination.test.jsx.snap
- ui/src/literature/components/ReferenceList.jsx
- ui/src/literature/components/__tests__/ReferenceList.test.jsx
- ui/src/literature/components/__tests__/__snapshots__/ReferenceList.test.jsx.snap
> ui: add option to see more references

- backend/inspirehep/records/api/base.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration-async/editor/test_editor_api.py
- backend/tests/integration-async/records/api/test_base.py
> records: fix revisions revert

- ui/src/actions/search.js
- ui/src/middlewares/__tests__/syncLocationWithSearch.test.js
- ui/src/middlewares/syncLocationWithSearch.js
- ui/src/search/helper.js
- ui/src/search/queryChange.js
- ui/ui-tests/__api_recordings__/JobSearch_1831385184/recording.har
Also fixes going back issue when a search link is clicked
> ui: simplify onQueryChange callbacks

- backend/inspirehep/config.py
- backend/inspirehep/records/config.py
- backend/inspirehep/records/links.py
- backend/inspirehep/search/api.py
- backend/inspirehep/search/config.py
- backend/inspirehep/search/errors.py
- backend/inspirehep/serializers.py
- backend/tests/integration/records/api/test_api_authors.py
- backend/tests/integration/records/api/test_api_literature.py
- backend/tests/integration/records/serializers/json/test_authors.py
- backend/tests/integration/records/serializers/json/test_conferences.py
- backend/tests/integration/records/serializers/json/test_data.py
- backend/tests/integration/records/serializers/json/test_experiments.py
- backend/tests/integration/records/serializers/json/test_institutions.py
- backend/tests/integration/records/serializers/json/test_jobs.py
- backend/tests/integration/records/serializers/json/test_journals.py
- backend/tests/integration/records/serializers/json/test_literature.py
- backend/tests/integration/records/serializers/json/test_seminars.py
- backend/tests/integration/records/serializers/test_bibtex.py
- backend/tests/integration/records/serializers/test_latex.py
- backend/tests/integration/records/test_links.py
- backend/tests/integration/search/test_api.py
> api: add public rest apis

- ui/src/authors/containers/DetailPageContainer/DetailPageContainer.jsx
- ui/src/reducers/__tests__/search.test.js
- ui/src/reducers/search.js
- ui/src/search/state.js
> ui: set initial total for publication and citations tab

- ui/package.json
- ui/src/seminars/components/ExportToCalendarAction/__tests__/__snapshots__/ics.test.js.snap
- ui/src/seminars/components/ExportToCalendarAction/__tests__/ics.test.js
- ui/src/seminars/components/ExportToCalendarAction/ics.js
- ui/yarn.lock
`ics` package introduces lots of dependencies that are not relevent to our use case
> ui: add minimal ics utility to replace `ics` package

- backend/poetry.lock
- backend/tests/integration/indexer/test_indexer_experiments/1108541.json
- backend/tests/integration/records/serializers/json/test_experiments/1108739.json
* INSPIR-3603
* requires remigration
> setup: bump inspire-schemas and inspire-dojson

- backend/inspirehep/migrator/tasks.py
> migration: retry on celery ResponseError

- backend/inspirehep/indexer/tasks.py
- backend/inspirehep/records/api/authors.py
- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/api/mixins.py
- backend/tests/integration-async/conftest.py
- backend/tests/integration-async/records/indexer/test_authors.py
- backend/tests/integration-async/records/indexer/test_literature.py
> indexer: reindex records which are citing record with changed BAI

- backend/inspirehep/search/facets.py
- backend/tests/integration/search/test_facets.py
> facets: add new aggregations to institutions detail page

- backend/inspirehep/search/api.py
- backend/tests/integration/search/test_api.py
> search: allow author search to perform query string query

- ui/src/experiments/components/ExperimentItem.jsx
- ui/src/experiments/components/__tests__/__snapshots__/ExperimentItem.test.jsx.snap
> ui: fix display of papers number in experiments

- ui/src/literature/components/LiteratureItem.jsx
- ui/src/literature/components/__tests__/__snapshots__/LiteratureItem.test.jsx.snap
- ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx
- ui/src/literature/utils.js
> ui: fix link to citing literature

- ui/src/common/components/UserFeedback/UserFeedback.scss
- ui/src/submissions/conferences/components/ExistingConferencesDrawer.scss
> ui: fix existing conferences drawer visibility issue

- backend/inspirehep/search/mappings/v7/records/journals.json
- backend/tests/integration/search/cassettes/test_return_record_for_publication_info_search_with_journal_title_without_dots.yaml
- backend/tests/integration/search/test_api.py
> journals: fix lowercase_journal_titles type

- backend/inspirehep/migrator/tasks.py
- backend/inspirehep/migrator/utils.py
- backend/inspirehep/migrator/views.py
- backend/tests/integration/migrator/test_migrator_view.py
> migrator: don't show blacklisted recs in dashboard

- backend/inspirehep/records/marshmallow/literature/bibtex.py
- backend/inspirehep/records/marshmallow/literature/ui.py
- backend/inspirehep/records/marshmallow/literature/utils.py
- backend/tests/integration/records/serializers/json/test_literature.py
- backend/tests/integration/records/test_utils.py
- backend/tests/unit/records/marshmallow/literature/test_bibtex_schema.py
- ui/src/literature/components/BookSeriesInfoList.jsx
- ui/src/literature/components/ParentRecordLink.jsx
- ui/src/literature/components/__tests__/BookSeriesInfoList.test.jsx
- ui/src/literature/components/__tests__/ParentRecordLink.test.jsx
- ui/src/literature/components/__tests__/__snapshots__/BookSeriesInfoList.test.jsx.snap
- ui/src/literature/components/__tests__/__snapshots__/ParentRecordLink.test.jsx.snap
- ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx
> literature: improve display of books

- backend/inspirehep/matcher/config.py
- backend/inspirehep/matcher/parsers.py
- backend/tests/integration/matcher/test_api.py
- backend/tests/integration/search/cassettes/test_return_record_for_publication_info_search_with_multiple_records_with_the_same_journal_title.yaml
- backend/tests/integration/search/test_api.py
- backend/tests/unit/matcher/test_parsers.py
* Improves `page_start` when reference has only one page.
* Fixes wrong config.
> matcher: improve parser

- backend/inspirehep/tools/errors.py
- backend/inspirehep/tools/utils.py
- backend/inspirehep/tools/views.py
- backend/tests/integration/tools/test_views.py
> bibgen: rewrite texkeys and handle 0 refs case

- backend/inspirehep/records/api/literature.py
> files: remove exception log for duplicate files

- ui/Dockerfile
This will allow us to use env variables in the configuration file templates
> Bump nginx to 1.19.

- backend/inspirehep/tools/utils.py
- backend/tests/integration/tools/test_views.py
- ui/src/bibliographyGenerator/BibliographyGenerator.jsx
- ui/src/bibliographyGenerator/__tests__/__snapshots__/BibliographyGenerator.test.jsx.snap
> bibliography generator: simplify docs & fix journal key bug

- ui/src/conferences/__tests__/__snapshots__/index.test.jsx.snap
- ui/src/conferences/__tests__/index.test.jsx
- ui/src/experiments/__tests__/__snapshots__/index.test.jsx.snap
- ui/src/experiments/__tests__/index.test.jsx
- ui/src/fixtures/store.js
- ui/src/institutions/__tests__/__snapshots__/index.test.jsx.snap
- ui/src/institutions/__tests__/index.test.jsx
- ui/src/seminars/__tests__/__snapshots__/index.test.jsx.snap
- ui/src/seminars/__tests__/index.test.jsx
> ui: add missing tests for sub-collections routes

- backend/tests/integration/records/test_utils.py
Quick fix for flaky integration test
> tests: fix flaky integration test

- ui/src/common/layouts/Header/HeaderMenu.jsx
- ui/src/common/layouts/Header/__tests__/__snapshots__/HeaderMenu.test.jsx.snap
Note: this issue is fixed on antd@v4.4.0, this is just a workaround to fix this quickly
by avoiding version upgrades of several packages.
INSPIR-3632
> ui: fix header menu theme style for small screens

- ui/src/common/components/CitationSummaryGraph/CitationSummaryGraph.jsx
- ui/src/common/components/__tests__/CitationSummaryGraph.test.jsx
- ui/src/common/constants.js
- ui/src/common/containers/CitationSummaryGraphContainer.jsx
- ui/src/common/containers/__tests__/CitationSummaryGraphContainer.test.jsx
- ui/src/literature/components/ExcludeSelfCitations.jsx
- ui/src/literature/containers/ExcludeSelfCitationsContainer.jsx
- ui/src/literature/containers/__tests__/ExcludeSelfCitationsContainer.test.jsx
> ui: fix citation range search when self excluded

- ui/src/literature/components/BookSeriesInfoList.jsx
- ui/src/literature/components/__tests__/__snapshots__/BookSeriesInfoList.test.jsx.snap
> literature: improve display of book series

- ui/src/common/utils.js
- ui/src/literature/components/CiteAllAction.jsx
- ui/src/literature/components/CiteModalAction.jsx
- ui/src/literature/components/__tests__/CiteAllAction.test.jsx
- ui/src/literature/components/__tests__/CiteModalAction.test.jsx
- ui/src/literature/constants.js
- ui/src/seminars/components/ExportToCalendarAction/ExportToCalendarAction.jsx
> ui: set proper mimetype and extension for cite

- backend/inspirehep/assign/__init__.py
- backend/inspirehep/assign/views.py
- backend/setup.py
- backend/tests/integration/assign/test_views.py
> assign: add initial API

- backend/inspirehep/accounts/api.py
- backend/inspirehep/records/config.py
- backend/inspirehep/records/marshmallow/jobs/base.py
- backend/inspirehep/records/marshmallow/jobs/ui.py
- backend/inspirehep/records/serializers/__init__.py
- backend/inspirehep/records/serializers/json/__init__.py
- backend/inspirehep/records/serializers/json/jobs.py
- backend/tests/integration/indexer/test_indexer_jobs.py
- backend/tests/integration/records/api/test_api_jobs.py
- backend/tests/integration/records/serializers/json/test_jobs.py
- backend/tests/integration/records/serializers/json/test_jobs/955427.json
- backend/tests/integration/records/views/test_views_jobs.py
> jobs: check if user can edit job with orcid

- backend/inspirehep/assign/views.py
- backend/tests/integration/assign/test_views.py
> assign: update stub author name and return id

- backend/inspirehep/matcher/api.py
- backend/inspirehep/matcher/config.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/matcher/test_api.py
> pubnote search: enable search for journal_title without letter

- backend/inspirehep/records/marshmallow/literature/ui.py
- backend/poetry.lock
- backend/tests/integration/records/serializers/json/test_literature.py
- backend/tests/unit/records/marshmallow/literature/test_ui.py
- ui/src/literature/components/LiteratureDocumentHead.jsx
- ui/src/literature/components/__tests__/LiteratureDocumentHead.test.jsx
> serializer: add new field citation_pdf_urls which will contain only local documents

- backend/inspirehep/search/aggregations.py
- backend/inspirehep/search/facets.py
- backend/tests/integration/records/views/test_views_authors.py
- backend/tests/integration/search/test_aggregations.py
- backend/tests/integration/search/test_facets.py
> facets: add facet for claimed papers

- backend/poetry.lock
ref: inspirehep/inspire-json-merger#81
> backend: update inspire-json-merger

- backend/inspirehep/search/facets.py
- backend/tests/integration/search/test_facets.py
Ref: #1052
* fix filtering for claimed and unclaimed papers
> facets: add facet for authors curated relation

- backend/inspirehep/search/mappings/v7/records/hep.json
- backend/poetry.lock
> mappings: support nested queries for _updated and _created fields

- backend/data/records/experiment/1108541.json
- backend/inspirehep/records/config.py
- backend/inspirehep/search/aggregations.py
- backend/inspirehep/search/facets.py
- backend/inspirehep/search/mappings/v7/records/experiments.json
- backend/tests/integration/search/test_aggregations.py
- backend/tests/integration/search/test_facets.py
- ui/package.json
- ui/src/common/components/AggregationFilter.jsx
- ui/src/common/components/AggregationFilters.jsx
- ui/src/common/components/TreeAggregation.jsx
- ui/src/common/components/__tests__/AggregationFilter.test.jsx
- ui/src/common/components/__tests__/TreeAggregation.test.jsx
- ui/src/common/components/__tests__/__snapshots__/AggregationFilter.test.jsx.snap
- ui/src/common/components/__tests__/__snapshots__/TreeAggregation.test.jsx.snap
- ui/src/experiments/components/ExperimentCollaboration.jsx
- ui/src/experiments/components/ExperimentItem.jsx
- ui/src/experiments/components/__tests__/__snapshots__/ExperimentItem.test.jsx.snap
- ui/src/experiments/containers/SearchPageContainer.jsx
- ui/src/search/config.js
- ui/src/search/queryChange.js
- ui/yarn.lock
> facets: tree classification facet for experiments

- backend/inspirehep/accounts/api.py
- backend/inspirehep/records/marshmallow/base.py
- backend/tests/integration/indexer/test_indexer_conferences.py
- backend/tests/integration/indexer/test_indexer_institutions.py
- backend/tests/integration/indexer/test_indexer_seminars.py
- backend/tests/integration/records/api/test_api_base.py
- backend/tests/integration/records/api/test_api_base/788797.json
- backend/tests/integration/records/serializers/json/test_seminars.py
> serializers: do not serialize on original object as serializers modify them

- backend/inspirehep/records/config.py
- backend/inspirehep/search/api.py
- backend/tests/integration/search/test_api.py
* ref #1136
* Note: we will still not have facets for pub note searches
> search: facets search should not trigger reference match

- backend/inspirehep/records/config.py
- backend/inspirehep/search/aggregations.py
- backend/inspirehep/search/facets.py
- backend/tests/integration/search/test_aggregations.py
- backend/tests/integration/search/test_facets.py
> experiments: add institution facet

- backend/inspirehep/search/aggregations.py
> experiments: increase classification aggs size

- backend/inspirehep/submissions/views.py
- backend/tests/integration/submissions/test_submissions_views.py
> jobs: allow jobs to be edited within 30 days after deadline

- backend/poetry.lock
> poetry: Update inspire-json-merger to 11.0.6

- backend/inspirehep/indexer/cli.py
- backend/tests/integration/indexer/test_cli.py
> indexer cli: delete indexes with given prefix

- backend/inspirehep/matcher/api.py
- backend/inspirehep/search/api.py
- backend/tests/integration/matcher/test_api.py
* #Ref:1056
* search for pubnotes where journal_name is with journal volume returns now up to 5 results
> pubnote search: journal_name together with journal volume

- backend/inspirehep/editor/views.py
- backend/inspirehep/rt/tickets.py
- backend/tests/integration/editor/test_editor_views.py
- backend/tests/integration/records/serializers/json/test_literature.py
> editor views: move endpoints for rt tickets from next

- ui/src/common/layouts/CollectionsMenu/CollectionsMenu.jsx
- ui/src/common/layouts/CollectionsMenu/CollectionsMenu.scss
- ui/src/common/layouts/CollectionsMenu/__tests__/__snapshots__/CollecitionsMenu.test.jsx.snap
> collections menu: change more dropdown spacing

- backend/inspirehep/pidstore/api/literature.py
- backend/inspirehep/pidstore/errors.py
- backend/inspirehep/pidstore/minters/texkey.py
- backend/inspirehep/pidstore/providers/texkey.py
- backend/tests/integration/pidstore/minters/test_minters_cnum.py
- backend/tests/integration/pidstore/minters/test_minters_texkey.py
- backend/tests/unit/pidstore/test_providers/test_texkey_provider.py
* add texkey minter and provider
ref: #1152
> pidstore: add texkey

- backend/inspirehep/sitemap/collections.py
- backend/tests/integration/sitemap/test_cli.py
> sitemap: add experiments and institutions to sitemap

- backend/poetry.lock
This should have been part of inspirehep/inspirehep#1132, but seems to have been forgotten for some reason.
> poetry: update inspire-schemas to v61.3.7

- backend/inspirehep/records/config.py
- smoke-tests/cypress/integration/literatureRelations.test.js
* Adds waits for literatureRelation tests
* Adds sort options for author search to enfornce deterministic order
> cypress: fix flaky tests

- ui/public/config.js
- ui/src/authors/containers/AuthorPublicationsContainer.jsx
- ui/src/authors/containers/__tests__/AuthorPublicationsContainer.test.jsx
> Add feature flag for claims UI

- build-and-deploy.sh
We do not push them to cypress service to run them against QA
> travis: remove smoke-tests deployment

- backend/inspirehep/records/serializers/bibtex.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/records/serializers/test_bibtex.py
> bibtex: improve LaTeX encoding

- backend/inspirehep/records/marshmallow/authors/common/advisor.py
- backend/inspirehep/records/marshmallow/authors/ui.py
- backend/tests/integration/records/serializers/json/test_authors.py
- backend/tests/unit/records/marshmallow/author/test_ui.py
- ui/src/authors/components/Advisors/Advisor.jsx
- ui/src/authors/components/Advisors/__tests__/Advisor.test.jsx
- ui/src/authors/components/Advisors/__tests__/__snapshots__/Advisor.test.jsx.snap
> authors: add first_name and last_name to advisors

- backend/poetry.lock
- backend/tests/integration/search/test_views.py
> poetry: bump inspire-query-parser to v6.0.29

- backend/inspirehep/records/marshmallow/literature/latex.py
- backend/inspirehep/records/serializers/templates/latex_template.tex
- backend/tests/integration/records/serializers/test_latex.py
- backend/tests/unit/records/marshmallow/literature/test_latex_schema.py
Ref: #1270
* requires reindexing
> latex schema: add erratum

- backend/inspirehep/records/serializers/templates/latex_template.tex
- backend/tests/integration/records/serializers/test_latex.py
> latex schema: limit rendered authors to 10

- backend/tests/integration/records/serializers/test_latex.py
> latex: fix the date in latex tests

- backend/inspirehep/records/marshmallow/literature/latex.py
- backend/tests/unit/records/marshmallow/literature/test_latex_schema.py
> latex: escape underscore in dois

- backend/inspirehep/records/serializers/templates/cv_html_template.html
- backend/tests/integration/records/serializers/data/cv_search_with_more_complex_records.html
- backend/tests/integration/records/serializers/data/cv_with_author_with_multiple_affiliations.html
- backend/tests/integration/records/serializers/data/cv_with_collaboration_and_multiple_authors.html
- backend/tests/integration/records/serializers/data/cv_with_collaboration_with_suffix_and_multiple_authors.html
- backend/tests/integration/records/serializers/data/cv_with_collaborations_and_no_authors.html
- backend/tests/integration/records/serializers/data/cv_with_publication_info_with_material.html
- backend/tests/integration/records/serializers/data/cv_with_publication_info_with_only_page_start.html
- backend/tests/integration/records/serializers/data/cv_with_publication_info_with_pubinfo_freetext.html
- backend/tests/integration/records/serializers/data/cv_with_publication_info_with_publication_material.html
- backend/tests/integration/records/serializers/test_cv.py
* Fixes issues with the cv format (space for multiple affiliations for author, error for records with collaborations and no authors, space for middle dot for collaborations and authors, missing collaborations with suffixes, spaces between records in cite all)
* Ref: #1173
> cv: fixes for cv format

- backend/inspirehep/records/api/base.py
- backend/inspirehep/records/marshmallow/common/accelerator_experiment.py
- backend/tests/helpers/utils.py
- backend/tests/integration/disambiguation/test_tasks.py
- backend/tests/integration/disambiguation/test_utils.py
- backend/tests/integration/indexer/test_indexer_authors/999108_expected.json
- backend/tests/integration/indexer/test_indexer_literature/es_1630825.json
- backend/tests/integration/pidstore/minters/test_minters_control_number.py
- backend/tests/integration/records/api/test_api_data.py
- backend/tests/integration/records/api/test_api_experiments.py
- backend/tests/integration/records/api/test_api_institutions.py
- backend/tests/integration/records/api/test_api_literature.py
- backend/tests/integration/records/api/test_api_seminars.py
- backend/tests/integration/records/serializers/json/test_conferences.py
- backend/tests/integration/records/serializers/json/test_jobs.py
- backend/tests/integration/records/serializers/json/test_literature.py
- backend/tests/integration/records/views/test_views_jobs.py
- backend/tests/integration/records/views/test_views_literature.py
> records: populate self automatically

- backend/inspirehep/orcid/tasks.py
> orcid: fix RequestError reporting

- backend/inspirehep/search/api.py
- backend/inspirehep/search/errors.py
- backend/inspirehep/search/factories/search.py
- backend/tests/integration/records/serializers/json/test_literature.py
- backend/tests/integration/search/test_factories_search.py
> search: add filtering of api response

- backend/inspirehep/indexer/tasks.py
- backend/inspirehep/records/api/conferences.py
- backend/tests/integration-async/records/indexer/test_conferences.py
- ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx
> search: reindex conference papers when conference name changed

- ui/src/common/layouts/CollectionsMenu/CollectionsMenu.jsx
- ui/src/common/layouts/CollectionsMenu/CollectionsMenu.scss
- ui/src/common/layouts/CollectionsMenu/__tests__/__snapshots__/CollecitionsMenu.test.jsx.snap
- ui/src/common/layouts/Footer/Footer.jsx
- ui/src/common/layouts/Footer/Footer.scss
- ui/src/common/layouts/Footer/__tests__/__snapshots__/Footer.test.jsx.snap
> ui: remove new tag

- ui/src/reducers/user.js
> ui: version cite format preference in localStorage

- backend/inspirehep/pidstore/providers/bai.py
- backend/tests/integration/pidstore/minters/test_minters_bai.py
https://sentry.inspirebeta.net/inspire-qa/hep/issues/394680/?query=is%3Aunresolved
> provider: quick fix for re-minting minted record

- backend/inspirehep/records/marshmallow/base.py
- backend/inspirehep/records/marshmallow/literature/bibtex.py
- backend/inspirehep/records/marshmallow/literature/latex.py
- backend/tests/integration/records/serializers/json/test_literature.py
* Needs literature reindex.
* Ref #1370
> records: fix serializer mutations

- ui/src/common/components/ExternalLink.jsx
- ui/src/common/components/__tests__/__snapshots__/ExternalLink.test.jsx.snap
> ui: remove noreferrer for external links

- backend/inspirehep/records/links.py
- backend/tests/integration/records/test_links.py
- backend/tests/integration/search/test_api.py
> search: add the fields argument to the search links

- record-editor/src/app/holdingpen-editor/holdingpen-toolbar/holdingpen-toolbar.component.html
> editor: fix disabled button in certain window sizes

- backend/inspirehep/records/marshmallow/literature/bibtex.py
- backend/tests/unit/records/marshmallow/literature/test_bibtex_schema.py
> bibtex: use article for book chapter and thesis with journal_title

- backend/inspirehep/submissions/marshmallow/literature.py
- smoke-tests/cypress/integration/literature.test.js
> Submission: Save comments in literature submission
