inspirehep/inspirehep

- ui/src/common/components/RecordUpdateInfo.jsx
- ui/src/common/components/__tests__/__snapshots__/RecordUpdateInfo.test.jsx.snap
Component style is updated as light-silver (aaa) color.
Ref: #1373
> ui: update date in author profile

- backend/inspirehep/records/api/literature.py
> literature: skip crossref merge on ValidationError

- ui/src/literature/components/LiteratureDocumentHead.jsx
- ui/src/literature/components/__tests__/LiteratureDocumentHead.test.jsx
- ui/src/literature/components/__tests__/__snapshots__/LiteratureDocumentHead.test.jsx.snap
> ui: use publication year for google scholar

- backend/inspirehep/editor/views.py
- backend/tests/integration/editor/test_editor_views.py
- record-editor/src/app/core/services/common-api.service.ts
- record-editor/src/app/core/services/holdingpen-api.service.ts
- record-editor/src/app/core/services/record-api.service.ts
- record-editor/src/app/holdingpen-editor/holdingpen-editor.component.ts
- record-editor/src/app/record-editor/json-editor-wrapper/json-editor-wrapper.component.ts
- record-editor/src/app/shared/interfaces/index.ts
- record-editor/src/app/shared/interfaces/record-resource.ts
- record-editor/src/app/shared/interfaces/workflow-resource.ts
- smoke-tests/cypress/integration/conferences.test.js
- smoke-tests/cypress/integration/institutions.test.js
- ui/docker/nginx/config/local.conf
> record-editor: add and use GET endpoints that returns schema too

- ui/src/experiments/containers/DetailPageContainer.jsx
> ui: latex rendering in experiment details

- backend/inspirehep/search/facets.py
- backend/tests/integration/search/test_facets.py
> ui: author count facet in institution page

- backend/tests/helpers/utils.py
- backend/tests/integration-async/migrator/test_migrator_api.py
- backend/tests/integration-async/migrator/test_migrator_tasks.py
> integration-async: replace time.sleep calls

- record-editor/package.json
> ui: fix sticky tabs in reference tab of editor

- .circleci/config.yml
> e2e: enable js depedency cache on CI

- backend/inspirehep/editor/views.py
- backend/inspirehep/matcher/utils.py
- backend/poetry.lock
- backend/tests/integration/editor/test_editor_views.py
- backend/tests/integration/matcher/test_utils.py
- backend/tests/unit/matcher/test_utils.py
> refextract: create journal dict

- record-editor/package.json
- record-editor/yarn.lock
ng2-json-editor is upgraded to v0.25.21.
Ref: #1436
> record-editor: sticky tabs in record-editor are fixed.

- record-editor/yarn.lock
> record-editor: bump ng2-json-editor

- backend/poetry.lock
> backend: bump inspire-schemas

- ui/src/actions/recordsFactory.js
- ui/yarn.lock
Since `axios` and underlying `XMLRequest` does not support
`redirect: "manual"` as `fetch` API, we need to wait browser
to follow the redirect and act after `200`.
> ui: fix record redirects

- backend/inspirehep/records/marshmallow/utils.py
- backend/tests/unit/records/marshmallow/literature/test_base_schema.py
- ui/src/common/components/Author/__tests__/Author.test.jsx
- ui/src/common/components/Author/__tests__/__snapshots__/Author.test.jsx.snap
- ui/src/common/utils.js
> authors: fix author's name suffix display

- backend/tests/integration-async/conftest.py
- backend/tests/integration-async/oai/test_views.py
- backend/tests/integration/conftest.py
- backend/tests/integration/matcher/test_views.py
- backend/tests/integration/sitemap/test_cli.py
tests: add different index prefix
> tests: use different ES prefixes

- backend/inspirehep/disambiguation/tasks.py
- backend/inspirehep/matcher/config.py
- backend/inspirehep/matcher/validators.py
- backend/poetry.lock
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
- backend/tests/integration/matcher/test_validators.py
- backend/tests/unit/submissions/test_authors.py
Ref: #1499
* bumps inspire-matcher, inspire-utils and inspire-schemas
> disambiguation: disambiguate author on name, collaboration, affiliation

- backend/inspirehep/matcher/tasks.py
- backend/tests/integration/matcher/test_tasks.py
> matcher: dedupe references after matching

- backend/inspirehep/disambiguation/tasks.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
> disambiguation: add reference pointing to newly created author

- backend/inspirehep/matcher/utils.py
- backend/inspirehep/pidstore/api/base.py
- backend/inspirehep/records/api/base.py
- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/receivers.py
- backend/inspirehep/records/tasks.py
- backend/poetry.lock
- backend/tests/integration-async/conftest.py
- backend/tests/integration-async/editor/test_editor_api.py
- backend/tests/integration-async/records/test_tasks.py
- backend/tests/integration/editor/test_editor_views.py
- backend/tests/integration/indexer/test_indexer_seminars/1.json
- backend/tests/integration/orcid/test_orcid_utils.py
- backend/tests/integration/records/api/test_api_base.py
- backend/tests/integration/records/serializers/json/test_seminars/1.json
- backend/tests/integration/records/test_utils.py
- backend/tests/integration/submissions/test_submissions_views.py
- backend/tests/unit/submissions/test_authors.py
Ref: inspirehep/inspirehep#1504
> reference linking: update refs after record merge

- backend/inspirehep/indexer/base.py
> Remove record validation before indexing

- backend/inspirehep/records/serializers/__init__.py
- backend/inspirehep/records/serializers/cv.py
- backend/inspirehep/records/serializers/jinja.py
- backend/inspirehep/records/serializers/latex.py
> jinja: reuse environments for caching

- backend/inspirehep/alembic/318758a589d5_modify_idx_object_index_in_pidstore_pid_.py
- backend/tests/integration/alembic/test_alembic.py
Ref: #1564
* requires alembic migration
> alembic: add migration to fix idx_object in pidstore_pid table

- record-editor/src/app/core/services/holdingpen-api.service.ts
- record-editor/src/app/holdingpen-editor/holdingpen-save-button/holdingpen-save-button.component.ts
> editor: validation request added before save function

- backend/inspirehep/submissions/views.py
- backend/tests/integration/submissions/test_submissions_views.py
> author submission: don't override _private_notes

- record-editor/src/app/shared/config/conferences.config.ts
- record-editor/src/app/shared/config/hep/core.config.ts
> editor: record ref config for all collections

- backend/inspirehep/editor/authorlist_utils.py
- backend/inspirehep/editor/views.py
- backend/tests/integration/editor/test_editor_views.py
- backend/tests/unit/editor/test_authorlist_utils.py
- record-editor/src/app/shared/components/extract-actions/author-extract-actions.component.ts
> editor: move authorlist from next

- backend/inspirehep/curation/views.py
- backend/pyproject.toml
- backend/tests/integration/curation/test_curation_views.py
> curation: add keyword api

- record-editor/src/app/shared/components/author-brief/author-brief.component.html
> editor: display all author affiliations

- .github/actions/docker-start-container/action.yml
- .github/workflows/integration.yml
- ui/docker/nginx/config/local.conf
> set etc/hosts for e2e to work with proper ui nginx config

- backend/inspirehep/migrator/tasks.py
- backend/inspirehep/utils.py
- backend/tests/integration/migrator/test_migrator_tasks.py
- backend/tests/unit/test_utils.py
> migrator: size batches according to number of workers

- record-editor/src/app/shared/config/conferences.config.ts
- record-editor/src/app/shared/config/hep/core.config.ts
> editor: configuration changes

- backend/inspirehep/records/marshmallow/literature/utils.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/unit/records/marshmallow/literature/test_literature_marshmallow_utils.py
> latex: do not escape curly brackets + upgrade pylatexenc

- ui/src/authors/components/EditAuthorRecordAction.tsx
> ui: change author edit tooltip

- backend/inspirehep/orcid/utils.py
- backend/tests/integration/orcid/test_orcid_utils.py
> orcid: push also orcid from user profile if curated_relation

- record-editor/src/app/holdingpen-editor/holdingpen-save-button/holdingpen-save-button.component.ts
> record-editor: workflow_object is updated if a validation error occurs

- backend/inspirehep/disambiguation/tasks.py
- backend/inspirehep/records/api/base.py
- backend/inspirehep/records/api/data.py
- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/api/mixins.py
- backend/poetry.lock
- backend/tests/helpers/utils.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
- backend/tests/integration-async/editor/test_editor_api.py
- backend/tests/integration-async/migrator/test_migrator_tasks.py
- backend/tests/integration-async/records/api/test_base.py
- backend/tests/integration-async/records/api/test_literature.py
- backend/tests/integration/indexer/test_indexer_literature.py
- backend/tests/integration/migrator/test_migrator_tasks.py
- backend/tests/integration/records/api/test_api_literature.py
- backend/tests/integration/records/views/test_views_authors.py
**Please do not review and do not merge**
> records: fix versioning issues

- record-editor/src/app/holdingpen-editor/holdingpen-save-button/holdingpen-save-button.component.ts
- ui/docker/nginx/config/local.conf
> record-editor: error display for valid data fixed

- backend/inspirehep/search/api.py
- backend/tests/integration/search/test_api.py
> jobs search: fix search for users

- backend/inspirehep/records/api/base.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
- backend/tests/integration/migrator/test_migrator_tasks.py
- backend/tests/integration/records/api/test_api_base.py
> records api: fix pid creation for deleted legacy records

- backend/inspirehep/mailing/api/authors.py
- backend/inspirehep/mailing/config.py
- backend/inspirehep/mailing/templates/mailing/authors/orcid_push_disabled.html
- backend/inspirehep/orcid/domain_models.py
- backend/inspirehep/orcid/push_access_tokens.py
- backend/inspirehep/orcid/putcode_getter.py
- backend/inspirehep/orcid/tasks.py
- backend/inspirehep/orcid/utils.py
- backend/pyproject.toml
- backend/tests/integration/orcid/test_orcid_push_access_tokens.py
- backend/tests/integration/orcid/test_orcid_tasks_orcid_push.py
- backend/tests/integration/orcid/test_orcid_utils.py
> orcid: handle deprecated orcid accounts

- backend/inspirehep/records/marshmallow/literature/bibtex.py
- backend/tests/unit/records/marshmallow/literature/test_bibtex_schema.py
- backend/tests/unit/records/marshmallow/literature/test_latex_schema.py
> bibtex: get_best_publication_info function updated

- backend/inspirehep/disambiguation/tasks.py
- backend/inspirehep/matcher/config.py
- backend/inspirehep/matcher/validators.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
- backend/tests/integration/matcher/test_validators.py
Ref: #1735, #1765
* Fix matcher validator errors
> disambiguation: assign bai to author

- backend/inspirehep/curation/views.py
- backend/tests/integration/curation/test_curation_views.py
> keywording api: support energy ranges

- backend/inspirehep/submissions/marshmallow/literature.py
- backend/tests/integration/submissions/test_submissions_views.py
> serializer: find conference cnum when deserializing reference

- backend/inspirehep/assign/tasks.py
- backend/inspirehep/assign/views.py
- backend/inspirehep/records/api/base.py
- backend/tests/integration-async/conftest.py
- backend/tests/integration/assign/test_tasks.py
- backend/tests/integration/assign/test_views.py
- backend/tests/integration/conftest.py
- ui/src/actions/__tests__/authors.test.js
- ui/src/actions/authors.js
> backend: Bulk interface for assign conferences

- backend/inspirehep/disambiguation/tasks.py
- backend/inspirehep/matcher/validators.py
- backend/tests/integration-async/conftest.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
- backend/tests/integration/matcher/test_validators.py
> disambiguation: fix assigning bai and disambiguation of updated author

- backend/inspirehep/disambiguation/tasks.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
> diasmbiguation: fix assigning bai when new author created

- backend/poetry.lock
> poetry: update inspire-dojson to v63.1.1

- backend/inspirehep/hal/tasks.py
> backend: better error messages for halpush

- backend/inspirehep/records/marshmallow/literature/es.py
- backend/inspirehep/search/mappings/v7/records/hep.json
- backend/poetry.lock
- backend/tests/integration/indexer/test_indexer_literature/es_1630825.json
- backend/tests/integration/records/serializers/json/test_literature.py
Ref: #1634
* requires remapping and reindexing
> search: add primary arxiv category

- backend/inspirehep/hal/config.py
> hal: increase push timeout

- ui/src/actions/__tests__/literature.test.js
- ui/src/actions/literature.js
- ui/src/literature/assignNotification.jsx
> export to cds: add notifications

- backend/poetry.lock
* ref #1832.
* requires remigration of author records.
> poetry: update inspire-dojson to v63.1.2.

- backend/inspirehep/indexer/cli.py
- backend/inspirehep/orcid/domain_models.py
- backend/tests/integration-async/records/indexer/test_indexer_cli.py
- backend/tests/integration/indexer/test_cli.py
- backend/tests/integration/orcid/test_orcid_domain_models.py
> api: ensure that we are getting proper record from get_record_by_pid_value

- backend/inspirehep/records/api/base.py
- backend/tests/integration-async/records/api/test_base.py
> records api: don't allow undeleting records

- backend/poetry.lock
* related to inspirehep/inspirehep#1677.
* requires remigration of literature records.
> poetry: update inspire-dojson to v63.1.3

- ui/src/common/components/PublicNotesList/PublicNotesList.scss
> ui: misalignment of literature result box to the checkbox fixed.

- backend/inspirehep/records/config.py
- backend/inspirehep/search/aggregations.py
- backend/inspirehep/search/facets.py
- backend/tests/integration/records/views/test_views_authors.py
- backend/tests/integration/search/test_aggregations.py
- backend/tests/integration/search/test_facets.py
> facets: Add experiment facet in author profile for curators

- backend/tests/integration-async/records/indexer/test_literature.py
> tests: fix flaky test

- backend/inspirehep/indexer/api.py
- backend/inspirehep/indexer/tasks.py
- backend/inspirehep/migrator/tasks.py
- backend/tests/integration-async/migrator/test_migrator_tasks.py
> indexing: unify index_record and migrator indexing task

- ui/src/user/components/SignUpPage.jsx
- ui/src/user/components/__tests__/__snapshots__/SignUpPage.test.jsx.snap
> ui: clarify wording on signup page

- backend/inspirehep/access_control.py
- backend/inspirehep/config.py
- backend/inspirehep/search/api.py
- backend/inspirehep/search/errors.py
- backend/tests/integration/records/views/test_views_literature.py
- backend/tests/integration/search/cassettes/test_collection_search_doesnt_return_records_from_private_collections.yaml
- backend/tests/integration/search/test_api.py
> search: handle hidden records correctly

- backend/inspirehep/records/api/base.py
- backend/tests/integration-async/pidstore/minters/test_minter_cnum.py
- backend/tests/integration-async/records/api/test_base.py
- backend/tests/integration/pidstore/minters/test_minters_texkey.py
- backend/tests/integration/records/api/test_api_base.py
> records: Correctly check record undeletion and block it

- backend/tests/helpers/factories/models/user_access_token.py
- backend/tests/helpers/providers/record_provider.py
> tests: generating fake names are changed by `first_name + last_name`.

- backend/inspirehep/records/marshmallow/literature/common/author.py
> tests: fix for `control-number` issue in literature index tests.

- record-editor/src/app/shared/config/authors.config.ts
> record-editor: addition of authors config

- backend/inspirehep/records/marshmallow/base.py
- backend/tests/integration/records/serializers/json/test_authors.py
- backend/tests/integration/records/serializers/json/test_literature.py
Required for https://github.com/inspirehep/inspirehep/issues/1962
> schemas: add revision_id to records envelope

- backend/inspirehep/search/aggregations.py
> aggregations: improve curation collections

- ui/src/home/components/CollaborationLogos/CollaborationLogos.jsx
> ui: change IHEP logo link

- ui/src/authors/components/AuthorResultItem.jsx
- ui/src/authors/components/EditAuthorRecordAction.tsx
- ui/src/authors/containers/SearchPageContainer.jsx
- ui/src/common/components/EditRecordAction.tsx
- ui/src/common/components/__tests__/EditRecordAction.test.jsx
- ui/src/common/components/__tests__/__snapshots__/EditRecordAction.test.jsx.snap
- ui/src/common/routes.js
> ui: author edit for catalogers leads to editor

- record-editor/package.json
- record-editor/src/app/shared/config/authors.config.ts
- record-editor/yarn.lock
> record editor: author editor delete button

- backend/inspirehep/disambiguation/tasks.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
ref: inspirehep/inspirehep#2010
> disambiguation: handle deleted records

- backend/inspirehep/hal/api.py
- backend/inspirehep/hal/tasks.py
- backend/tests/integration-async/hal/test_hal_tasks.py
- backend/tests/integration/hal/test_hal_api.py
> hal push: don't push stale data

- record-editor/src/app/record-editor/record-toolbar/record-toolbar.component.ts
> editor: page refresh when 412 error responded

- record-editor/src/app/record-editor/record-toolbar/record-toolbar.component.ts
> record-editor: go to detail view when the record successfully saved.

- backend/inspirehep/disambiguation/tasks.py
- backend/inspirehep/pidstore/providers/bai.py
- backend/inspirehep/records/api/base.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/unit/pidstore/test_providers/test_bai_provider.py
> bai: change retry policy 

- record-editor/src/app/shared/config/authors.config.ts
> ui: autocomplete for authors in record editor 

- backend/inspirehep/matcher/api.py
- backend/inspirehep/matcher/config.py
- backend/tests/integration/matcher/test_api.py
> matcher: set report_number to lower priority

- backend/inspirehep/alembic/2d7ea622feda_add_index_to_authors_records.py
- backend/inspirehep/cli.py
- backend/inspirehep/disambiguation/cli.py
- backend/inspirehep/records/models.py
- backend/tests/integration/alembic/test_alembic.py
- backend/tests/integration/disambiguation/test_cli.py
ref: inspirehep/inspirehep#2034
> disambiguation: add cli to remove stub authors

- backend/inspirehep/assign/views.py
- backend/tests/integration/assign/test_views.py
> assign authors: don't create incorrect bai for stub authors

- backend/inspirehep/disambiguation/cli.py
- backend/tests/integration/disambiguation/test_cli.py
> disambiguation: pass app context to cli

- backend/inspirehep/search/mappings/v7/records/hep.json
- backend/tests/integration/search/test_api.py
ref: #2065
* requires remapping and reindexing
> search: fix mappings for journal volume

- backend/inspirehep/records/api/authors.py
- backend/inspirehep/records/utils.py
- backend/tests/integration/records/api/test_api_authors.py
> authors: link papers when creating new profile

- .github/workflows/integration.yml
This reverts commit 1f21f2ad87ba96311cd5e4219c3cf669cdc1a66d.
> Revert "cypress: container version is defined"

- backend/inspirehep/hal/tasks.py
- backend/inspirehep/orcid/domain_models.py
- backend/inspirehep/orcid/utils.py
- backend/inspirehep/utils.py
- backend/tests/integration/hal/test_core_sword.py
> hal: handle stale data error for record update & introduce lock system

- backend/inspirehep/records/config.py
- record-editor/src/app/shared/config/authors.config.ts
- record-editor/src/app/shared/config/commons.ts
> record-editor: add experiment autocomplete to project_membership

- backend/inspirehep/records/config.py
- backend/tests/integration/records/views/test_views_experiments.py
- backend/tests/integration/records/views/test_views_journals.py
> records: create and update permissions added

- backend/inspirehep/disambiguation/tasks.py
> bug: author disambiguation should retry for OperationalError and StaleDataError

- backend/inspirehep/assign/views.py
- backend/tests/integration/assign/test_views.py
> assign: update literature author bai when assigning author

- e2e/cypress/support/commands/visual.js
> cypress: fix flacky tests

- .github/workflows/integration.yml
> cypress: parallelization

- ui/src/authors/components/OrcidPushSetting.jsx
- ui/src/authors/components/OrcidPushSettingMessage.jsx
- ui/src/authors/components/__tests__/OrcidPushSetting.test.jsx
- ui/src/authors/components/__tests__/OrcidPushSettingMessage.test.jsx
- ui/src/authors/components/__tests__/__snapshots__/OrcidPushSetting.test.jsx.snap
- ui/src/authors/components/__tests__/__snapshots__/OrcidPushSettingMessage.test.jsx.snap
- ui/src/authors/containers/OrcidPushSettingContainer.jsx
- ui/src/authors/containers/OrcidPushSettingMessageContainer.jsx
- ui/src/authors/containers/__tests__/OrcidPushSettingContainer.test.jsx
- ui/src/authors/containers/__tests__/OrcidPushSettingMessageContainer.test.jsx
> ui: Change text for claim papers in profile

- backend/tests/integration-async/records/indexer/test_literature.py
> fix flaky integration-async tests

- backend/inspirehep/rt/tickets.py
- backend/tests/integration/rt/cassettes/test_create_ticket_with_empty_owner.yaml
- backend/tests/integration/rt/test_rt.py
> rt: exclude empty owner from payload when creating ticket

- e2e/cypress/integration/seminars.test.js
- e2e/cypress/support/commands/core.js
- e2e/cypress/support/commands/form.js
> cypress: firefox support

- backend/inspirehep/records/api/literature.py
- backend/tests/integration-async/records/api/test_literature.py
> disambigguation: don't run for author ref change

- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/utils.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
- backend/tests/integration-async/records/api/test_literature.py
> disambiguation: don't run when bai and references change

- backend/inspirehep/cli.py
- backend/inspirehep/hepdata/cli.py
- backend/tests/integration/hepdata/__init__.py
- backend/tests/integration/hepdata/cassettes/test_hepdata_harvest_happy_flow.yaml
- backend/tests/integration/hepdata/cassettes/test_hepdata_harvest_happy_flow_with_date_passed.yaml
- backend/tests/integration/hepdata/test_cli.py
> backend: hepdata harvest

- backend/inspirehep/records/api/base.py
> base api: batch query get_records_by_pids

- backend/inspirehep/alembic/232af38d2604_add_students_advisors_table.py
- backend/inspirehep/indexer/api.py
- backend/inspirehep/records/api/authors.py
- backend/inspirehep/records/api/mixins.py
- backend/inspirehep/records/marshmallow/authors/base.py
- backend/inspirehep/records/marshmallow/authors/es.py
- backend/inspirehep/records/marshmallow/authors/ui.py
- backend/inspirehep/records/models.py
- backend/inspirehep/search/mappings/v7/records/authors.json
- backend/tests/integration-async/records/api/test_authors.py
- backend/tests/integration-async/records/api/test_literature.py
- backend/tests/integration-async/records/indexer/test_authors.py
- backend/tests/integration/alembic/test_alembic.py
- backend/tests/integration/indexer/test_indexer_authors.py
- backend/tests/integration/indexer/test_indexer_authors/999108.json
- backend/tests/integration/indexer/test_indexer_authors/999108_expected.json
- backend/tests/integration/orcid/test_orcid_utils.py
- backend/tests/integration/orcid/test_orcid_utils/1061000.json
- backend/tests/integration/records/api/test_api_mixins.py
- backend/tests/integration/records/serializers/json/test_authors.py
- backend/tests/unit/records/marshmallow/author/test_ui.py
> authors: add student-advisor relationship

- record-editor/src/app/shared/components/extract-actions/author-extract-actions.component.ts
- record-editor/src/app/shared/components/extract-actions/ref-extract-actions.component.ts
> record-editor: authorlist tool

- backend/inspirehep/records/marshmallow/literature/bibtex.py
- backend/inspirehep/records/serializers/bibtex.py
- backend/tests/unit/records/marshmallow/literature/test_bibtex_schema.py
> bug: no pages in bibtex for book chapters

- backend/inspirehep/disambiguation/tasks.py
> disambiguation: correctly retry for duplicate PIDs

- backend/inspirehep/assign/views.py
- backend/inspirehep/records/api/authors.py
- backend/tests/integration/assign/test_views.py
> assign: fix assigning papers to new author

- backend/inspirehep/search/mappings/v7/records/hep.json
> records: addition of affiliations_identifiers

- e2e/cypress/integration/literature.test.js
- ui/src/literature/components/LiteratureItem.jsx
- ui/src/literature/containers/LiteratureSearchContainer.jsx
> ui: numbers are missing from the list view

- backend/inspirehep/records/api/base.py
- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/tasks.py
- backend/tests/integration-async/records/api/test_literature.py
- backend/tests/integration/records/api/test_api_base.py
> literature: add task to fix invalid entries in RecordsAuthors table

- backend/inspirehep/records/api/authors.py
- backend/inspirehep/records/api/mixins.py
- backend/tests/integration/records/api/test_api_mixins.py
> students-advisors: delete entries only in one direction

- backend/inspirehep/matcher/api.py
- backend/inspirehep/search/api.py
- backend/tests/integration/matcher/test_api.py
> matcher: use relaxed title matching only with grobid

- e2e/cypress/integration/literature.test.js
- ui/src/actions/__tests__/literature.test.js
- ui/src/actions/literature.js
- ui/src/common/components/ListWithPagination.jsx
- ui/src/common/components/__tests__/__snapshots__/ListWithPagination.test.jsx.snap
- ui/src/common/containers/ReferenceListContainer.jsx
- ui/src/common/containers/__tests__/ReferenceListContainer.test.jsx
- ui/src/search/config.js
- ui/src/search/constants.js
- ui/src/search/state.js
> references: keep number of references selection for pagination in literature details

- ui/src/literature/components/ImprintInfo.jsx
- ui/src/literature/components/__tests__/ImprintInfo.test.jsx
- ui/src/literature/components/__tests__/__snapshots__/ImprintInfo.test.jsx.snap
- ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx
> ui: display imprints from books

- ui/src/middlewares/__tests__/statePersister.test.js
- ui/src/middlewares/statePersister.js
- ui/src/reducers/index.js
> ui: persist search states in local storage.

- backend/inspirehep/access_control.py
- backend/inspirehep/accounts/api.py
- backend/inspirehep/config.py
- backend/inspirehep/editor/views.py
- backend/inspirehep/records/config.py
- backend/inspirehep/records/marshmallow/common/mixins.py
- backend/inspirehep/records/marshmallow/literature/ui.py
- backend/inspirehep/search/api.py
- backend/tests/integration-async/editor/test_editor_api.py
- backend/tests/integration/records/serializers/json/test_literature.py
- backend/tests/integration/records/views/test_views_literature.py
> permissions: `read` and `read_write` permissions added for collections.

- backend/inspirehep/indexer/cli.py
- backend/tests/integration/indexer/test_cli.py
> fix flaky indexer test

- backend/inspirehep/records/config.py
- backend/inspirehep/records/marshmallow/experiments/base.py
- backend/inspirehep/records/marshmallow/experiments/es.py
- backend/inspirehep/records/marshmallow/institutions/base.py
- backend/inspirehep/records/marshmallow/institutions/es.py
- backend/inspirehep/search/mappings/v7/records/experiments.json
- backend/inspirehep/search/mappings/v7/records/institutions.json
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/indexer/test_indexer_experiments.py
- backend/tests/integration/indexer/test_indexer_institutions.py
- backend/tests/unit/records/marshmallow/experiments/test_es.py
- backend/tests/unit/records/marshmallow/institutions/test_es.py
- docker-compose.services.yml
- record-editor/src/app/shared/config/commons.ts
- record-editor/src/app/shared/config/hep/core.config.ts
* Needs remaping and reindexing
* Ref: #1230
> records: addition of `search_as_you_type` for exp and ins

- ui/src/submissions/common/schemas/constants.js
> literature submission: Add new categories

- ui/public/index.html
> opensearch: link added into index.html

- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/records/views/test_views_literature.py
- record-editor/src/app/core/services/editor-error-converter.service.ts
- record-editor/src/app/core/services/index.ts
- record-editor/src/app/core/services/workflow-error-converter.service.spec.ts
- record-editor/src/app/record-editor/json-editor-wrapper/json-editor-wrapper.component.html
- record-editor/src/app/record-editor/json-editor-wrapper/json-editor-wrapper.component.ts
- record-editor/src/app/record-editor/record-toolbar/record-toolbar.component.ts
- record-editor/src/app/shared/interfaces/index.ts
- record-editor/src/app/shared/interfaces/validation-error.ts
- record-editor/src/app/shared/interfaces/workflow-object.ts
- record-editor/src/app/shared/interfaces/workflow-validation-error.ts
> editor: return validation problems

- record-editor/package.json
- record-editor/yarn.lock
> editor: strip whitespaces

- backend/inspirehep/records/api/authors.py
- backend/inspirehep/records/api/base.py
- backend/tests/integration/records/api/test_api_base.py
> records api: batch `get_records`

- backend/inspirehep/disambiguation/tasks.py
- backend/inspirehep/matcher/config.py
- backend/poetry.lock
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
> disambiguation: change config for names matching

- ui/src/reducers/index.js
> ui: persist number of search results

- backend/inspirehep/records/config.py
- backend/tests/integration/records/serializers/json/test_literature.py
> sorting: add least recent sorting option

- backend/inspirehep/editor/views.py
- backend/tests/integration/editor/test_editor_views.py
> deduplicate references

- backend/inspirehep/matcher/utils.py
- backend/inspirehep/records/tasks.py
- backend/poetry.lock
- backend/tests/integration-async/records/test_tasks.py
> records: update references in all the records

- backend/inspirehep/legacy/views.py
- backend/tests/integration/legacy/test_views.py
- backend/tests/integration/pidstore/test_pidstore_api_base.py
- ui/src/submissions/authors/schemas/uniqueOrcid.jsx
> add redirects for orcid and arxiv

- backend/inspirehep/records/config.py
- backend/inspirehep/search/facets.py
- backend/tests/integration/search/test_facets.py
> facets: add collection facet in Institutions detail page

- backend/inspirehep/legacy/views.py
- backend/tests/integration/legacy/test_views.py
> arxiv redirect: support slashes in pid value

- backend/inspirehep/rt/templates/rt/update_author.html
- backend/inspirehep/submissions/views.py
- backend/tests/integration/submissions/test_submissions_views.py
> author submission: dont create two rt tickets

- record-editor/src/app/shared/config/hep/core.config.ts
> record editor: add preprint_date as default field

- backend/inspirehep/records/marshmallow/literature/common/author.py
- backend/inspirehep/search/mappings/v7/records/hep.json
- backend/tests/unit/records/marshmallow/literature/common/test_author.py
> mappings: remove name_suggest

- ui/src/common/constants.js
- ui/src/common/layouts/Footer/Footer.jsx
- ui/src/common/layouts/Footer/__tests__/__snapshots__/Footer.test.jsx.snap
> privacy: change privacy notice url

- backend/inspirehep/records/api/literature.py
- backend/tests/integration/records/api/test_api_literature.py
> editor: show url validation error to user

- backend/inspirehep/oai/utils.py
- backend/tests/unit/oai/test_utils.py
> exporting: add curation check

- backend/inspirehep/records/config.py
> Most recent sorting for lit

- backend/inspirehep/assign/tasks.py
- backend/inspirehep/assign/utils.py
- backend/inspirehep/records/marshmallow/literature/ui.py
- backend/tests/integration/records/serializers/json/test_literature.py
- ui/src/authors/components/PublicationsSelect.jsx
- ui/src/authors/containers/AssignAllDifferentProfileActionContainer.jsx
- ui/src/authors/containers/PublicationsSelectAllContainer.jsx
- ui/src/authors/containers/__tests__/AssignAllDifferentProfileActionContainer.test.jsx
- ui/src/authors/containers/__tests__/AuthorPublicationsContainer.test.jsx
* ui fixes - don't dispatch unclaimed when user can't claim it
> claiming: return can_claim when more authors than 10

- backend/inspirehep/records/marshmallow/authors/ui.py
- backend/tests/unit/records/marshmallow/author/test_ui.py
- ui/src/authors/components/AuthorWebsitesAction.jsx
- ui/src/authors/components/__tests__/__snapshots__/AuthorWebsitesAction.test.jsx.snap
- ui/src/submissions/authors/components/AuthorForm.jsx
> ui: add links to external author websites

- backend/inspirehep/records/config.py
- backend/inspirehep/records/marshmallow/experiments/es.py
- backend/inspirehep/search/aggregations.py
- backend/inspirehep/search/mappings/v7/records/experiments.json
- backend/tests/integration/indexer/test_indexer_experiments.py
- backend/tests/integration/records/serializers/json/test_experiments.py
- backend/tests/integration/search/test_aggregations.py
- backend/tests/integration/search/test_facets.py
> Rename experiment facets

- backend/poetry.lock
> Bump inspire-query-parser

- backend/poetry.lock
> Bump query parser

- backend/poetry.lock
> Update inspire-query-parser to 6.0.46

- backend/poetry.lock
- backend/tests/integration/records/api/test_api_literature.py
> Bump inspire-schemas 61.4.11 update test

- ui/src/actions/__tests__/search.test.js
- ui/src/actions/search.js
- ui/src/search/config.js
> fix for redirection error of embedded search

- ui/src/search/config.js
* changed collection to curation_collection on literature's persistedQueryParamsDuringNewSearch
* ref: #1945
> ui: curation collection facet

- ui/src/literature/components/LiteratureCollectionBanner.jsx
- ui/src/literature/components/__tests__/__snapshots__/HiddenCollectionAlert.test.jsx.snap
> Add a space to banner text

- ui/src/literature/components/LiteratureCollectionBanner.jsx
- ui/src/literature/components/__tests__/__snapshots__/HiddenCollectionAlert.test.jsx.snap
> Link hidden collection banner to correct FAQ entry

- backend/inspirehep/records/marshmallow/experiments/ui.py
- backend/inspirehep/records/marshmallow/fields/__init__.py
- backend/inspirehep/records/marshmallow/fields/nested_without_empty_objects.py
- backend/inspirehep/records/marshmallow/institutions/ui.py
- backend/inspirehep/records/marshmallow/literature/authors.py
- backend/inspirehep/records/marshmallow/literature/common/citation_item.py
- backend/inspirehep/records/marshmallow/literature/common/reference_item.py
- backend/inspirehep/records/marshmallow/literature/cv.py
- backend/inspirehep/records/marshmallow/literature/references.py
- backend/tests/unit/records/marshmallow/fields/test_nested_without_empty_objects.py
> improve deserialisation response time

- .github/workflows/integration.yml
> add gh action for linting

- backend/inspirehep/search/mappings/v7/records/hep.json
- backend/tests/integration/search/test_api.py
ref: cern-sis/issues-inspire#9
* requires remapping & reindexing
> lit search: journal title case insensitive

- ui/src/authors/components/__tests__/__snapshots__/PublicationsSelect.test.jsx.snap
- ui/src/authors/containers/__tests__/__snapshots__/PublicationSelectContainer.test.jsx.snap
* two snapshots were obsolete and breaking the tests in github, created new snapshots
> ui tests: fix for the obsolete snapshot

- backend/inspirehep/disambiguation/tasks.py
- backend/inspirehep/disambiguation/utils.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
- backend/tests/unit/disambiguation/test_utils.py
> disambiguation: reorder names

- backend/inspirehep/matcher/utils.py
- backend/tests/integration/matcher/test_utils.py
> journals: dont query deleted journals for journal dict

- backend/inspirehep/submissions/loaders.py
- backend/inspirehep/submissions/marshmallow/__init__.py
- backend/inspirehep/submissions/marshmallow/experiments.py
- backend/inspirehep/submissions/serializers.py
- backend/inspirehep/submissions/views.py
- backend/tests/integration/submissions/test_submissions_views.py
Ref: https://github.com/cern-sis/issues-inspire/issues/18
> experiments_submissions_backend

- backend/poetry.lock
Ref: https://github.com/inspirehep/inspirehep/issues/2437
> update inspire-query-parser for fulltext

- backend/inspirehep/submissions/loaders.py
- backend/inspirehep/submissions/marshmallow/__init__.py
- backend/inspirehep/submissions/marshmallow/institutions.py
- backend/inspirehep/submissions/serializers.py
- backend/inspirehep/submissions/views.py
- backend/tests/integration/submissions/test_submissions_views.py
Ref: https://github.com/cern-sis/issues-inspire/issues/17
> Institutions submission backend

- ui/package.json
- ui/src/common/storage.js
- ui/src/setupTests.js
- ui/src/tracker.js
- ui/yarn.lock
* Use localForage instead of localStorage in the app
* ref: #1359
changed dealing with async value
> ui: local forage implementation

- ui/src/common/layouts/Header/HeaderMenu.jsx
- ui/src/common/layouts/Header/HeaderMenuContainer.jsx
- ui/src/common/routes.js
- ui/src/submissions/__tests__/__snapshots__/index.test.jsx.snap
- ui/src/submissions/index.jsx
- ui/src/submissions/institutions/components/InstitutionForm.jsx
- ui/src/submissions/institutions/components/InstitutionSubmission.jsx
- ui/src/submissions/institutions/components/__tests__/InstitutionForm.test.jsx
- ui/src/submissions/institutions/components/__tests__/__snapshots__/InstitutionForm.test.jsx.snap
- ui/src/submissions/institutions/containers/InstitutionSubmissionPageContainer.jsx
- ui/src/submissions/institutions/containers/InstitutionSubmissionSuccessPageContainer.jsx
- ui/src/submissions/institutions/containers/__tests__/InstitutionSubmissionPageContainer.test.jsx
- ui/src/submissions/institutions/containers/__tests__/InstitutionSubmissionSucessPage.test.jsx
- ui/src/submissions/institutions/containers/__tests__/__snapshots__/InstitutionSubmissionPageContainer.test.jsx.snap
- ui/src/submissions/institutions/containers/__tests__/__snapshots__/InstitutionSubmissionSucessPage.test.jsx.snap
- ui/src/submissions/institutions/schemas/__tests__/institution.test.js
- ui/src/submissions/institutions/schemas/institution.js
* added institution submission  to submissions section (for curators only)
* ref: cern-sis/issues-inspire#7
> ui: institution submission

- ui/src/common/layouts/Header/HeaderMenu.jsx
- ui/src/common/routes.js
- ui/src/submissions/__tests__/__snapshots__/index.test.jsx.snap
- ui/src/submissions/experiments/components/ExperimentForm.jsx
- ui/src/submissions/experiments/components/ExperimentSubmission.jsx
- ui/src/submissions/experiments/components/__tests__/ExperimentForm.test.jsx
- ui/src/submissions/experiments/components/__tests__/__snapshots__/ExperimentForm.test.jsx.snap
- ui/src/submissions/experiments/containers/ExperimentSubmissionPageContainer.jsx
- ui/src/submissions/experiments/containers/ExperimentSubmissionSuccessPageContainer.jsx
- ui/src/submissions/experiments/containers/__tests__/ExperimentSubmissionPageContainer.test.jsx
- ui/src/submissions/experiments/containers/__tests__/ExperimentSubmissionSuccessPageContainer.test.jsx
- ui/src/submissions/experiments/containers/__tests__/__snapshots__/ExperimentSubmissionPageContainer.test.jsx.snap
- ui/src/submissions/experiments/containers/__tests__/__snapshots__/ExperimentSubmissionSuccessPageContainer.test.jsx.snap
- ui/src/submissions/experiments/schemas/__tests__/experiment.test.js
- ui/src/submissions/experiments/schemas/constants.js
- ui/src/submissions/experiments/schemas/experiment.js
- ui/src/submissions/index.jsx
* added experiment submission to submissions section (for curators only)
* ref: cern-sis/issues-inspire#6
> ui: experiment submission

- backend/inspirehep/disambiguation/utils.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
- backend/tests/unit/disambiguation/test_utils.py
ref: cern-sis/issues-inspire#34
> disambiguation: improve name reordering

- ui/package.json
- ui/src/common/storage.js
- ui/src/setupTests.js
- ui/src/tracker.js
- ui/yarn.lock
This reverts commit 99ef6f8bc3c57fbc5c4d750743e18b3b85073be9.
> Revert "ui: local forage implementation"

- ui/src/authors/components/AssignAction.jsx
- ui/src/authors/components/AssignOwnProfileAction.jsx
- ui/src/authors/components/__tests__/AssignAction.test.jsx
- ui/src/authors/components/__tests__/AssignOwnProfileAction.test.jsx
- ui/src/authors/components/__tests__/__snapshots__/AssignAction.test.jsx.snap
- ui/src/authors/components/__tests__/__snapshots__/AssignOwnProfileAction.test.jsx.snap
- ui/src/authors/containers/AssignAllActionContainer.jsx
- ui/src/authors/containers/AssignAllOwnProfileActionContainer.jsx
- ui/src/authors/containers/__tests__/AssignAllActionContainer.test.jsx
- ui/src/authors/containers/__tests__/AssignAllOwnProfileActionContainer.test.jsx
* display plural entities instead of singular
* ref: cern-sis/issues-inspire#32
> ui: change wording on claim menu

- backend/poetry.lock
Ref: https://github.com/cern-sis/issues-inspire/issues/19
> upgrade inspire-schemas

- backend/inspirehep/alembic/0ae62076ae0c_add_workflow_record_sources_table.py
- backend/inspirehep/config.py
- backend/inspirehep/records/models.py
- backend/inspirehep/records/views.py
- backend/tests/integration/alembic/test_alembic.py
- backend/tests/integration/records/views/test_views.py
ref: cern-sis/issues-inspire#3
> root table: create api on hep

- backend/inspirehep/disambiguation/tasks.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
Ref: https://github.com/cern-sis/issues-inspire/issues/21
> handle gracefully records with no authors in disambiguation

- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/errors.py
- backend/inspirehep/records/views.py
- backend/tests/integration/records/views/test_views_article.py
Ref: https://github.com/orgs/cern-sis/projects/1/views/6
> handle Crossref gateway timeouts on import

- backend/inspirehep/assign/views.py
- backend/tests/integration/assign/test_views.py
- backend/tests/integration/records/views/test_views.py
- ui/src/actions/__tests__/authors.test.js
- ui/src/actions/authors.js
ref: cern-sis/issues-inspire#31
> assign: if author is stub treat papers as unclaimed

- backend/inspirehep/indexer/base.py
- backend/inspirehep/indexer/tasks.py
- backend/tests/integration-async/records/indexer/cassettes/test_fulltext_indexer_removes_deleted_from_es.yaml
- backend/tests/integration-async/records/indexer/test_fulltext.py
> fulltext indexer: handle deleted records

- backend/inspirehep/disambiguation/cli.py
- backend/inspirehep/disambiguation/tasks.py
- backend/tests/integration-async/conftest.py
- backend/tests/integration-async/disambiguation/test_disambiguation_cli.py
ref: cern-sis/issues-inspire#66
> disambiguation cli: run in disambiguation queue and add countdown

- ui/.gitignore
- ui/src/actions/__tests__/authors.test.js
- ui/src/actions/authors.js
- ui/src/authors/assignNotification.jsx
- ui/src/authors/components/PublicationsSelect.jsx
- ui/src/literature/containers/LiteratureSearchContainer.jsx
* ref: cern-sis/issues-inspire#44
> ui: display count of claimed papers on notification toast

- backend/inspirehep/records/marshmallow/literature/latex.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/records/serializers/test_latex.py
Ref: https://github.com/cern-sis/issues-inspire/issues/53
> Fix: Ed is stripped in LaTeX formats

- backend/inspirehep/editor/authorlist_utils.py
- backend/tests/unit/editor/test_authorlist_utils.py
Ref: https://github.com/cern-sis/issues-inspire/issues/47
> extract orcid and emails with author list extraction tool

- backend/inspirehep/assign/tasks.py
- backend/tests/integration/assign/test_views.py
Ref: https://github.com/cern-sis/issues-inspire/issues/70
> bug fix missing name in claiming rt ticket

- backend/inspirehep/records/config.py
- backend/inspirehep/tools/utils.py
- backend/tests/integration/records/api/test_api_literature.py
- backend/tests/integration/records/serializers/json/test_literature.py
- backend/tests/integration/records/serializers/test_cv.py
- backend/tests/integration/search/test_api.py
- backend/tests/integration/tools/test_views.py
Ref: https://github.com/cern-sis/issues-inspire/issues/38
> add format for CV HTML to API

- backend/inspirehep/editor/views.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/editor/test_editor_views.py
ref: cern-sis/issues-inspire#48
> editor: add normalization to authorlist

- backend/inspirehep/records/marshmallow/literature/latex.py
- backend/inspirehep/records/serializers/templates/latex_template.tex
- backend/tests/integration/records/serializers/test_latex.py
- backend/tests/unit/records/marshmallow/literature/test_latex_schema.py
Ref: https://github.com/cern-sis/issues-inspire/issues/58
> add book publication information to LaTeX formats

- record-editor/src/app/shared/components/link-references-button/link-references-button.component.ts
ref: cern-sis/issues-inspire#67
> editor: cleanup references before sending to matcher

- ui/src/institutions/containers/DetailPageContainer.jsx
* ref: cern-sis/issues-inspire#84
> ui: delete GRID link from Institution detail page

- backend/inspirehep/submissions/loaders.py
- backend/inspirehep/submissions/marshmallow/__init__.py
- backend/inspirehep/submissions/marshmallow/journals.py
- backend/inspirehep/submissions/serializers.py
- backend/inspirehep/submissions/views.py
- backend/tests/integration/submissions/test_submissions_views.py
- e2e/cypress/integration/journals.test.js
- e2e/cypress/support/commands/core.js
- e2e/cypress/support/commands/form.js
- ui/package.json
- ui/src/actions/submissions.js
- ui/src/common/constants.js
- ui/src/common/layouts/Header/HeaderMenu.jsx
- ui/src/common/routes.js
- ui/src/submissions/__tests__/__snapshots__/index.test.jsx.snap
- ui/src/submissions/index.jsx
- ui/src/submissions/journals/components/JournalForm.tsx
- ui/src/submissions/journals/components/JournalSubmission.tsx
- ui/src/submissions/journals/components/__tests__/JournalForm.test.jsx
- ui/src/submissions/journals/components/__tests__/__snapshots__/JournalForm.test.jsx.snap
- ui/src/submissions/journals/containers/JournalSubmissionPageContainer.tsx
- ui/src/submissions/journals/containers/__tests__/JournalSubmissionPageContainer.test.jsx
- ui/src/submissions/journals/containers/__tests__/__snapshots__/JournalSubmissionPageContainer.test.jsx.snap
- ui/src/submissions/journals/schemas/__tests__/journal.test.js
- ui/src/submissions/journals/schemas/journal.ts
* ui and endpoint for journal submissions
* ref: https://github.com/cern-sis/issues-inspire/issues/88
> submissions: journal submission

- backend/inspirehep/assign/utils.py
- backend/tests/integration/assign/test_views.py
ref: cern-sis/issues-inspire#100
> assign: fix name compability check when no match found

- backend/inspirehep/disambiguation/tasks.py
ref: https://github.com/cern-sis/issues-inspire/issues/78
> Retry disambiguation task for authors PIDAlreadyExistsError

- backend/inspirehep/disambiguation/tasks.py
- backend/inspirehep/records/api/authors.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
- backend/tests/integration/records/api/test_api_authors.py
ref: cern-sis/issues-inspire#97
> disambiguation: assign to stub author when ambiguous match

- backend/inspirehep/indexer/base.py
ref: cern-sis/issues-inspire#92
> indexer: log results from indexing

- ui/src/literature/components/NoAuthorsClaimingButton.tsx
- ui/src/literature/components/__tests__/NoAuthorsClaimingButton.test.jsx
- ui/src/literature/components/__tests__/__snapshots__/NoAuthorsClaimingButton.test.jsx.snap
- ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx
* ref: cern-sis/issues-inspire#107
> ui: fix for broken ui when paper doesn't have authors

- .github/workflows/integration.yml
- backend/data/records/journals/1213100.json
* added journal records to records importer
> integration: update workflow file

- backend/inspirehep/records/marshmallow/literature/common/author.py
- backend/tests/integration/records/serializers/test_cv.py
ref: cern-sis/issues-inspire#90
> cv: don't add supervisors

- backend/inspirehep/alembic/0605ca08eebd_add_primary_key_for_degree_for_.py
- backend/inspirehep/records/models.py
- backend/tests/integration-async/records/api/test_authors.py
- backend/tests/integration-async/records/indexer/test_authors.py
- backend/tests/integration/records/api/test_api_mixins.py
ref: https://github.com/cern-sis/issues-inspire/issues/79
> Student-advisor table primary key bug

- backend/inspirehep/assign/tasks.py
- backend/inspirehep/assign/views.py
- backend/tests/integration/assign/test_views.py
ref: cern-sis/issues-inspire#109
> assign: creatre rt ticket should work when some args in payload missing

- ui/src/literature/components/AssignLiteratureItemDrawer.tsx
- ui/src/literature/components/__tests__/__snapshots__/AssignLiteratureItemDrawer.test.jsx.snap
- ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx
* ref: cern-sis/issues-inspire#99
> ui: add pagination for assign literature item drawer

- .github/workflows/integration.yml
- e2e/cypress/support/commands/core.js
* ref: cern-sis/issues-inspire#85
> e2e: fix for firefox test

- backend/inspirehep/records/tasks.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration-async/records/test_tasks.py
ref: https://github.com/cern-sis/issues-inspire/issues/103
> Redirection of merged records

- ui/src/authors/assignNotification.jsx
* ref: cern-sis/issues-inspire#122
> ui: fix in claiming notification wording

- backend/inspirehep/pidstore/api/base.py
- backend/inspirehep/search/factories/query.py
- backend/inspirehep/search/mappings/v7/records/hep.json
- backend/poetry.lock
- backend/tests/integration/search/test_api.py
- backend/tests/integration/search/test_factories_query.py
ref: cern-sis/issues-inspire#102
* requires remapping & reindexing
> search: add citedby query

- backend/inspirehep/indexer/cli.py
- backend/tests/integration/indexer/test_cli.py
ref: cern-sis/issues-inspire#129
> indexer cli: handle fulltext in reindex when passing many pids

- backend/inspirehep/disambiguation/cli.py
- backend/inspirehep/disambiguation/tasks.py
- backend/inspirehep/records/api/literature.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
ref: cern-sis/issues-inspire#133
> disambiguation: check version_id in task

- ui/src/literature/components/CitationSummarySwitch.jsx
- ui/src/literature/components/__tests__/__snapshots__/CitationSummarySwitch.test.jsx.snap
* ref: cern-sis/issues-inspire#121
> ui: add label to citation summary

- ui/src/common/components/EditRecordAction.tsx
- ui/src/common/routes.js
- ui/src/experiments/containers/DetailPageContainer.jsx
* ref: cern-sis/issues-inspire#127
> ui: add missing edit button to experiment detail view

- backend/inspirehep/search/api.py
- backend/tests/integration/search/test_api.py
ref: cern-sis/issues-inspire#140
> fulltext highlight: change highlighter

- ui/src/journals/containers/DetailPageContainer.tsx
- ui/src/journals/containers/__tests__/DetailPageContainer.test.jsx
* button was available even for not logged in users, added authorisation container
* ref: cern-sis/issues-inspire#128
> ui: fix for journal edit button

- ui/src/literature/components/FulltextSnippet/FulltextSnippet.scss
- ui/src/literature/components/FulltextSnippet/FulltextSnippet.tsx
- ui/src/literature/components/FulltextSnippet/__tests__/FulltextSnippet.test.jsx
- ui/src/literature/components/FulltextSnippet/__tests__/__snapshots__/FulltextSnippet.test.jsx.snap
- ui/src/literature/components/LiteratureItem.jsx
- ui/src/literature/components/__tests__/LiteratureItem.test.jsx
- ui/src/literature/components/__tests__/__snapshots__/LiteratureItem.test.jsx.snap
* ref: cern-sis/issues-inspire#124
> ui: add fulltext snippet with highlighted search term

- .pre-commit-config.yaml
- backend/inspirehep/assign/views.py
- backend/tests/integration/assign/test_views.py
- backend/tests/integration/search/test_api.py
* ref: cern-sis/issues-inspire#144
> assign: fix claiming when user is not cataloger

- backend/inspirehep/serializers.py
> search: log es failures

- backend/inspirehep/disambiguation/cli.py
- backend/tests/integration-async/disambiguation/test_disambiguation_cli.py
> disambiguation cli: enable batches for record retrieval

- backend/inspirehep/search/aggregations.py
- backend/inspirehep/search/api.py
- backend/inspirehep/search/facets.py
- backend/tests/integration/records/views/test_views_jobs/es_aggregations_for_1735925.json
- backend/tests/integration/search/test_aggregations.py
- backend/tests/integration/search/test_api.py
- backend/tests/integration/search/test_facets.py
- ui/src/search/state.js
> jobs: users should see closed jobs

- ui/src/search/queryChange.js
* ref: cern-sis/issues-inspire#131
> ui: fix for date facet not working after location change

- ui/src/App.less
- ui/src/common/layouts/CollectionsMenu/CollectionsMenu.less
- ui/src/common/layouts/Header/HeaderMenu.less
- ui/src/submissions/literature/components/DataImporter.jsx
- ui/src/submissions/literature/components/__tests__/__snapshots__/DataImporter.test.jsx.snap
- ui/src/user/components/LoginPage/LoginPage.jsx
- ui/src/user/components/LoginPage/LoginPage.less
- ui/src/user/components/LoginPage/__tests__/__snapshots__/LoginPage.test.jsx.snap
* ref: cern-sis/issues-inspire#161, cern-sis/issues-inspire#151, cern-sis/issues-inspire#152
> ui: fixes for miscellaneous ui bugs across the app

- backend/inspirehep/records/marshmallow/literature/bibtex.py
- backend/inspirehep/records/marshmallow/literature/latex.py
- backend/tests/integration/records/serializers/test_bibtex.py
- backend/tests/integration/records/serializers/test_latex.py
ref: cern-sis/issues-inspire#147
> latex & bibtex: strip mathml

- backend/inspirehep/records/tasks.py
ref:cern-sis/issues-inspire#106
> redirect refs: increase scroll time

- README.md
- backend/inspirehep/files/cli.py
- backend/inspirehep/files/config.py
- backend/scripts/setup
- docker-compose.services.yml
- docker-compose.yml
ref:cern-sis/issues-inspire#143
> local setup: enable s3

- backend/inspirehep/logger/ext.py
> prometheus exporter: add label depending on request headers

- ui/.eslintrc
- ui/package.json
- ui/src/journals/components/JournalItem.tsx
- ui/src/journals/components/JournalPapers.tsx
- ui/src/journals/components/__tests__/JournalPapers.test.jsx
- ui/src/journals/components/__tests__/Journaltem.test.jsx
- ui/src/journals/components/__tests__/__snapshots__/JournalPapers.test.jsx.snap
- ui/src/journals/components/__tests__/__snapshots__/Journaltem.test.jsx.snap
- ui/src/journals/containers/DetailPageContainer.tsx
- ui/src/journals/containers/SearchPageContainer.tsx
- ui/src/search/state.js
- ui/yarn.lock
* ref: cern-sis/issues-inspire#71
> ui: journal embedded search view and number of papers

- ui/src/literature/components/ConferenceInfoList.jsx
- ui/src/literature/components/__tests__/__snapshots__/ConferenceInfoList.test.jsx.snap
* ref: cern-sis/issues-inspire#172
> ui: change label for proceedings

- backend/inspirehep/assign/tasks.py
- backend/inspirehep/curation/tasks.py
- backend/inspirehep/disambiguation/tasks.py
- backend/inspirehep/errors.py
- backend/inspirehep/hal/tasks.py
- backend/inspirehep/indexer/tasks.py
- backend/inspirehep/matcher/tasks.py
- backend/inspirehep/records/tasks.py
- backend/inspirehep/sitemap/tasks.py
> exceptions: refactor exceptions used for task retries

- backend/inspirehep/logger/ext.py
as in the example here 
https://github.com/rycus86/prometheus_flask_exporter/blob/fa68d4761743c6e6de58273262e5b1e935c17530/tests/test_defaults.py#L760
> update prometheus static_labels

- ui/src/literature/components/ConferenceInfoList.jsx
- ui/src/literature/components/LiteratureItem.jsx
- ui/src/literature/components/__tests__/ConferenceInfoList.test.jsx
- ui/src/literature/components/__tests__/__snapshots__/ConferenceInfoList.test.jsx.snap
- ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx
* ref: cern-sis/issues-inspire#175
> ui: change conference info label depending on document type

- ui/src/journals/components/JournalTitlesListModal.tsx
- ui/src/journals/components/__tests__/__snapshots__/JournalTitlesListModal.test.jsx.snap
- ui/src/journals/containers/DetailPageContainer.tsx
The issue was placing the modal outside DetailPageContainer <Row /> element. Moved JournalTitlesModal inside <Row />
> ui: fix for elements width inconsistency when modal is open

- backend/inspirehep/search/mappings/v7/records/journals.json
- backend/tests/integration/search/test_api.py
> journal search: add filters to `lowercase_journal_titles`

- backend/inspirehep/editor/views.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/editor/test_editor_views.py
- record-editor/src/app/core/services/common-api.service.ts
- record-editor/src/app/shared/components/file-upload-button/file-upload-button.component.ts
ref: #https://github.com/cern-sis/issues-inspire/issues/142
> Upgrade editor upload rights

- backend/tests/helpers/providers/record_provider.py
- backend/tests/helpers/utils.py
ref: cern-sis/issues-inspire#185
> fix flaky faker's control_number generation

- .github/workflows/integration.yml
> CI: split async tests

- .gitignore
- backend/Dockerfile-local
- backend/scripts/setup
- docker-compose.yml
- record-editor/Dockerfile
- record-editor/Dockerfile-local
- ui/Dockerfile-local
* Fixes docker setup and allow to run the project on M1.
> global: ARM arch changes

- backend/inspirehep/records/config.py
- backend/inspirehep/search/api.py
- backend/inspirehep/search/errors.py
- backend/inspirehep/search/factories/query.py
- backend/tests/integration/search/test_api.py
ref: cern-sis/issues-inspire#190
> records: return json response for REST errors

- backend/inspirehep/search/errors.py
- backend/inspirehep/serializers.py
- backend/tests/integration/search/test_api.py
ref: cern-sis/issues-inspire#190
> handle search serializer errors

- backend/inspirehep/matcher/api.py
- backend/tests/integration/matcher/test_api.py
- backend/tests/integration/search/test_api.py
ref: cern-sis/issues-inspire#210
> search: do not return data records when no hits from lit search

- backend/tests/integration/records/serializers/json/test_authors.py
> fix flaky test

- backend/inspirehep/records/errors.py
> exceptions: file exceptions should be rest

- backend/inspirehep/accounts/views.py
- backend/tests/integration-async/accounts/test_views.py
ref cern-sis/issues-inspire#222
> accounts: add endpoint for email change

- record-editor/src/environments/environment.prod.ts
* ref: cern-sis/issues-inspire#220
> editor: change sentry dsn key

- .github/workflows/integration.yml
> parallelize e2e tests

- ui/src/jobs/components/SubscribeJobsForm.jsx
- ui/src/submissions/authors/schemas/author.js
- ui/src/submissions/common/schemas/contacts.js
- ui/src/submissions/jobs/schemas/job.js
- ui/src/user/components/SingUpForm.tsx
- ui/src/user/components/__tests__/__snapshots__/SingUpForm.test.jsx.snap
* ref: cern-sis/issues-inspire#212
> ui: trim whitespaces in email input fields

- .github/workflows/integration.yml
ref [https://github.com/cypress-io/github-action/issues/518\#issuecomment-1210979047](https://github.com/cypress-io/github-action/issues/518#issuecomment-1210979047)
> fix parallel cypress settings

- backend/inspirehep/serializers.py
- backend/tests/integration/search/test_api.py
ref: cern-sis/issues-inspire#226
> serializers: raise search serialization error for db&es exceptions

- backend/data/records/literature/374836.json
- ui/src/literature/components/PersistentIdentifiers.tsx
- ui/src/literature/components/__tests__/PersistentIdentifiers.test.jsx
- ui/src/literature/components/__tests__/__snapshots__/PersistentIdentifiers.test.jsx.snap
- ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx
* ref: cern-sis/issues-inspire#224
> ui: display persistent identifiers

- backend/inspirehep/disambiguation/cli.py
ref: cern-sis/issues-inspire#229
> cli stub authors: commit deletes in single transactions

- .pre-commit-config.yaml
- ui/src/common/constants.ts
- ui/src/common/layouts/Footer/__tests__/__snapshots__/Footer.test.jsx.snap
* ref: cern-sis/issues-inspire#230
> ui: change RT to SNOW for metadata issues

- ui/src/index.js
* ref: cern-sis/issues-inspire#197
> ui: prevent app from crashing on ResizeObserver error

- .github/workflows/integration.yml
- backend/data/records/literature/1124337.json
- backend/data/records/literature/44707.json
- ui/src/authors/assignNotification.tsx
- ui/src/authors/components/AssignAction.tsx
- ui/src/authors/components/AssignDifferentProfileAction.tsx
- ui/src/authors/components/AssignNoProfileAction.tsx
- ui/src/authors/components/AssignOneDifferentProfileAction.tsx
- ui/src/authors/components/AssignOwnProfileAction.tsx
- ui/src/authors/components/ClaimingDisabledButton.tsx
- ui/src/authors/components/PublicationsSelectAll.tsx
- ui/src/authors/components/__tests__/__snapshots__/AssignAction.test.jsx.snap
- ui/src/authors/components/__tests__/__snapshots__/AssignDifferentProfileAction.test.jsx.snap
- ui/src/authors/components/__tests__/__snapshots__/AssignNoProfileAction.test.jsx.snap
- ui/src/authors/components/__tests__/__snapshots__/AssignOneDifferentProfileAction.test.jsx.snap
- ui/src/authors/components/__tests__/__snapshots__/AssignOwnProfileAction.test.jsx.snap
- ui/src/authors/components/__tests__/__snapshots__/ClaimingDisabledButton.test.jsx.snap
- ui/src/authors/components/__tests__/__snapshots__/PublicationsSelectAll.test.jsx.snap
- ui/src/literature/components/AssignLiteratureItem.tsx
- ui/src/literature/components/LiteratureItem.jsx
- ui/src/literature/components/NoAuthorsClaimingButton.tsx
- ui/src/literature/components/__tests__/__snapshots__/AssignLiteratureItem.test.jsx.snap
- ui/src/literature/components/__tests__/__snapshots__/LiteratureItem.test.jsx.snap
- ui/src/literature/components/__tests__/__snapshots__/NoAuthorsClaimingButton.test.jsx.snap
* ref: cern-sis/issues-inspire#156
> ui: added e2e tests for claiming - part 1

- backend/inspirehep/hal/tasks.py
- backend/inspirehep/matcher/api.py
- backend/inspirehep/orcid/domain_models.py
- backend/inspirehep/orcid/tasks.py
> tasks: handle gracefully errors

- backend/inspirehep/accounts/cli.py
- backend/inspirehep/cli.py
- backend/tests/integration/accounts/test_cli.py
ref: cern-sis/issues-inspire#233
> accounts: add cli to delete users

- record-editor/src/app/core/services/common-api.service.ts
- record-editor/src/app/shared/components/tickets/ticket/ticket.component.html
- record-editor/src/app/shared/components/tickets/ticket/ticket.component.scss
- record-editor/src/app/shared/components/tickets/ticket/ticket.component.ts
- record-editor/src/app/shared/components/tickets/tickets.component.html
- record-editor/src/app/shared/components/tickets/tickets.component.scss
- record-editor/src/app/shared/components/tickets/tickets.component.ts
- record-editor/src/app/shared/interfaces/index.ts
- record-editor/src/app/shared/interfaces/snow-ticket.ts
* ref: cern-sis/issues-inspire#241
> editor: support both SNOW and RT tickets

- ui/src/settings/components/SettingsPage.tsx
- ui/src/settings/components/__tests__/SettingsPage.test.jsx
- ui/src/settings/components/__tests__/__snapshots__/SettingsPage.test.jsx.snap
* ref: cern-sis/issues-inspire#249
> ui: disable orcid push when user has no author profile

- backend/inspirehep/disambiguation/cli.py
ref cern-sis/issues-inspire#247
> refactor stub authors cli

- backend/inspirehep/records/serializers/bibtex.py
- backend/inspirehep/records/serializers/cv.py
- backend/inspirehep/records/serializers/json/authors.py
- backend/inspirehep/records/serializers/json/conferences.py
- backend/inspirehep/records/serializers/json/experiments.py
- backend/inspirehep/records/serializers/json/institutions.py
- backend/inspirehep/records/serializers/json/jobs.py
- backend/inspirehep/records/serializers/json/journals.py
- backend/inspirehep/records/serializers/json/literature.py
- backend/inspirehep/records/serializers/json/raw.py
- backend/inspirehep/records/serializers/json/seminars.py
- backend/inspirehep/records/serializers/latex.py
- backend/inspirehep/serializers.py
- backend/tests/integration/test_serializers.py
ref: cern-sis/issues-inspire#221
> headers: dont add link header to search & record response

- .github/workflows/e2e-tests.yml
- backend/inspirehep/records/tasks.py
- backend/scripts/server
- backend/tests/integration-async/conftest.py
- docker-compose.yml
> fix `redirect_references_to_merged_record`

- backend/inspirehep/errors.py
- backend/inspirehep/records/tasks.py
- backend/inspirehep/records/utils.py
- backend/inspirehep/records/views.py
- backend/inspirehep/rt/templates/rt/self_curation.html
- backend/inspirehep/submissions/tasks.py
- backend/tests/integration-async/records/test_record_views.py
- backend/tests/integration-async/records/test_tasks.py
- backend/tests/integration/records/views/test_views.py
> self curation: add backend

- backend/tests/helpers/utils.py
- backend/tests/integration-async/assign/test_tasks.py
- backend/tests/integration-async/assign/test_views.py
- backend/tests/integration-async/curation/test_curation_cli.py
- backend/tests/integration-async/disambiguation/test_disambiguation_cli.py
- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
- backend/tests/integration-async/editor/test_editor_api.py
- backend/tests/integration-async/matcher/test_cli.py
- backend/tests/integration-async/migrator/test_migrator_api.py
- backend/tests/integration-async/migrator/test_migrator_tasks.py
- backend/tests/integration-async/oai/test_views.py
- backend/tests/integration-async/records/api/test_literature.py
- backend/tests/integration-async/records/indexer/test_authors.py
- backend/tests/integration-async/records/indexer/test_conferences.py
- backend/tests/integration-async/records/indexer/test_data.py
- backend/tests/integration-async/records/indexer/test_experiments.py
- backend/tests/integration-async/records/indexer/test_fulltext.py
- backend/tests/integration-async/records/indexer/test_institutions.py
- backend/tests/integration-async/records/indexer/test_jobs.py
- backend/tests/integration-async/records/indexer/test_journals.py
- backend/tests/integration-async/records/indexer/test_literature.py
- backend/tests/integration-async/records/indexer/test_seminars.py
- backend/tests/integration-async/records/test_fulltext.py
- backend/tests/integration-async/records/test_record_views.py
- backend/tests/integration-async/records/test_records_cli.py
- backend/tests/integration-async/records/test_tasks.py
ref: https://github.com/cern-sis/issues-inspire/issues/278
> tests: replace retry_until_pass with tenacity

- ui/src/common/components/CitationsByYearGraph/CitationsByYearGraph.tsx
- ui/src/common/components/CitationsByYearGraph/__tests__/__snapshots__/CitationsByYearGraph.test.tsx.snap
* ref: cern-sis/issues-inspire#285
> ui: fix for tooltips in citations graph

- backend/inspirehep/records/marshmallow/literature/common/__init__.py
- backend/inspirehep/records/marshmallow/literature/common/reference_item.py
- backend/inspirehep/records/utils.py
- backend/inspirehep/records/views.py
- backend/tests/integration-async/records/test_record_views.py
- backend/tests/unit/records/marshmallow/literature/common/test_reference_item.py
ref: cern-sis/issues-inspire#279
> self curation: add diff interface

- backend/inspirehep/records/cli.py
- backend/tests/integration/records/test_cli.py
removes caching to directory and uploads the xmls directly to s3
> legacy_records: optimize xml export script

- backend/inspirehep/records/cli.py
- backend/inspirehep/records/tasks.py
- backend/tests/integration-async/records/test_records_cli.py
- backend/tests/integration/records/test_cli.py
ref: https://github.com/cern-sis/issues-inspire/issues/271
> legacy_records: add xml export celery task

- backend/inspirehep/records/tasks.py
- backend/tests/integration-async/records/test_records_cli.py
ref: https://github.com/cern-sis/issues-inspire/issues/271
> legacy_records: fix bucket name for xml export

- backend/inspirehep/records/tasks.py
ref: https://github.com/cern-sis/issues-inspire/issues/271
> legacy_records: fix upload format

- backend/inspirehep/curation/api.py
- backend/inspirehep/curation/errors.py
- backend/inspirehep/curation/utils.py
- backend/inspirehep/curation/views.py
- backend/tests/integration/curation/test_api.py
- backend/tests/integration/curation/test_api/ambiguous_experiments/experiment_with_ambiguous_collaboration_1.json
- backend/tests/integration/curation/test_api/ambiguous_experiments/experiment_with_ambiguous_collaboration_2.json
- backend/tests/integration/curation/test_api/ambiguous_experiments/experiment_with_subgroup_1.json
- backend/tests/integration/curation/test_api/ambiguous_experiments/experiment_with_subgroup_2.json
- backend/tests/integration/curation/test_api/experiments/experiment_with_collaboration.json
- backend/tests/integration/curation/test_api/experiments/experiment_with_collaboration_and_subgroups.json
- backend/tests/integration/curation/test_api/experiments/experiment_without_collaboration.json
- backend/tests/integration/curation/test_curation_views.py
- backend/tests/unit/curation/test_utils.py
ref: cern-sis/issues-inspire#294
> collaboration normalization: move all functionalities from next

- ui/src/reducers/__tests__/search.test.js
- ui/src/reducers/search.js
- ui/src/search/config.js
* ref: cern-sis/issues-inspire#307
> ui: fix earliest_date facet

- ui/src/reducers/__tests__/search.test.js
- ui/src/reducers/search.js
- ui/src/search/config.js
This reverts commit cee283ca6fb5393ab32c3bb8c218fbd0da47d73f.
> Revert "ui: fix earliest_date facet"

- backend/inspirehep/search/mappings/v7/records/institutions.json
- backend/tests/integration/search/test_api.py
- docker-compose.services.yml
ref: cern-sis/issues-inspire#311
> search: update institutions mapping

- ui/src/authors/components/__tests__/AssignAction.test.jsx
- ui/src/authors/components/__tests__/AssignDifferentProfileAction.test.jsx
- ui/src/authors/components/__tests__/AssignOneDifferentProfileAction.test.jsx
- ui/src/authors/components/__tests__/AssignOwnProfileAction.test.jsx
- ui/src/literature/components/__tests__/AssignLiteratureItem.test.jsx
- ui/src/literature/components/__tests__/ToolAction.test.jsx
- ui/src/user/containers/__tests__/SignUpPageContainer.test.tsx
* ref: cern-sis/issues-inspire#313
> ui: fix flaky tests

- ui/src/actions/literature.ts
- ui/src/literature/components/CurateReferenceDrawer/CurateReferenceDrawer.tsx
- ui/src/literature/components/CurateReferenceDrawer/__tests__/CurateReferenceDrawer.test.tsx
- ui/src/literature/containers/CurateReferenceDrawerContainer.tsx
- ui/src/literature/containers/DetailPageContainer/DetailPageContainer.tsx
- ui/src/literature/containers/__tests__/CurateReferenceDrawerContainer.test.tsx
* ref: cern-sis/issues-inspire#237
> ui: fix for self curation

- backend/inspirehep/errors.py
fixes cern-sis/issues-inspire#315
> retry tasks on integrity error

- backend/inspirehep/records/tasks.py
- backend/inspirehep/records/views.py
- backend/tests/integration-async/records/test_record_views.py
- backend/tests/integration-async/records/test_tasks.py
- backend/tests/integration/records/views/test_views.py
ref: cern-sis/issues-inspire#327
> self-curation: update reference sync

- record-editor/src/app/shared/components/tickets/ticket/ticket.component.ts
* ref: cern-sis/issues-inspire#334
> editor: fix snow ticket resolve issue

- backend/inspirehep/editor/views.py
- backend/inspirehep/rt/templates/rt/curation_needed_author.html
- backend/inspirehep/rt/templates/rt/curator_new.html
- backend/inspirehep/rt/templates/rt/curator_new_author.html
- backend/inspirehep/rt/templates/rt/curator_update_author.html
- backend/inspirehep/rt/templates/rt/user_accepted_author.html
- backend/inspirehep/rt/templates/rt/user_new_author.html
- backend/inspirehep/snow/config.py
> map rt queues to functional categories

- ui/src/literature/components/ReferenceList.tsx
- ui/src/literature/components/__tests__/__snapshots__/ReferenceList.test.jsx.snap
ref: cern-sis/issues-inspire#341
> Add loader to references

- e2e/cypress/integration/literature.test.js
- e2e/cypress/integration/references.test.js
- ui/src/literature/components/CurateReferenceDrawer/CurateReferenceDrawer.tsx
- ui/src/literature/components/ReferenceDiffInterface/__tests__/__snapshots__/ReferenceDiffInterface.test.tsx.snap
- ui/src/literature/components/ReferenceItem.jsx
- ui/src/literature/components/__tests__/__snapshots__/ReferenceItem.test.jsx.snap
* ref: cern-sis/issues-inspire#312
> e2e: add tests for self curation

- README.md
- backend/inspirehep/records/config.py
* ref: cern-sis/issues-inspire#320
> records: configure experiments sorting

- e2e/cypress.config.js
- e2e/cypress/e2e/authors.test.js
- e2e/cypress/e2e/conferences.test.js
- e2e/cypress/e2e/experiments.test.js
- e2e/cypress/e2e/institutions.test.js
- e2e/cypress/e2e/jobs.test.js
- e2e/cypress/e2e/journals.test.js
- e2e/cypress/e2e/literature.test.js
- e2e/cypress/e2e/seminars.test.js
- e2e/cypress/plugins/index.js
- e2e/cypress/support/commands/core.js
- e2e/cypress/support/commands/form.js
- e2e/package.json
- e2e/yarn.lock
- ui/src/common/components/EventTitle.jsx
- ui/src/common/components/__tests__/__snapshots__/EventTitle.test.jsx.snap
- ui/src/experiments/containers/DetailPageContainer.jsx
- ui/src/institutions/containers/DetailPageContainer.jsx
- ui/src/jobs/containers/DetailPageContainer.jsx
- ui/src/journals/containers/DetailPage.less
- ui/src/journals/containers/DetailPageContainer.tsx
- ui/src/submissions/conferences/containers/ConferenceSubmissionSuccessPageContainer.jsx
- ui/src/submissions/conferences/containers/__tests__/__snapshots__/ConferenceSubmissionSuccessPageContainer.test.jsx.snap
- ui/src/submissions/jobs/components/JobUpdateSubmissionSuccessPage.jsx
- ui/src/submissions/jobs/components/__tests__/__snapshots__/JobUpdateSubmissionSuccessPage.test.jsx.snap
- ui/src/submissions/seminars/containers/SeminarSubmissionSuccessPageContainer.jsx
* ref: cern-sis/issues-inspire#363
> e2e: rewrite submission tests

- e2e/cypress/e2e/claiming.test.js
* ref: cern-sis/issues-inspire/365
> e2e: fix for claiming as author test

- ui/src/authors/assignNotification.tsx
- ui/src/common/components/ExternalLink.tsx
- ui/src/common/components/LinkWithTargetBlank.tsx
- ui/src/common/components/__tests__/__snapshots__/APIButton.test.tsx.snap
- ui/src/common/components/__tests__/__snapshots__/LinkWithTargetBlank.test.jsx.snap
- ui/src/common/layouts/Header/Banner.tsx
- ui/src/common/layouts/Header/__tests__/__snapshots__/Banner.test.jsx.snap
- ui/src/home/components/NewsAndUpdates.tsx
- ui/src/home/components/__tests__/__snapshots__/NewsAndUpdates.test.jsx.snap
- ui/src/literature/assignNotification.jsx
- ui/src/literature/components/ReferenceDiffInterface/__tests__/__snapshots__/ReferenceDiffInterface.test.tsx.snap
- ui/src/user/components/LoginPage/__tests__/__snapshots__/LoginPage.test.tsx.snap
* ref: cern-sis/issues-inspire#375
> ui: add noreferer noopener attribute to links with target blank

- ui/src/literature/assignNotification.jsx
* ref: cern-sis/issues-inspire#173
> ui: fix wrong plural form in notification

- backend/data/records/conferences/1794610.json
- ui/src/App.less
- ui/src/common/components/EventTitle.jsx
- ui/src/common/components/__tests__/EventTitle.test.jsx
- ui/src/common/components/__tests__/__snapshots__/EventTitle.test.jsx.snap
- ui/src/journals/containers/DetailPage.less
* ref: cern-sis/issues-inspire#380
> ui: fix styles in event title

- backend/inspirehep/records/config.py
- backend/inspirehep/search/facets.py
- backend/tests/integration/search/test_aggregations.py
ref: cern-sis/issues-inspire#396
> search: fix jobs field of interest filter

- backend/inspirehep/records/config.py
- backend/tests/integration/records/api/test_api_literature.py
ref: cern-sis/issues-inspire#355
> cv format: fix wrong request content type

- e2e/cypress/e2e/claiming.test.js
- ui/src/authors/components/AssignNoProfileAction.tsx
- ui/src/authors/components/EditAuthorRecordAction.tsx
- ui/src/authors/components/__tests__/__snapshots__/AssignNoProfileAction.test.jsx.snap
- ui/src/common/components/UserFeedback/UserFeedback.jsx
- ui/src/common/components/UserFeedback/__tests__/__snapshots__/UserFeedback.test.jsx.snap
- ui/src/common/constants.ts
- ui/src/common/layouts/Footer/Footer.tsx
- ui/src/common/layouts/Footer/__tests__/__snapshots__/Footer.test.jsx.snap
- ui/src/common/layouts/Header/__tests__/__snapshots__/HeaderMenu.test.jsx.snap
- ui/src/literature/assignNotification.jsx
* ref: cern-sis/issues-inspire#362
> ui: updated contact link

- backend/inspirehep/assign/tasks.py
- backend/inspirehep/rt/templates/rt/new_conference.html
- backend/inspirehep/rt/templates/rt/new_job.html
- backend/inspirehep/rt/templates/rt/update_job.html
- backend/inspirehep/submissions/views.py
- backend/tests/integration/assign/test_views.py
* queue/functional category names for SNow have been corrected
* templates are now plain text
> tickets: fix small SNow bugs

- backend/inspirehep/records/config.py
- backend/inspirehep/search/facets.py
- backend/tests/integration/search/test_aggregations.py
ref: https://github.com/cern-sis/issues-inspire/issues/407
> facets: fix jobs category facets

- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/helpers/providers/record_provider.py
- backend/tests/integration/pidstore/minters/test_minters_cnum.py
- backend/tests/integration/records/serializers/json/test_conferences.py
- backend/tests/integration/records/views/test_views_conferences.py
- docker/jupyter/hep_requirements.txt
prepares for inspire-schema version bump from https://github.com/inspirehep/inspire-schemas/pull/454
ref: https://github.com/cern-sis/issues-inspire/issues/404
> tests: adjust tests for required titles for conferences

- ui/src/authors/__tests__/utils.test.js
- ui/src/authors/components/AuthorResultItem.tsx
- ui/src/authors/components/InspireID.tsx
- ui/src/authors/components/__tests__/InspireID.test.tsx
- ui/src/authors/components/__tests__/__snapshots__/AuthorResultItem.test.jsx.snap
- ui/src/authors/containers/DetailPageContainer/DetailPageContainer.tsx
- ui/src/authors/utils.ts
- ui/src/common/components/ExperimentList.jsx
* ref: cern-sis/issues-inspire#431
> ui: add INSPIRE ID

- README.md
- ui/Dockerfile
- ui/Dockerfile-local
- ui/package.json
* ref: cern-sis/issues-inspire#369
> ui: updated node to 20

- README.md
- backend/inspirehep/snow/api.py
- backend/inspirehep/snow/views.py
- backend/tests/integration/conftest.py
- backend/tests/integration/snow/cassettes/test_reply_ticket_view_with_template.yaml
- backend/tests/integration/snow/cassettes/test_reply_ticket_with_template_view_a.yaml
- backend/tests/integration/snow/cassettes/test_reply_ticket_with_template_view_aa.yaml
- backend/tests/integration/snow/cassettes/test_resolve_ticket_with_template_view.yaml
- backend/tests/integration/snow/test_snow_views.py
Needs changes on inspire-next before merge
ref: https://github.com/cern-sis/issues-inspire/issues/415
> Refactor snow views

- ui/src/literature/components/PersistentIdentifiers.tsx
- ui/src/literature/components/__tests__/__snapshots__/PersistentIdentifiers.test.jsx.snap
* ref: cern-sis/issues-inspire/issues#435
> ui: linkify URN identifiers

- .github/workflows/e2e-tests.yml
Reverts inspirehep/inspirehep#3120
> Revert "workflow: change os to macos for e2e"

- backend/inspirehep/snow/api.py
- backend/inspirehep/snow/config.py
- backend/tests/integration/editor/cassettes/test_get_snow_tickets_for_record.yaml
- backend/tests/integration/snow/cassettes/test_create_ticket_with_template_view.yaml
- backend/tests/integration/snow/cassettes/test_get_ticket_by_recid.yaml
ref: https://github.com/cern-sis/issues-inspire/issues/421
> snow: fix disappearing snow tickets

- backend/inspirehep/records/marshmallow/literature/common/author.py
- backend/tests/unit/records/marshmallow/literature/common/test_author.py
ref: https://github.com/cern-sis/issues-inspire/issues/426
> authors: fix get id function

- ui/src/user/components/LocalLoginPage.tsx
* ref: cern-sis/issues-inspire#434
> friday improvement: fix submit on enter on local login page

- backend/inspirehep/hal/errors.py
- backend/inspirehep/hal/tasks.py
- backend/tests/integration/hal/test_core_sword.py
ref: https://github.com/cern-sis/issues-inspire/issues/403
> hal: fix exception raise on _hal_create

- .github/workflows/e2e-tests.yml
- e2e/package.json
- e2e/yarn.lock
> e2e: update cypress to fix ff issue

- e2e/cypress/e2e/references.test.js
- e2e/cypress/e2e/settings.test.js
- e2e/cypress/support/commands/form.js
- ui/src/user/components/SignUpPage.tsx
- ui/src/user/components/__tests__/__snapshots__/SignUpPage.test.tsx.snap
- ui/src/user/containers/__tests__/SignUpPageContainer.test.tsx
* ref: cern-sis/issues-inspire#464
> tests: fix flaky e2e and unit tests

- backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
- backend/tests/integration-async/records/test_tasks.py
- backend/tests/integration/matcher/test_api.py
- backend/tests/integration/records/serializers/json/test_literature.py
- backend/tests/integration/records/serializers/test_cv.py
- backend/tests/integration/records/test_utils.py
- e2e/cypress/e2e/references.test.js
* ref: cern-sis/issues-inspire#428
> backend: fix for some flaky tests

- ui/src/common/components/DocumentHead.jsx
- ui/src/common/components/__tests__/__snapshots__/DocumentHead.test.jsx.snap
- ui/src/holdingpen/index.tsx
* ref: cern-sis/issues-inspire#469
> ui: add noarchive meta tag to all pages

- backend/inspirehep/assign/utils.py
- backend/inspirehep/assign/views.py
- backend/tests/integration/assign/test_views.py
- backend/tests/unit/assign/test_assign_utils.py
* ref: cern-sis/issues-inspire#467
> assign: fix author `can_claim` check

- ui/src/__tests__/App.test.tsx
- ui/src/common/components/SearchResults.tsx
- ui/src/common/routes.ts
- ui/src/holdingpen-new/__tests__/index.test.tsx
- ui/src/holdingpen-new/components/AuthorResultItem.tsx
- ui/src/holdingpen-new/components/Breadcrumbs.tsx
- ui/src/holdingpen-new/components/ResultItem.less
- ui/src/holdingpen-new/components/ResultItemWithActions.tsx
- ui/src/holdingpen-new/components/ResultitemWithComparison.tsx
- ui/src/holdingpen-new/containers/DashboardPageContainer/DashboardPageContainer.less
- ui/src/holdingpen-new/containers/DashboardPageContainer/DashboardPageContainer.tsx
- ui/src/holdingpen-new/containers/SearchPageContainer/SearchPageContainer.tsx
- ui/src/holdingpen-new/containers/__tests__/DashboardPageContainer.test.tsx
- ui/src/holdingpen-new/containers/__tests__/SearchPageContainer.test.tsx
- ui/src/holdingpen-new/token.ts
* ref: cern-sis/issues-inspire#475
> ui: connect and adjust new holdingpen search page

- ui/src/common/components/SearchResults.tsx
- ui/src/common/routes.ts
- ui/src/holdingpen-new/components/AuthorResultItem.tsx
- ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
- ui/src/holdingpen-new/containers/DetailPageContainer/DetailPageContainer.less
- ui/src/holdingpen-new/containers/SearchPageContainer/SearchPageContainer.tsx
* ref: cern-sis/issues-inspire#478
> ui: new holdingpen - author detail page

- ui/src/common/PrivateRoute.tsx
- ui/src/common/routes.ts
- ui/src/holdingpen-new/__tests__/index.test.tsx
- ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
- ui/src/holdingpen-new/containers/LoginPageContainer/LoginPageContainer.tsx
- ui/src/holdingpen-new/containers/SearchPageContainer/SearchPageContainer.tsx
- ui/src/holdingpen-new/index.tsx
- ui/src/holdingpen-new/token.ts
- ui/src/holdingpen-new/utils/utils.ts
* ref: cern-sis/issues-inspire#492
> ui: added login page to new holdinpen

- ui/.eslintrc
- ui/public/outdated-browser.html
- ui/src/common/components/LinkWithTargetBlank.tsx
- ui/src/common/components/__tests__/__snapshots__/APIButton.test.tsx.snap
- ui/src/common/components/__tests__/__snapshots__/LinkWithTargetBlank.test.jsx.snap
- ui/src/common/layouts/Header/Banner.tsx
- ui/src/common/layouts/Header/__tests__/__snapshots__/Banner.test.jsx.snap
- ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
- ui/src/home/components/NewsAndUpdates.tsx
- ui/src/home/components/__tests__/__snapshots__/NewsAndUpdates.test.jsx.snap
- ui/src/literature/components/ReferenceDiffInterface/__tests__/__snapshots__/ReferenceDiffInterface.test.tsx.snap
* ref: cern-sis/issues-inspire#506
> ui: remove `rel="noopener noreferrer"` from external links

- ui/src/holdingpen-new/components/AuthorResultItem.tsx
- ui/src/holdingpen-new/containers/DashboardPageContainer/DashboardPageContainer.less
- ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
- ui/src/holdingpen-new/containers/SearchPageContainer/SearchPageContainer.tsx
* ref: cern-sis/issues-inspire#503
> ui: handle new data structure in new holdingpen

- backend/inspirehep/matcher/api.py
- backend/inspirehep/matcher/config.py
- backend/tests/integration/matcher/test_api.py
ref: https://github.com/cern-sis/issues-inspire/issues/349
> matcher: only consider first author for thesis fuzzy match

- backend/inspirehep/editor/views.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/integration/editor/test_editor_views.py
- backend/tests/integration/editor/test_editor_views/author_list.xml
- record-editor/src/app/shared/components/extract-actions/author-extract-actions.component.ts
- record-editor/src/app/shared/components/extract-actions/extract-actions.component.html
* ref cern-sis/issues-inspire#427
> editor: support of authorlist xml extraction

- ui/src/holdingpen-new/components/AuthorResultItem.tsx
- ui/src/holdingpen-new/components/ResultItemWithActions.tsx
* ref: cern-sis/issues-inspire#517
> ui: handle update author case

- ui/src/holdingpen-new/components/Links.tsx
- ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
* ref: cern-sis/issues-inspire#541
> ui: fix wrong orcid source

- ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
* ref: cern-sis/issues-inspire#519
> ui: connect snow ticket info in new holdingpen

- ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
* ref: cern-sis/issues-inspire#522
> ui: connect accept curate decision in new holdingpen

- ui/src/holdingpen-new/components/Links.tsx
- ui/src/holdingpen-new/components/ResultItem/AuthorResultItem.tsx
- ui/src/holdingpen-new/components/ResultItem/__tests__/AuthorResultItem.test.tsx
- ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
- ui/src/holdingpen-new/containers/DetailPageContainer/__tests__/__snapshots__/AuthorDetailPageContainer.test.tsx.snap
- ui/src/holdingpen-new/utils/utils.tsx
* ref: cern-sis/issues-inspire#518
> ui: display decision on completed workflows in new holdingpen

- backend/tests/integration/editor/test_editor_views/author_list.xml
- record-editor/src/app/shared/components/extract-actions/author-extract-actions.component.ts
ref: https://github.com/cern-sis/issues-inspire/issues/557
> editor: improve author xml detection

- ui/src/actions/holdingpen.ts
- ui/src/holdingpen-new/__tests__/__snapshots__/index.test.tsx.snap
- ui/src/holdingpen-new/components/Breadcrumbs/Breadcrumbs.tsx
- ui/src/holdingpen-new/components/SearchFilters.tsx
- ui/src/holdingpen-new/containers/DashboardPageContainer/DashboardPageContainer.tsx
- ui/src/holdingpen-new/utils/__tests__/utils.test.tsx
- ui/src/holdingpen-new/utils/utils.tsx
* ref: cern-sis/issues-inspire#480
> ui: connect search in new holdingpen

- ui/src/actions/holdingpen.ts
- ui/src/holdingpen-new/components/SearchFilters.tsx
- ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
- ui/src/holdingpen-new/containers/SearchPageContainer/SearchPageContainer.less
- ui/src/holdingpen-new/containers/SearchPageContainer/SearchPageContainer.tsx
- ui/src/holdingpen-new/containers/SearchPageContainer/__tests__/__snapshots__/SearchPageContainer.test.tsx.snap
- ui/src/holdingpen-new/notifications.ts
* ref: cern-sis/issues-inspire#553
> ui: display decision on ui instantly in new holdingpen

- backend/data/records/conferences/1794610.json
- ui/src/backoffice/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
* ref: cern-sis/issues-inspire#563
> ui: fixed error link in backoffice ui

- backend/data/records/conferences/1794610.json
- ui/src/backoffice/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
* ref: cern-sis/issues-inspire#562
> ui: fix display of tables on small screen

- ui/src/backoffice/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
* ref: cern-sis/issues-inspire#561
> ui: added link to running dag for admins

- backend/inspirehep/mailing/providers/mailtrain.py
- backend/tests/integration/mailing/cassettes/test_mailtrain_subscribe_user_to_list.yaml
* ref: cern-sis/issues-inspire/issues/360
> mailtrain: force subscribe if unsubscribed

- backend/data/records/jobs/1813119.json
- record-editor/src/app/app.module.ts
- record-editor/src/app/app.router.ts
- record-editor/src/app/backoffice-editor/backoffice-editor.component.html
- record-editor/src/app/backoffice-editor/backoffice-editor.component.ts
- record-editor/src/app/backoffice-editor/backoffice-editor.module.ts
- record-editor/src/app/backoffice-editor/backoffice.router.ts
- record-editor/src/app/core/services/backoffice-api-auth.service.ts
- record-editor/src/app/core/services/backoffice-api.service.ts
- record-editor/src/app/core/services/index.ts
- record-editor/src/app/holdingpen-editor/backoffice-save-button/backoffice-save-button.component.html
- record-editor/src/app/holdingpen-editor/backoffice-save-button/backoffice-save-button.component.ts
- record-editor/src/app/holdingpen-editor/backoffice-save-button/index.ts
- record-editor/src/app/holdingpen-editor/holdingpen-editor.module.ts
- record-editor/src/app/holdingpen-editor/holdingpen-toolbar/holdingpen-toolbar.component.html
- record-editor/src/app/holdingpen-editor/holdingpen-toolbar/holdingpen-toolbar.component.ts
- record-editor/src/app/shared/interfaces/workflow-object.ts
- record-editor/src/environments/environment.prod.ts
- record-editor/src/environments/environment.ts
- ui/src/backoffice/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
- ui/src/backoffice/containers/DetailPageContainer/__tests__/__snapshots__/AuthorDetailPageContainer.test.tsx.snap
* ref: cern-sis/issues-inspire#538
> record-editor: open backoffice workflows in editor

- .github/workflows/backend-tests.yml
This reverts commit 6640b89990ef9ae78c3abefcb75989ecf39060b2.
> Revert "build(deps): bump actions/upload-artifact from 3 to 4"

- backoffice/.envs/local/.django
- backoffice/backoffice/workflows/api/serializers.py
- backoffice/backoffice/workflows/api/utils.py
- backoffice/backoffice/workflows/api/views.py
- backoffice/backoffice/workflows/tests/cassettes/TestAirflowUtils.test_delete_workflow_dag.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAirflowUtils.test_delete_workflow_dag_runs.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAirflowUtils.test_fetch_data_workflow_dag.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAirflowUtils.test_find_executed_dags.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAirflowUtils.test_find_failed_dag.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAirflowUtils.test_restart_failed_tasks.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAirflowUtils.test_restart_failed_tasks_no_tasks.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAirflowUtils.test_restart_workflow_dags.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAirflowUtils.test_trigger_airflow_dag.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAuthorWorkflowViewSet.test_accept_author.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAuthorWorkflowViewSet.test_create_author.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAuthorWorkflowViewSet.test_reject_author.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAuthorWorkflowViewSet.test_restart_a_task.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAuthorWorkflowViewSet.test_restart_full_dagrun.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAuthorWorkflowViewSet.test_restart_with_params.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAuthorWorkflowViewSet.test_validate_invalid_schema_record.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAuthorWorkflowViewSet.test_validate_no_schema_record.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAuthorWorkflowViewSet.test_validate_not_valid_record.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestAuthorWorkflowViewSet.test_validate_valid_record.yaml
- backoffice/backoffice/workflows/tests/cassettes/TestWorkflowViewSet.test_delete.yaml
- backoffice/backoffice/workflows/tests/conftest.py
- backoffice/backoffice/workflows/tests/test_views.py
- record-editor/src/app/backoffice-editor/backoffice-editor.component.ts
- record-editor/src/app/shared/interfaces/workflow-object.ts
ref: https://github.com/cern-sis/issues-inspire/issues/585
ref: https://github.com/cern-sis/issues-inspire/issues/578
> backoffice: add validation errors in response

- backoffice/backoffice/authors/api/views.py
- backoffice/backoffice/authors/tests/test_views.py
*ref:cern-sis/issues-inspire/issues/603
> backoffice: add workflow_id to author create rout

- workflows/dags/author/author_create/author_create_approved.py
- workflows/dags/author/author_create/author_create_init.py
- workflows/dags/author/author_create/shared_tasks.py
- workflows/dags/author/author_update/author_update.py
- workflows/plugins/hooks/backoffice/workflow_ticket_management_hook.py
- workflows/tests/cassettes/TestAuthorCreate.test_close_author_create_user_ticket.yaml
*ref: cern-sis/issues-inspire/issues/582
> worfklows: update author routes

- backoffice/config/settings/base.py
*ref: cern-sis/issues-inspire/issues/604
> backoffice: disable email verification

- record-editor/src/app/core/services/global-app-state.service.ts
* ref: cern-sis/issues-inspire/609
> editor: add support of uploading files from holdingpen

- .pre-commit-config.yaml
- workflows/dags/author/author_create/author_create_approved.py
- workflows/dags/author/author_create/author_create_init.py
- workflows/dags/author/author_create/author_create_rejected.py
- workflows/dags/author/author_update/author_update.py
- workflows/plugins/hooks/backoffice/workflow_management_hook.py
- workflows/tests/cassettes/TestWorkflowManagementHook.test_get_workflow_url.yaml
- workflows/tests/conftest.py
- workflows/tests/test_author_create_tasks.py
- workflows/tests/test_workflow_management_hook.py
* ref: cern-sis/issues-inspire/issues/614
> workflows: fixed accesses to authors api

- workflows/dags/author/author_create/author_create_init.py
- workflows/dags/author/author_update/author_update.py
- workflows/tests/cassettes/TestAuthorCreateInit.test_set_schema.yaml
- workflows/tests/cassettes/TestAuthorUpdate.test_create_ticket_on_author_update.yaml
- workflows/tests/test_author_tasks.py
* ref: cern-sis/issues-inspire/issues/611
> workflows: fixed set_schema and create_ticket_on_author_update

- ui/src/setupTests.js
ref: https://github.com/cern-sis/issues-inspire/issues/629
> ui: mock notification ui in tests

- README.md
* ref: cern-sis/issues-inspire/issues/606
> documentation: improve documentation on how to run and login to orcid

- backoffice/config/settings/production_base.py
*ref: cern-sis/issues-inspire/issues/509
> backoffice: allow cookies in cors requests

- ui/src/data/components/DataItem.jsx
- ui/src/data/components/__tests__/__snapshots__/DataItem.test.jsx.snap
- ui/src/data/containers/DetailPageContainer/DetailPageContainer.tsx
* ref: cern-sis/issues-inspire/issues/637
> ui: fix dois on search results

- Makefile
- README.md
- docker-compose.services.yml
- workflows/dags/author/author_create/author_create_init.py
- workflows/plugins/hooks/backoffice/workflow_management_hook.py
- workflows/plugins/include/utils/set_workflow_status.py
- workflows/tests/cassettes/TestSetWorkflowStatus.test_set_workflow_status_to_error.yaml
- workflows/tests/cassettes/TestWorkflowManagementHook.test_set_workflow_status.yaml
- workflows/tests/cassettes/TestWorkflowManagementHook.test_update_workflow.yaml
- workflows/tests/test_set_workflow_status.py
- workflows/tests/test_workflow_management_hook.py
also some small config fixes for easy testing with docker
* ref: https://github.com/cern-sis/issues-inspire/issues/643
> workflows: fix author submissions not erroring

- workflows/dags/data/data_harvest.py
* ref: cern-sis/issues-inspire/issues/641
> workflows: add clearer logging

- ui/src/backoffice/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
- workflows/dags/author/author_create/author_create_approved.py
cern-sis/issues-inspire/issues/615
> generic: deprecate create-ticket param

- workflows/plugins/hooks/backoffice/workflow_management_hook.py
- workflows/plugins/hooks/backoffice/workflow_ticket_management_hook.py
ref: https://github.com/cern-sis/issues-inspire/issues/646
> backoffice: replace run_with_advanced_retry calls

- workflows/dags/data/data_harvest.py
- workflows/tests/test_data_tasks.py
* ref: cern-sis/issues-inspire/issues/630
> workflows: update source of data harvest

- backend/data/records/data/2727274.json
- backend/data/records/data/457569.json
- backend/data/records/data/457570.json
- ui/src/common/components/AuthorList.jsx
- ui/src/data/__tests__/utils.test.jsx
- ui/src/data/components/DOIListShowAll.jsx
- ui/src/data/components/DataItem.jsx
- ui/src/data/components/__tests__/DOIListShowAll.test.jsx
- ui/src/data/components/__tests__/DataItem.test.jsx
- ui/src/data/components/__tests__/__snapshots__/DOIListShowAll.test.jsx.snap
- ui/src/data/components/__tests__/__snapshots__/DataItem.test.jsx.snap
- ui/src/data/containers/DetailPageContainer/DetailPageContainer.tsx
- ui/src/data/utils.ts
- ui/src/literature/components/DOIList.jsx
- ui/src/literature/components/__tests__/DOIList.test.jsx
- ui/src/literature/components/__tests__/__snapshots__/DOIList.test.jsx.snap
- ui/src/literature/components/__tests__/__snapshots__/ReferenceItem.test.jsx.snap
closes: https://github.com/cern-sis/issues-inspire/issues/639
closes: https://github.com/cern-sis/issues-inspire/issues/652
> ui: show all dois for data collection

- backoffice/backoffice/authors/airflow_utils.py
- backoffice/backoffice/authors/api/views.py
- backoffice/backoffice/authors/tests/cassettes/TestAirflowUtils.test_delete_workflow_dag_error.yaml
- backoffice/backoffice/authors/tests/cassettes/TestAirflowUtils.test_find_failed_dag.yaml
- backoffice/backoffice/authors/tests/cassettes/TestAirflowUtils.test_restart_failed_tasks.yaml
- backoffice/backoffice/authors/tests/cassettes/TestAuthorWorkflowViewSet.test_restart_current_task_without_failed_dags.yaml
- backoffice/backoffice/authors/tests/cassettes/TestAuthorWorkflowViewSet.test_restart_current_task_without_ran_dags.yaml
- backoffice/backoffice/authors/tests/cassettes/TestAuthorWorkflowViewSet.test_restart_full_dagrun_without_ran_dags.yaml
- backoffice/backoffice/authors/tests/test_airflow_utils.py
- backoffice/backoffice/authors/tests/test_views.py
ref: https://github.com/cern-sis/issues-inspire/issues/647
> backoffice: set processing state when restarting

- workflows/dags/data/data_harvest.py
- workflows/requirements.txt
- workflows/tests/cassettes/TestDataHarvest.test_normalize_collaborations.yaml
- workflows/tests/test_data_tasks.py
* ref: cern-sis/issues-inspire/issues/635
> workflows: add normalizing collaborations to data harvest

- .github/workflows/backend-tests.yml
- .github/workflows/build-backoffice-workflow.yml
- .github/workflows/build.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/hotfix.yml
- .github/workflows/integration-tests.yml
- .github/workflows/lint.yml
- .github/workflows/pull-request-development-backoffice.yml
- .github/workflows/pull-request-development-inspirehep.yml
- .github/workflows/pull-request-development-workflows.yml
- .github/workflows/push-development-backoffice.yml
- .github/workflows/push-development-inspirehep.yml
- .github/workflows/push-development-workflows.yml
- .github/workflows/push-development.yml
- .github/workflows/push-master-backoffice.yml
- .github/workflows/push-master-inspirehep.yml
- .github/workflows/push-master-workflows.yml
- .github/workflows/release-jupyter.yml
- .github/workflows/release.yml
- .github/workflows/test-backoffice.yml
- .github/workflows/test-workflows.yml
ref: https://github.com/cern-sis/issues-inspire/issues/653
> fix[github workflows]: Set Ubuntu version as 24.04 and "actions/upload-artifact" as v4

- backend/inspirehep/curation/api.py
- backend/inspirehep/curation/utils.py
- backend/inspirehep/curation/views.py
- backend/tests/integration/curation/test_api.py
- workflows/dags/data/data_harvest.py
* ref: cern-sis/issues-inspire/issues/654
> generic: set wf_id to optional on normalization

- ui/src/backoffice/components/Links.tsx
- ui/src/backoffice/components/__tests__/Links.test.tsx
ref: https://github.com/cern-sis/issues-inspire/issues/664
> backoffice-ui: fix orcid links

- ui/src/submissions/authors/components/AuthorForm.jsx
ref: https://github.com/cern-sis/issues-inspire/issues/651
> ui: add bluesky form hint text

- ui/src/backoffice/containers/DetailPageContainer/columnData.tsx
cern-sis/issues-inspire/issues/668
> ui: set end-date default as '-'

- backoffice/backoffice/authors/api/views.py
- backoffice/backoffice/authors/tests/test_views.py
- record-editor/src/app/backoffice-editor/backoffice-editor.component.ts
- record-editor/src/app/holdingpen-editor/backoffice-save-button/backoffice-save-button.component.ts
- record-editor/src/app/holdingpen-editor/holdingpen-editor.component.ts
Ref https://github.com/cern-sis/issues-inspire/issues/663
> record-editor: fix editor validation

- ui/src/backoffice/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
- ui/src/backoffice/containers/DetailPageContainer/__tests__/AuthorDetailPageContainer.test.tsx
- ui/src/backoffice/containers/DetailPageContainer/__tests__/__snapshots__/AuthorDetailPageContainer.test.tsx.snap
ref: https://github.com/cern-sis/issues-inspire/issues/670
> backoffice-ui: display native_names and name_variants on author page

- ui/src/backoffice/components/Links.tsx
- ui/src/backoffice/components/__tests__/Links.test.tsx
ref: https://github.com/cern-sis/issues-inspire/issues/669
> backoffice-ui: add copy button for author ids

- ui/src/data/__tests__/__snapshots__/index.test.jsx.snap
- ui/src/data/__tests__/index.test.jsx
- ui/src/data/__tests__/utils.test.jsx
- ui/src/data/components/DOIListShowAll.jsx
- ui/src/data/components/__tests__/DOIListShowAll.test.jsx
- ui/src/data/components/__tests__/DataItem.test.jsx
- ui/src/data/components/__tests__/__snapshots__/DOIListShowAll.test.jsx.snap
- ui/src/data/components/__tests__/__snapshots__/DataItem.test.jsx.snap
- ui/src/data/containers/DetailPageContainer/DetailPageContainer.tsx
- ui/src/data/containers/SearchPageContainer.jsx
- ui/src/data/index.tsx
- ui/src/data/utils.ts
* ref: cern-sis/issues-inspire/issues/660
> ui[data]: replace enzyme by rtl in the tests

- e2e/cypress/e2e/references.test.js
- ui/src/backoffice/components/Author/AuthorMainInfo.tsx
- ui/src/backoffice/components/Author/PrivateNotes.tsx
- ui/src/backoffice/components/Author/__tests__/AuthorMainInfo.test.tsx
- ui/src/backoffice/components/Author/__tests__/PrivateNotes.test.tsx
- ui/src/backoffice/components/DeleteWorkflow/__tests__/DeleteWorkflow.test.tsx
- ui/src/backoffice/components/ResultItem/__tests__/ResultItem.test.tsx
- ui/src/backoffice/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
- ui/src/backoffice/containers/DetailPageContainer/__tests__/AuthorDetailPageContainer.test.tsx
- ui/src/backoffice/utils/utils.tsx
ref https://github.com/cern-sis/issues-inspire/issues/667
> backoffice: prominent submission + refactoring

- workflows/dags/data/data_harvest.py
- workflows/tests/test_data_tasks.py
* ref: cern-sis/issues-inspire/issues/675
> data: set source to HEPData

- ui/src/backoffice/containers/DetailPageContainer/columnData.tsx
ref: https://github.com/cern-sis/issues-inspire/issues/671
> fix[ui][backoffice]: Make order of the columns under Project membership history the same as Institution history

- .github/workflows/push-master-backoffice.yml
- .github/workflows/push-master-workflows.yml
- .github/workflows/release.yml
ref https://github.com/cern-sis/issues-inspire/issues/636
> gh-actions: add repo to send event

- ui/src/bibliographyGenerator/__tests__/BibliograpyGeneratorPageContainer.test.jsx
- ui/src/setupTests.js
ref https://github.com/cern-sis/issues-inspire/issues/672
> ui: increase waitFor timeout

- ui/src/backoffice/__tests__/__snapshots__/index.test.tsx.snap
- ui/src/backoffice/authors/containers/__tests__/__snapshots__/AuthorDetailPageContainer.test.tsx.snap
- ui/src/backoffice/common/components/Breadcrumbs/Breadcrumbs.tsx
- ui/src/backoffice/common/components/Breadcrumbs/__tests__/Breadcrumbs.test.tsx
- ui/src/backoffice/common/components/Breadcrumbs/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
- ui/src/backoffice/search/containers/__tests__/__snapshots__/SearchPageContainer.test.tsx.snap
ref: https://github.com/cern-sis/issues-inspire/issues/683
> backoffice-ui: fix breadcrumb icon and link

- ui/src/backoffice/authors/components/ResultItem/ResultItem.less
- ui/src/backoffice/authors/components/ResultItem/ResultItem.tsx
- ui/src/backoffice/authors/components/ResultItem/__tests__/ResultItem.test.tsx
- ui/src/backoffice/authors/containers/AuthorDetailPageContainer.less
- ui/src/backoffice/authors/containers/AuthorDetailPageContainer.tsx
remove decision-pill border color and fix typo
ref: https://github.com/cern-sis/issues-inspire/issues/682
> backoffice-ui: remove decision-pill border color

- ui/src/data/components/DataItem.jsx
- ui/src/data/containers/DetailPageContainer/DetailPageContainer.tsx
- ui/src/data/containers/DetailPageContainer/__tests__/__snapshots__/DetailPageContainer.test.jsx.snap
ref https://github.com/cern-sis/issues-inspire/issues/695
> ui: remove edit button from data

- ui/src/backoffice/authors/containers/AuthorDetailPageContainer.tsx
- ui/src/backoffice/authors/containers/__tests__/AuthorDetailPageContainer.test.tsx
- ui/src/data/containers/DetailPageContainer/DetailPageContainer.tsx
ref https://github.com/cern-sis/issues-inspire/issues/679
> backoffice-ui: display record id in decision box

- ui/src/submissions/authors/containers/AuthorSubmissionPageContainer.jsx
- ui/src/submissions/authors/containers/__tests__/AuthorSubmissionPageContainer.test.jsx
ref: https://github.com/cern-sis/issues-inspire/issues/674
Before:
After:
> feat[ui]: Add author update warning to the submission form

- ui/src/common/components/EventStartDateFilter.jsx
- ui/src/common/components/__tests__/__snapshots__/EventStartDateFilter.test.jsx.snap
- ui/src/seminars/__tests__/__snapshots__/index.test.jsx.snap
- ui/src/seminars/__tests__/index.test.jsx
- ui/src/seminars/components/ExportToCalendarAction/__tests__/ExportToCalendarAction.test.jsx
- ui/src/seminars/components/ExportToCalendarAction/__tests__/__snapshots__/ExportToCalendarAction.test.jsx.snap
- ui/src/seminars/components/__tests__/SeminarCountWarning.test.jsx
- ui/src/seminars/components/__tests__/SeminarDatesTimes.test.jsx
- ui/src/seminars/components/__tests__/SeminarItem.test.jsx
- ui/src/seminars/components/__tests__/__snapshots__/SeminarCountWarning.test.jsx.snap
- ui/src/seminars/components/__tests__/__snapshots__/SeminarDatesTimes.test.jsx.snap
- ui/src/seminars/components/__tests__/__snapshots__/SeminarItem.test.jsx.snap
- ui/src/seminars/containers/DetailPageContainer.jsx
- ui/src/seminars/containers/SeminarSearchContainer.jsx
- ui/src/seminars/containers/__tests__/SeminarStartDateFilterContainter.test.jsx
Wasn't able to convert test
`dispatches SEARCH_QUERY_UPDATE onChange with start_date and timezone if specific date` to rtl
> Enzyme is dead seminar

- ui/src/data/containers/DetailPageContainer/DetailPageContainer.tsx
ref https://github.com/cern-sis/issues-inspire/issues/681
> ui: add document head to data

- ui/src/common/components/SearchBoxNamespaceSelect.tsx
- ui/src/common/components/__tests__/SearcBoxNamespaceSelect.test.jsx
- ui/src/common/components/__tests__/__snapshots__/SearcBoxNamespaceSelect.test.jsx.snap
- ui/src/common/containers/SearchBoxNamespaceSelectContainer.tsx
ref https://github.com/cern-sis/issues-inspire/issues/708
> ui: hide data option from the main dropdown

- backend/inspirehep/submissions/views.py
* ref: cern-sis/issues-inspire/issues/724
> authors: set feature flag to be a switch

- backend/inspirehep/records/marshmallow/data/ui.py
- ui/src/data/components/DataItem.jsx
- ui/src/data/components/__tests__/DataItem.test.jsx
- ui/src/data/components/__tests__/__snapshots__/DataItem.test.jsx.snap
* ref https://github.com/cern-sis/issues-inspire/issues/676
> serializers: add literature to data list

- ui/src/backoffice/authors/components/AuthorMainInfo.tsx
- ui/src/backoffice/authors/containers/AuthorDetailPageContainer.tsx
- ui/src/backoffice/authors/containers/__tests__/AuthorDetailPageContainer.test.tsx
- ui/src/backoffice/authors/containers/__tests__/__snapshots__/AuthorDetailPageContainer.test.tsx.snap
* ref: cern-sis/issues-inspire/issues/696
> ui[backoffice]: remove Links if empty from author page

- ui/src/backoffice/authors/containers/AuthorDetailPageContainer.tsx
- ui/src/backoffice/authors/containers/__tests__/__snapshots__/AuthorDetailPageContainer.test.tsx.snap
* ref: cern-sis/issues-inspire/issues/748
> ui[backoffice]: remove 'skip to next step' button

- ui/.dockerignore
ref: https://github.com/cern-sis/issues-inspire/issues/731
> fix(ui): add .dockerignore to ui

- ui/src/bibliographyGenerator/__tests__/BibliographyGenerator.test.jsx
- ui/src/bibliographyGenerator/__tests__/BibliograpyGeneratorPageContainer.test.jsx
- ui/src/bibliographyGenerator/__tests__/__snapshots__/BibliographyGenerator.test.jsx.snap
ref: https://github.com/cern-sis/issues-inspire/issues/701
> fix(ui): Remove enzyme from Bibliography Generator

- backend/data/records/data/2727274.json
- backend/data/records/data/2727275.json
- backend/data/records/data/457568.json
- backend/data/records/data/457569.json
- backend/data/records/data/457570.json
- backend/inspirehep/records/marshmallow/data/es.py
- backend/inspirehep/records/marshmallow/data/ui.py
- backend/tests/integration/records/serializers/json/test_data.py
* ref https://github.com/cern-sis/issues-inspire/issues/747
> backend: lit serializer to data index

- ui/src/backoffice/authors/containers/AuthorDetailPageContainer.tsx
- ui/src/backoffice/authors/containers/__tests__/__snapshots__/AuthorDetailPageContainer.test.tsx.snap
- ui/src/backoffice/utils/__tests__/utils.test.tsx
- ui/src/backoffice/utils/utils.tsx
ref: https://github.com/cern-sis/issues-inspire/issues/750
> fix(ui)(backoffice): Use ISO format for dates on author workflows

- ui/src/backoffice/authors/containers/AuthorDetailPageContainer.tsx
- ui/src/backoffice/common/components/ResultItem/ResultItem.tsx
- ui/src/backoffice/utils/__tests__/utils.test.tsx
- ui/src/backoffice/utils/utils.tsx
ref: https://github.com/cern-sis/issues-inspire/issues/750
Related: https://github.com/inspirehep/inspirehep/pull/3434
> fix(ui)(backoffice): return separate date and time in formatDateTime()

- workflows/dags/author/author_create/author_create_init.py
- workflows/dags/author/author_update/author_update.py
- workflows/dags/author/shared_tasks.py
- workflows/tests/cassettes/TestAuthorCreateInit.test_set_submission_number.yaml
- workflows/tests/test_author_tasks.py
* ref: cern-sis/issues-inspire/issues/754
> workflows[author]: add submission number

- ui/src/common/components/Logo/Logo.less
- ui/src/common/layouts/Header/Header.less
- ui/src/common/layouts/Header/Header.tsx
ref: https://github.com/cern-sis/issues-inspire/issues/752
https://github.com/user-attachments/assets/44362ec0-36c3-4964-9d97-9c441db72133
https://github.com/user-attachments/assets/7d1fe293-8284-4b72-b7ac-013748d1583e
https://github.com/user-attachments/assets/b793eaab-bafe-4a91-8c45-d1550e57ff21
> fix(ui): fix fake-collections-menu on header

- workflows/dags/data/bulk_data_harvest.py
- workflows/plugins/hooks/tenacity_config.py
* ref: cern-sis/issues-inspire/issues/760
N.B. I havent added tests and this dag is only intended to be use temporarily. lmk if it makes sense to add them
> workflows[data]: add a yearly data harvest

- backoffice/backoffice/authors/fixtures/workflows.json
- docker-compose.yml
- record-editor/angular-cli.json
- record-editor/src/app/shared/config/api.config.ts
- record-editor/src/config.js
- record-editor/src/environments/environment.prod.ts
- record-editor/src/environments/environment.ts
- record-editor/src/index.html
- ui/public/config.js
ref https://github.com/cern-sis/issues-inspire/issues/746
> record-editor: dynamic environment urls

- ui/src/common/layouts/CollectionsMenu/CollectionsMenu.less
- ui/src/common/layouts/CollectionsMenu/CollectionsMenu.tsx
- ui/src/common/layouts/CollectionsMenu/__tests__/__snapshots__/CollectionsMenu.test.jsx.snap
* ref https://github.com/cern-sis/issues-inspire/issues/703
> ui: add beta tag to data

- workflows/dags/data/bulk_data_harvest.py
* ref: cern-sis/issues-inspire/issues/767
> workflows[data]: fix creation date

- backend/inspirehep/search/mappings/os-v2/records/data.json
ref https://github.com/cern-sis/issues-inspire/issues/745
> os: add mapping for literature

- ui/src/errors/__tests__/index.test.jsx
- ui/src/errors/components/__tests__/Error401.test.jsx
- ui/src/errors/components/__tests__/Error404.test.jsx
- ui/src/errors/components/__tests__/Error500.test.jsx
- ui/src/errors/components/__tests__/ErrorAppCrash.test.jsx
- ui/src/errors/components/__tests__/ErrorNetwork.test.jsx
- ui/src/errors/components/__tests__/ErrorPage.test.jsx
- ui/src/errors/components/__tests__/__snapshots__/Error401.test.jsx.snap
- ui/src/errors/components/__tests__/__snapshots__/Error404.test.jsx.snap
- ui/src/errors/components/__tests__/__snapshots__/Error500.test.jsx.snap
- ui/src/errors/components/__tests__/__snapshots__/ErrorAppCrash.test.jsx.snap
- ui/src/errors/components/__tests__/__snapshots__/ErrorNetwork.test.jsx.snap
- ui/src/errors/components/__tests__/__snapshots__/ErrorPage.test.jsx.snap
* ref https://github.com/cern-sis/issues-inspire/issues/773
> ui: remove enzyme from errors

- backend/inspirehep/indexer/api.py
- backend/inspirehep/indexer/tasks.py
- backend/inspirehep/records/api/data.py
- backend/inspirehep/records/api/literature.py
- backend/inspirehep/records/api/mixins.py
- backend/inspirehep/records/config.py
- backend/inspirehep/records/marshmallow/data/es.py
- backend/inspirehep/records/marshmallow/literature/es.py
- backend/inspirehep/records/marshmallow/utils.py
- backend/inspirehep/records/receivers.py
- backend/inspirehep/search/facets.py
- backend/tests/integration-async/records/api/test_data.py
- backend/tests/integration/matcher/test_views.py
- backend/tests/integration/records/views/test_views_data.py
- backend/tests/integration/search/test_facets.py
* Add endpoint to filter for Authors in Data Collections
* Add facet to fetch Data Records of Author
* Reindex data records if their linked Literature updates
ref: https://github.com/cern-sis/issues-inspire/issues/720
> backend: add data facet for author agg

- ui/src/home/components/NewsAndUpdates.tsx
ref: https://github.com/cern-sis/issues-inspire/issues/771
> ui: fix link overflow for news

- ui/src/authors/containers/DetailPageContainer/DetailPageContainer.tsx
* ref https://github.com/cern-sis/issues-inspire/issues/786
> ui: add dataset count

- backend/data/records/data/2727274.json
- backend/data/records/data/2727275.json
- backend/inspirehep/records/marshmallow/data/ui.py
- ui/src/common/components/KeywordList.jsx
- ui/src/data/containers/DetailPageContainer/DetailPageContainer.tsx
- ui/src/data/containers/DetailPageContainer/__tests__/DetailPageContainer.test.tsx
- ui/src/data/containers/DetailPageContainer/__tests__/__snapshots__/DetailPageContainer.test.tsx.snap
had to add the `Latex` component to the tags. else some of the observables woulndt get properly displayed
> Data UI but good

- backend/inspirehep/records/api/mixins.py
- backend/tests/integration/records/api/test_api_data.py
- backend/tests/integration/records/api/test_api_mixins.py
* ref: cern-sis/issues-inspire/issues/800
> backend: fix data record update

- backend/inspirehep/records/config.py
- backend/inspirehep/search/aggregations.py
- backend/inspirehep/search/facets.py
- backend/tests/integration/records/views/test_views_data.py
- backend/tests/integration/search/test_aggregations.py
- backend/tests/integration/search/test_facets.py
* ref https://github.com/cern-sis/issues-inspire/issues/796
> backend: add more facets for data

- ui/src/authors/containers/DetailPageContainer/DetailPageContainer.tsx
- ui/src/data/containers/DataSearchPageContainer.jsx
- ui/src/data/containers/SearchPageContainer.jsx
- ui/src/middlewares/syncLocationWithSearch.js
- ui/src/search/config.js
* ref https://github.com/cern-sis/issues-inspire/issues/796
> ui: facets for data + embedded

- ui/src/authors/containers/DetailPageContainer/DetailPageContainer.tsx
* ref https://github.com/cern-sis/issues-inspire/issues/784
> ui: enable datasets for everyone

- ui/src/literature/components/LiteratureItem.jsx
- ui/src/literature/components/ReferenceDiffInterface/ReferenceDiffInterface.tsx
- ui/src/literature/containers/DetailPageContainer/DetailPageContainer.tsx
(Still using external url, in the future this needs to change or some components won't work correctly (Link))
ref: https://github.com/cern-sis/issues-inspire/issues/766
> feat(ui): don't open dataset links in new tab

- backend/inspirehep/utils.py
- backend/poetry.lock
- backend/pyproject.toml
ref: https://github.com/cern-sis/issues-inspire/issues/776
depends on: https://github.com/cern-sis/kubernetes-inspire/pull/246
> backend: add zulip dependency

- .github/workflows/backend-tests.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/test-backoffice.yml
- Makefile
- backend/inspirehep/config.py
- backend/tests/integration-async/conftest.py
- backend/tests/integration/conftest.py
- backoffice/.envs/local/.postgres
- docker-compose.services.yml
- docker-compose.yml
- init.sql
*ref: cern-sis/issues-inspire/issues/587
Continued in https://github.com/inspirehep/inspirehep/pull/3495
> docker: separate postgres in different dbs

- backend/inspirehep/utils.py
ref: https://github.com/cern-sis/issues-inspire/issues/776
depends on: https://github.com/cern-sis/kubernetes-inspire/pull/246
> backend: add zulip env vars

- backend/inspirehep/assign/tasks.py
- backend/inspirehep/curation/tasks.py
- backend/inspirehep/logger/config.py
- backend/inspirehep/records/tasks.py
- backend/inspirehep/sitemap/tasks.py
- backend/inspirehep/utils.py
* ref https://github.com/cern-sis/issues-inspire/issues/711
> monitoring: error messages for record-indexer

- backend/inspirehep/logger/config.py
- backend/inspirehep/utils.py
ref https://github.com/cern-sis/issues-inspire/issues/715
ref https://github.com/cern-sis/issues-inspire/issues/712
> 712 redirect references + matcher

- backend/inspirehep/logger/config.py
- backend/inspirehep/utils.py
* ref https://github.com/cern-sis/issues-inspire/issues/822
> monitoring: error messagees for hal push

- .github/workflows/pull-request-development-inspirehep.yml
- .github/workflows/pull-request-master-inspirehep.yml
Add dependency to only run tests if linting was successful
> actions: add lint dependency to inspirehep tests

- backend/inspirehep/search/api.py
- backend/tests/integration/search/cassettes/test_search_with_special_characters_returns_correct_status_code.yaml
- backend/tests/integration/search/test_api.py
* ref: cern-sis/issues-inspire/issues/795
> backend: fix `500` on special chars search

- backend/inspirehep/logger/config.py
- backend/inspirehep/utils.py
* ref: cern-sis/issues-inspire/issues/710
> monitoring: error messages for disambiguation

- ui/src/common/components/SearchBoxNamespaceSelect.tsx
ref: https://github.com/cern-sis/issues-inspire/issues/817
> ui: increase max dropdown height

- workflows/dags/data/bulk_data_harvest.py
- workflows/dags/data/data_harvest.py
- workflows/tests/data_records/ins1906174_version3.json
- workflows/tests/test_data_tasks.py
* ref: cern-sis/issues-inspire/issues/824
> workflows[data]: fix data harvest

- backend/inspirehep/hal/core/sword.py
- backend/tests/integration/hal/test_core_sword.py
ref: https://github.com/cern-sis/issues-inspire/issues/831
> backend: add halpush duplicate header

- backend/inspirehep/assign/views.py
* ref: cern-sis/issues-inspire/issues/839
> fix: export_papers_to_cds now runs as task

- ui/src/authors/containers/SearchPageContainer.jsx
- ui/src/common/constants.ts
- ui/src/common/utils.ts
- ui/src/conferences/containers/SearchPageContainer.jsx
- ui/src/data/containers/SearchPageContainer.jsx
- ui/src/experiments/containers/SearchPageContainer.jsx
- ui/src/institutions/containers/SearchPageContainer.jsx
- ui/src/jobs/containers/SearchPageContainer.jsx
- ui/src/journals/containers/SearchPageContainer.tsx
- ui/src/literature/__tests__/__snapshots__/index.test.tsx.snap
- ui/src/literature/containers/SearchPageContainer.jsx
- ui/src/seminars/components/SearchPage.jsx
- ui/src/seminars/containers/SeminarSearchContainer.jsx
* ref: cern-sis/issues-inspire#820
https://github.com/user-attachments/assets/72ae11f1-ad38-443d-8b3e-cab12e265b9e
> ui: center the no results message on search page

- backend/inspirehep/factory.py
- backend/tests/integration/records/views/test_views.py
* ref: https://github.com/cern-sis/issues-inspire/issues/793
> backend: ensure REST errors for all Exceptions

- backend/inspirehep/editor/views.py
- backend/tests/integration-async/editor/test_editor_api.py
* ref https://github.com/cern-sis/issues-inspire/issues/834
> editor: ensure default user_email

- backend/inspirehep/disambiguation/tasks.py
* ref: https://github.com/cern-sis/issues-inspire/issues/821
> celery: fix disambiguation parameter

- backend/inspirehep/orcid/builder.py
- backend/tests/integration/orcid/test_orcid_converter.py
* ref: https://github.com/cern-sis/issues-inspire/issues/829
> orcid: fix titles with xml

- backend/inspirehep/sitemap/cli.py
- backend/tests/integration/sitemap/test_cli.py
* ref: cern-sis/issues-inspire/issues/869
> sitemap: run as a celery task

- backend/inspirehep/records/tasks.py
* ref https://github.com/cern-sis/issues-inspire/issues/882
> tasks: catch KeyError on redirect references

- backend/poetry.lock
- backend/pyproject.toml
ref: https://github.com/cern-sis/issues-inspire/issues/861
ref: https://github.com/inspirehep/inspire-json-merger/pull/124
> bump: inspire-json-merger

- backend/inspirehep/utils.py
* ref https://github.com/cern-sis/issues-inspire/issues/836
For reference -> [#inspire > inspire-qa-tasks @ 💬](https://cern-rcs-sis.zulipchat.com/#narrow/channel/310485-inspire/topic/inspire-qa-tasks/near/520695478)
> monitoring: collapse error message

- backoffice/backoffice/authors/api/utils.py
- backoffice/backoffice/authors/api/views.py
- backoffice/backoffice/authors/tests/cassettes/TestAuthorWorkflowViewSet.test_create_returns_503_if_airflow_fails.yaml
- backoffice/backoffice/authors/tests/test_utils.py
- backoffice/backoffice/authors/tests/test_views.py
ref: https://github.com/cern-sis/issues-inspire/issues/918
> backoffice: better airflow exception handling

- backend/data/records/literature/1358394.json
- backend/inspirehep/records/marshmallow/literature/common/external_system_identifier.py
- backend/tests/unit/records/marshmallow/literature/common/test_external_system_identifier.py
- backend/tests/unit/records/marshmallow/literature/test_ui.py
* ref https://github.com/cern-sis/issues-inspire/issues/928
> cds: cdsrdm in favor of cds

- workflows/dags/cds/cds_harvest.py
- workflows/dags/cds/cds_rdm_harvest.py
- workflows/dags/data/data_harvest.py
* ref: cern-sis/issues-inspire/issues/933
> workflows: cache venvs in celery workers

- Makefile
- backoffice/config/settings/base.py
- backoffice/config/settings/test.py
- docker-compose.yml
* ref: cern-sis/issues-inspire/issues/917
> celery: create documents in os using celery

- backend/data/records/literature/2610294.json
- backend/data/records/literature/2610370.json
- backend/data/records/literature/2786837.json
- backend/inspirehep/records/marshmallow/literature/utils.py
- backend/tests/integration/records/test_utils.py
* ref https://github.com/cern-sis/issues-inspire/issues/950
> backend: fix linked books

- backend/inspirehep/records/marshmallow/literature/cds.py
- backend/tests/integration/records/serializers/json/test_literature.py
* ref https://github.com/cern-sis/issues-inspire/issues/876
> cds: optimize query

- backoffice/backoffice/management/utils.py
now it gets all the required fields for opensearch to work
> cli: fix delete_author

- backend/inspirehep/records/marshmallow/literature/cds.py
- backend/tests/integration/records/serializers/json/test_literature.py
* ref https://github.com/cern-sis/issues-inspire/issues/876
> cds: resolve orcid only for claimed

- backoffice/.envs/local/.django
- docker-compose.yml
* ref: cern-sis/issues-inspire/issues/967
> backoffice: loaddata index fix

- workflows/dags/literature/arxiv_harvest.py
- workflows/requirements.txt
- workflows/scripts/connections/connections.json
- workflows/tests/cassettes/TestArxivHarvest.test_fetch_records_logical_date.yaml
- workflows/tests/cassettes/TestArxivHarvest.test_fetch_records_with_from_until.yaml
- workflows/tests/test_arxiv_harvest.py
- workflows/tests/test_arxiv_harvest/arxiv1608.06937.xml
- workflows/tests/test_arxiv_harvest/arxiv2007.03037-bad.xml
- workflows/tests/test_arxiv_harvest/arxiv2007.03037.xml
- workflows/tests/test_data_tasks.py
* ref: cern-sis/issues-inspire/issues/966
> workflows: implement the arxiv harvest

- backend/inspirehep/records/config.py
- backend/inspirehep/records/marshmallow/literature/base.py
- backend/inspirehep/records/marshmallow/literature/es.py
- backend/inspirehep/records/marshmallow/literature/expanded.py
- backend/inspirehep/records/marshmallow/literature/utils.py
- backend/inspirehep/records/serializers/json/literature.py
- backend/inspirehep/search/mappings/os-v2/records/hep.json
- backend/tests/integration/indexer/test_indexer_literature.py
- backend/tests/integration/records/api/test_api_literature.py
* ref https://github.com/cern-sis/issues-inspire/issues/970
> fix: only put resolved authors in es

- backend/inspirehep/editor/views.py
- backend/tests/integration/editor/test_editor_views.py
- backend/tests/integration/editor/test_editor_views/author_list.xml
* ref: cern-sis/issues-inspire/issues/942
> editor: decode latex in author_list xml

- backend/inspirehep/submissions/errors.py
* ref: cern-sis/issues-inspire/issues/874
> submissions: fix error message

- .github/workflows/backend-tests.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/test-backoffice.yml
- docker-compose.services.yml
* ref https://github.com/cern-sis/issues-inspire/issues/1005
> rabbitmq: bump to 4-management-alpine

- ui/public/config.js
- ui/src/backoffice/authors/containers/AuthorDetailPageContainer.tsx
* ref: cern-sis/issues-inspire/issues/1019
> ui: fix see running dags button

- workflows/requirements.txt
* ref: cern-sis/issues-inspire/issues/1015
> workflows: add sentry

- ui/src/common/components/__tests__/ResultItem.test.jsx
- ui/src/journals/components/JournalItem.tsx
* ref: cern-sis/issues-inspire/issues#823
> ui: removed unnecesary prop and updated test

- workflows/dags/literature/hep_create_dag.py
- workflows/plugins/include/inspire/guess_coreness.py
- workflows/scripts/connections/connections.json
- workflows/tests/test_guess_coreness.py
* ref https://github.com/cern-sis/issues-inspire/issues/1051
> arxiv: implement guess coreness

- workflows/dags/literature/hep_create_dag.py
- workflows/tests/test_hep_tasks.py
- workflows/tests/test_utils.py
*ref: cern-sis/issues-inspire/issues/1067
> workflows: is_arxiv_paper

- e2e/cypress/e2e/jobs.test.js
- e2e/cypress/support/commands/form.js
* ref: cern-sis/issues-inspire#1078
> e2e: fixed job submission test

- backend/inspirehep/oai/config.py
- backend/inspirehep/oai/converter.py
- backend/inspirehep/oai/serializers.py
- backend/inspirehep/oai/utils.py
- backend/inspirehep/records/marshmallow/literature/es.py
- backend/tests/helpers/utils.py
- backend/tests/integration/indexer/test_indexer_literature.py
- backend/tests/integration/orcid/test_orcid_converter.py
- backend/tests/integration/records/serializers/json/test_literature.py
- backend/tests/integration/records/views/test_views_literature.py
- backend/tests/unit/oai/test_converter.py
- backend/tests/unit/records/marshmallow/literature/common/test_abstract_source.py
- backend/tests/unit/records/marshmallow/literature/test_es_schema.py
* ref https://github.com/cern-sis/issues-inspire/issues/1073
> backend: introduce oaire serializer

- workflows/dags/data/data_harvest.py
- workflows/dags/literature/hep_create_dag.py
- workflows/plugins/include/utils/workflows.py
- workflows/tests/test_data_tasks.py
* ref: cern-sis/issues-inspire/issues/1059
> workflows: merge normalize_collaboration implementations

- workflows/dags/author/author_create/author_create_approved.py
- workflows/dags/author/author_create/author_create_init.py
- workflows/dags/author/author_create/author_create_rejected.py
- workflows/dags/author/author_update/author_update.py
- workflows/dags/cds/cds_harvest.py
- workflows/dags/cds/cds_rdm_harvest.py
- workflows/dags/data/data_harvest.py
- workflows/dags/literature/arxiv_harvest.py
- workflows/dags/literature/hep_create_dag.py
- workflows/dags/literature/ieee_harvest.py
* ref: cern-sis/issues-inspire/issues/1074
> workflows: fix warnings

- workflows/dags/author/author_create/author_create_init.py
- workflows/plugins/hooks/inspirehep/inspire_http_hook.py
- workflows/tests/test_author_tasks.py
* ref https://github.com/cern-sis/issues-inspire/issues/1095
> workflows: fix ticket urls for authors
