ui/src/common/components/__tests__/Suggester.test.jsx
We still can't use jest's fakeTimers because it doesn't work with
lodash.debounce. And we don't want to make `debounce`. Thus this
increases wait timeout by 20milisec to avoid random failures
=> ui: increase timer for Suggester unit tests

inspirehep/config.py, tests/integration/records/test_views.py
* Filters out buckets of author_count aggregation where doc_count = 0
so that it they don't show up on the UI leads users to empty searches.
JIRA:INSPIR-1983
=> search: do not return buckets with doc_count 0

ui/package.json, ui/src/App.scss, ui/src/actions/__tests__/search.test.js, ui/src/authors/containers/DetailPage.jsx, ui/src/common/__tests__/utils.test.js, ui/src/common/components/EmbeddedSearch.jsx, ui/src/common/components/SearchResults.jsx, ui/src/common/components/__tests__/SearchResults.test.jsx, ui/src/common/components/__tests__/__snapshots__/EmbeddedSearch.test.jsx.snap, ui/src/common/components/__tests__/__snapshots__/SearchResults.test.jsx.snap, ui/src/common/containers/ResultsContainer.jsx, ui/src/common/utils.js, ui/src/fixtures/store.js, ui/src/literature/components/LiteratureItem.jsx, ui/src/literature/components/__tests__/LiteratureItem.test.jsx, ui/src/literature/components/__tests__/__snapshots__/LiteratureItem.test.jsx.snap, ui/src/literature/containers/SearchPage.jsx
* Adds search rank for literature search results both on literature
search and author's literature, except small (phone) screens.
* Note that it uses native flexbox because antd's grid wraps Cols
without column size (span) and when it is set, it either takes extra
space for the searchRank unnecessarily and not guaranteed to work
properly for all screen sizes & title, rank lenght
* INSPIR-2062
=> ui: add search rank for literature results

ui/src/middlewares/__tests__/statePersister.test.js, ui/src/middlewares/statePersister.js, ui/src/reducers/index.js
* While rehydrating the reducer state from locatStroge, it combines
initialState of reducer too, in order to keep updates to initialData to
the persisted state in localStorage. Otherwise store would always use
persisted one directly and ignore initialState, therefore anything
we'll add to it.
=> ui: merge persisted state on top of initialState

inspirehep/records/api/base.py, inspirehep/records/errors.py, tests/integration/records/test_api_authors.py, tests/integration/records/test_api_base.py, tests/integration/records/test_api_conferences.py, tests/integration/records/test_api_data.py, tests/integration/records/test_api_experiments.py, tests/integration/records/test_api_institutions.py, tests/integration/records/test_api_jobs.py, tests/integration/records/test_api_journals.py, tests/integration/records/test_api_literature.py
* Check type of record when doing InspireRecord.create / create_or_update and get_record so that we use the proper subclass
* INSPIR-2210
=> records: record create based on pid type

inspirehep/config.py, inspirehep/records/indexer/base.py, inspirehep/search/factories/search.py, tests/helpers/compare.py, tests/integration/conftest.py, tests/integration/pidstore/minters/test_minters_arxiv.py, tests/integration/pidstore/minters/test_minters_control_number.py, tests/integration/pidstore/minters/test_minters_doi.py, tests/integration/pidstore/minters/test_minters_orcid.py, tests/integration/records/serializers/test_bibtex.py, tests/integration/records/serializers/test_json.py, tests/integration/records/serializers/test_latex.py, tests/integration/records/test_api_base.py, tests/integration/records/test_indexer.py, tests/integration/records/test_views.py, tests/integration/search/test_factories_search.py, tests/integration/submissions/test_submissions_views.py
* BREAKING: Renames ``create_record`` fixture factory to ``create_record_factory``.
* Creates ``create_record`` fixture to create records from the application level.
* Adds elastic search source based on the ``Content-Type``.
=> search: source based on the Content-Type

inspirehep/records/marshmallow/literature/common/conference_info_item.py, tests/integration/records/serializers/test_json.py, tests/unit/records/marshmallow/literature/common/test_conference_info_item.py, ui/src/common/components/PublicationInfo.jsx, ui/src/literature/components/ConferenceInfo.jsx, ui/src/literature/components/ConferenceInfoList.jsx, ui/src/literature/components/LiteratureItem.jsx, ui/src/literature/components/__tests__/ConferenceInfo.test.jsx, ui/src/literature/components/__tests__/ConferenceInfoList.test.jsx, ui/src/literature/components/__tests__/LiteratureItem.test.jsx, ui/src/literature/components/__tests__/__snapshots__/ConferenceInfo.test.jsx.snap, ui/src/literature/components/__tests__/__snapshots__/ConferenceInfoList.test.jsx.snap, ui/src/literature/components/__tests__/__snapshots__/LiteratureItem.test.jsx.snap, ui/src/literature/components/__tests__/utils.test.js, ui/src/literature/utils.js
* Fixed the conference info serializer to retrieve the conference record properly and return correct data
* Added page_start, page_end and acronyms to the serializer
* Added ConferenceInfo component to display conference as Contribution to {acronyms or title}, {start_page - end_page}
=> Display conference info

README.md, inspirehep/alembic/7be4c8b5c5e8_inspirehep_new_migrations.py, inspirehep/alembic_helper/db.py, inspirehep/alembic_helper/table_check.py, inspirehep/config.py, scripts/setup, setup.py, tests/integration-async/records/conftest.py, tests/integration/conftest.py, tests/integration/test_alembic.py
* ADD: Adds alembic to the project with all migrations which will bring all tables for inspirehep and tables for inspire-next because it's not possible to run migrations form inspirehep and inspire-next in the same db, ad both projects are using same modules and tables and this migrations won't work together.
* INSPIR-2213
=> alembic: add alembic to inspirehep

inspirehep/accounts/api.py, inspirehep/submissions/marshmallow/__init__.py, inspirehep/submissions/marshmallow/author.py, inspirehep/submissions/serializers.py, inspirehep/submissions/views.py, tests/helpers/factories/models/user_access_token.py, tests/integration/conftest.py, tests/integration/submissions/test_submissions_views.py, tests/unit/submissions/test_authors.py
When updating an author profile, it will not display hidden emails
unless logged in user who is updating is the author (matches user.orcid
and author.orcid)
=> submissions: restrict hidden email access

inspirehep/cli/indexer.py, tests/integration-async/records/indexer/test_indexer_cli.py
This commit removes from the query for reindexing the check for deleted record.
This is possible because `bulk_action` used by the `batch_reindex` task already
filters out deleted record when the metadata is loaded to be enhanced before reindexing.
* INSPIR-2353
=> cli: decrease query time for simpleindex command

inspirehep/records/api/base.py, inspirehep/records/api/data.py, inspirehep/records/api/literature.py, inspirehep/records/api/mixins.py, inspirehep/records/marshmallow/literature/base.py, inspirehep/records/marshmallow/literature/latex.py, inspirehep/search/api.py, tests/integration-async/records/indexer/test_literature.py, tests/integration/conftest.py, tests/integration/records/serializers/test_json.py, tests/integration/records/serializers/test_latex.py, tests/integration/records/test_api_base.py, tests/integration/records/test_api_conferences.py, tests/integration/records/test_api_data.py, tests/integration/records/test_api_experiments.py, tests/integration/records/test_api_institutions.py, tests/integration/records/test_api_jobs.py, tests/integration/records/test_api_journals.py, tests/integration/records/test_api_literature.py, tests/integration/records/test_views.py
* Add: get_citations_count method
* Add: citations_count property
* Fix: Latex serializer which were using get_citation_count method which was not in InspireRecord at all.
* INSPIR-2314
* INSPIR-2214
=> records: add citation count method and update serializers

inspirehep/records/marshmallow/literature/base.py
* FIX: correctly spell `citeable` in literature base schema, so it gets
serialized in the JSON response.
=> literature: output citeable in JSON serializer

ui/src/authors/containers/AuthorPublicationsContainer.jsx, ui/src/authors/containers/NumberOfCiteablePapersContainer.jsx, ui/src/authors/containers/NumberOfPublishedPapersContainer.jsx, ui/src/authors/containers/__tests__/AuthorPublicationsContainer.test.jsx, ui/src/common/components/CitationSummaryGraph/CitationSummaryGraph.jsx, ui/src/common/components/CitationSummaryGraph/index.js, ui/src/common/components/__tests__/CitationSummaryGraph.test.jsx, ui/src/common/components/__tests__/__snapshots__/CitationSummaryGraph.test.jsx.snap, ui/src/common/constants.js, ui/src/common/containers/CitationSummaryGraphContainer.jsx, ui/src/common/containers/__tests__/CitationSummaryGraphContainer.test.jsx, ui/src/common/containers/__tests__/__snapshots__/CitationSummaryGraphContainer.test.jsx.snap, ui/src/styleVariables.js
* Added interactivity to the citation summary graph
* On hover, the color darkens a bit. On click, it refetches author publications and facets and the other bars are grayed out
* INSPIR-2388
=> ui: Add citation summary graph interactivity

data/records/literature/1721418.json, docker-compose.services.yml, inspirehep/config.py, inspirehep/records/serializers/json.py, inspirehep/serializers.py, tests/integration/records/serializers/test_json.py, ui/src/authors/containers/AuthorPublicationsContainer.jsx, ui/src/authors/containers/__tests__/AuthorPublicationsContainer.test.jsx, ui/src/authors/containers/__tests__/__snapshots__/AuthorPublicationsContainer.test.jsx.snap, ui/src/common/components/EmbeddedSearch.jsx, ui/src/common/components/SelectBox.jsx, ui/src/common/components/SortBy.jsx, ui/src/common/components/__tests__/EmbeddedSearch.test.jsx, ui/src/common/components/__tests__/SortBy.test.jsx, ui/src/common/components/__tests__/__snapshots__/EmbeddedSearch.test.jsx.snap, ui/src/common/components/__tests__/__snapshots__/SortBy.test.jsx.snap, ui/src/common/containers/SortByContainer.jsx, ui/src/common/layouts/SearchLayout/SearchLayout.jsx, ui/src/common/layouts/SearchLayout/__tests__/SearchLayout.test.jsx, ui/src/common/layouts/SearchLayout/__tests__/__snapshots__/SearchLayout.test.jsx.snap, ui/src/common/propTypes.js, ui/src/reducers/__tests__/authors.test.js, ui/src/reducers/__tests__/search.test.js, ui/src/reducers/authors.js, ui/src/reducers/search.js
* Sort option now comes with search results and rendered on the UI
dynamically, so that we can avoid hardcoding them on the UI and
creating different SortBy for each collections since sort options
change by collection.
* Makes [web] and [worker] services "restart: always" to avoid crashing
due to syntax errors during development
* Fixes literature record in `data/records` which had duplicate pid
(arxiv)
=> search: server-side sort options

docker-compose.services.yml, inspirehep/accounts/api.py, inspirehep/accounts/fixtures.py, inspirehep/accounts/roles.py, inspirehep/config.py, inspirehep/migrator/views.py, inspirehep/search/api.py, inspirehep/search/utils.py, pyproject.toml, tests/integration/conftest.py, tests/integration/migrator/test_migrator_cli.py, tests/integration/migrator/test_migrator_view.py, tests/integration/records/serializers/test_json.py, tests/integration/records/serializers/test_json/955427.json, tests/integration/records/views/test_views_jobs.py, tests/integration/records/views/test_views_jobs/es_aggregations_cataloger_for_1735925.json, tests/integration/records/views/test_views_literature.py
This commit introduces a permission check for literature and jobs endpoints.
* ADD new Enum class calles Roles centralize the roles in Inspire;
* ADD new faces 'status' for job, if user is cataloger;
* REFACTOR all the superuser and cataloger permissions using Roles;
* INSPIR-2409
=> views: filter records and facets by permissions

ui/src/common/components/CitationSummaryGraph/CitationSummaryGraph.jsx, ui/src/common/components/CitationSummaryTable/CitationSummaryTable.jsx, ui/src/common/components/CitationSummaryTable/__tests__/__snapshots__/CitationSummaryTable.test.jsx.snap, ui/src/common/components/CitationsByYearGraph/CitationsByYearGraph.jsx, ui/src/common/components/CitationsByYearGraph/__tests__/CitationsByYearGraph.test.jsx, ui/src/common/components/CitationsByYearGraph/__tests__/__snapshots__/CitationsByYearGraph.test.jsx.snap, ui/src/common/components/__tests__/CitationSummaryGraph.test.jsx, ui/src/common/components/__tests__/__snapshots__/CitationSummaryGraph.test.jsx.snap
* Aligned the numbers for the citation summary graph based on the width of the container INSPIR-2441
* Changed the yAxis domain for the citation by year graph to start from 0
* Changed the yAxis for the citation by year graph to not have non-integer ticks
* Changed peer-review to peer review in the citation summary table INSPIR-2421
=> ui: Align numbers for citation summary graph

ui/package.json, ui/src/actions/search.js, ui/src/common/components/AggregationFilters.jsx, ui/src/common/components/__tests__/AggregationFilters.test.jsx, ui/src/common/components/__tests__/__snapshots__/AggregationFilters.test.jsx.snap, ui/src/jobs/containers/SearchLayout.jsx, ui/src/middlewares/__tests__/searchDispatcher.test.js, ui/src/middlewares/searchDispatcher.js, ui/yarn.lock
* Changed the location of calling the facets in the searchDispatcher so that it only calls facets for jobs the first time you go on jobs and it never calls facets for authors
* Added logic to not call facets when only page or sorting changed
* INSPIR-2468
=> Dropdown menus should stay unchanged for jobs page

ui/src/common/__tests__/utils.test.js, ui/src/common/components/CitationsByYearGraph/CitationsByYearGraph.jsx, ui/src/common/components/CitationsByYearGraph/__tests__/__snapshots__/CitationsByYearGraph.test.jsx.snap, ui/src/common/components/NumberOfResults.jsx, ui/src/common/components/RangeAggregation/RangeAggregation.jsx, ui/src/common/components/RangeAggregation/__tests__/__snapshots__/RangeAggregation.test.jsx.snap, ui/src/common/utils.js, ui/src/literature/components/LiteratureItem.jsx, ui/src/literature/components/NumberOfPages.jsx, ui/src/literature/components/__tests__/__snapshots__/LiteratureItem.test.jsx.snap
* Pluralizes `citations` conditionally
* Also uses new `pluralizeUnlessSingular` function for other use cases
* INSPIR-2444
=> ui: pluralize conditionally

ui/src/submissions/authors/containers/AuthorUpdateSubmissionPage.jsx, ui/src/submissions/jobs/containers/JobUpdateSubmissionPage.jsx
* Displays errors happens while fetchign update data for an update
submission form, and doesn't render empty form fields incase of error.
* Displays loading feedback instead of not rendering while fetching
update form data.
=> ui: display update form data fetch errors

tests/integration/conftest.py, tests/integration/migrator/test_migrator_cli.py
* Use a more elegant ``cli runner``.
* Mark flaky ``DEBUG=True`` with xfail, the are
blocking merging for the moment.
=> tests: migrator use more elegant cli runner

ui/src/App.scss, ui/src/common/components/CitationSummaryGraph/CitationSummaryGraph.jsx, ui/src/common/components/CitationSummaryGraph/CitationSummaryGraph.scss, ui/src/common/components/__tests__/__snapshots__/CitationSummaryGraph.test.jsx.snap
* Moved the citations label in the citation summary graph so it doesn't overlap
* INSPIR-2452
=> ui: Fix the citations label in the citation summary graph

inspirehep/migrator/cli.py, inspirehep/migrator/tasks.py, inspirehep/records/api/base.py, inspirehep/records/api/literature.py, tests/integration/migrator/test_migrator_cli.py, tests/integration/migrator/test_migrator_cli/1607957.xml, tests/integration/migrator/test_migrator_cli/1734025.xml, tests/integration/migrator/test_migrator_tasks.py, tests/integration/records/api/test_api_literature.py
* allow migrator to run different methods depending of parameters
* migrator now won't push to orcid
* migrator now won't index to early
* migrator now won't recallculate citations too early
* continous migration will migrate records in proper way, but it will still push to orcid
* Detach migrator from CLI command, so it will run independently
=>  migrator: Prepare migrator to properly migrate records

ui/src/actions/__tests__/authors.test.js, ui/src/actions/authors.js, ui/src/common/__tests__/utils.test.js, ui/src/common/components/CitationsByYearGraph/CitationsByYearGraph.jsx, ui/src/common/components/CitationsByYearGraph/__tests__/__snapshots__/CitationsByYearGraph.test.jsx.snap, ui/src/common/utils.js
* Reduces number of years display on the graph.
Now we set tickValues on the X axis explicitly for all conditions because tickTotal is
unreliable.
* Also makes fetchAuthorError redirectable so that it redirects to
error pages when request fails.
* INSPIR-2443
=> ui: fix citations by year grap x axis

inspirehep/migrator/tasks.py, inspirehep/records/api/base.py, inspirehep/records/indexer/base.py, inspirehep/records/indexer/tasks.py, inspirehep/records/indexer/utils.py, tests/integration/migrator/fixtures/dummy_deleted.xml, tests/integration/migrator/test_migrator_tasks.py, tests/integration/migrator/test_migrator_tasks/dummy_record.json, tests/integration/records/indexer/test_indexer_authors.py, tests/integration/records/indexer/test_indexer_authors/999108.json, tests/integration/records/indexer/test_indexer_authors/999108_expected.json, tests/integration/records/indexer/test_indexer_data.py, tests/integration/records/indexer/test_indexer_experiments.py, tests/integration/records/indexer/test_indexer_institutions.py, tests/integration/records/indexer/test_indexer_jobs.py, tests/integration/records/indexer/test_indexer_journals.py, tests/integration/records/indexer/test_indexer_literature.py
* Delete records from ES if it is marked as deleted
* Process references of records if migrator is not processing all records from mirror table
* Fix jobs and Authors to index properly
=> migrator/indexer: change how records are indexed

ui/src/common/__tests__/browser.test.js, ui/src/common/browser.js, ui/src/common/components/CitationSummaryGraph/CitationSummaryGraph.jsx, ui/src/common/utils.js
* `dominant-baseline` with `text-after-edge` value works differently on
Safari. That's why we needed to use a different value.
* INSPIR-2525
=> ui: fix citations summary graph label for Safari

inspirehep/records/marshmallow/literature/bibtex.py, inspirehep/records/serializers/bibtex.py, tests/unit/records/marshmallow/literature/test_bibtex_schema.py
* URLs are now hidden (what and when to show them needs more thought)
and report numbers are now shown for all entry types, unless they are
marked as hidden in the metadata.
=> bibtex: hide urls, change report numbers display

inspirehep/records/marshmallow/literature/base.py, tests/integration/records/views/test_views_literature.py, ui/src/literature/components/LiteratureDate.jsx, ui/src/literature/components/__tests__/__snapshots__/LiteratureDate.test.jsx.snap
earliest_date was not serialized as `date` on UI response because it
was accessed via `dict.get` while being a regular property on
`LiteratureRecord` class
This also moves date formatting for UI to frontend (where it belongs)
* INSPIR-2539
=> literature: fix earliest_date on ui serializer

inspirehep/migrator/tasks.py, inspirehep/records/api/literature.py, inspirehep/records/indexer/tasks.py, inspirehep/records/indexer/utils.py, tests/integration-async/conftest.py, tests/integration-async/migrator/test_migrator_tasks.py, tests/integration-async/records/indexer/test_literature.py, tests/integration/migrator/test_migrator_tasks.py, tests/integration/records/api/test_api_literature.py, tests/integration/records/indexer/test_indexer_literature.py
* Fix get_modified_references so it returns all references for just created records
* Make get_modified_references return list of uuids instead of list of pids
* Fix process_references which was throwing error whenever record didn't have modified references
* INSPIR-2477
=> citations: fix process records references

ui/src/common/components/SearchScopeSelect.jsx, ui/src/common/components/__tests__/SearchScopeSelect.test.jsx, ui/src/common/components/__tests__/__snapshots__/SearchBox.test.jsx.snap, ui/src/common/components/__tests__/__snapshots__/SearchScopeSelect.test.jsx.snap, ui/src/common/containers/SearchScopeSelectContainer.jsx, ui/src/common/containers/__tests__/GoBackLinkContainer.test.jsx, ui/src/common/containers/__tests__/PaginationContainer.test.jsx, ui/src/common/containers/__tests__/SearchBoxContainer.test.jsx, ui/src/common/containers/__tests__/SearchScopeSelectContainer.test.jsx, ui/src/common/containers/__tests__/SortByContainer.test.jsx, ui/src/submissions/jobs/components/StatusField.jsx, ui/src/submissions/jobs/components/__tests__/StatusField.test.jsx, ui/src/submissions/jobs/components/__tests__/__snapshots__/StatusField.test.jsx.snap, ui/src/submissions/jobs/containers/StatusFieldContainer.jsx
* fixes tests of small search components by droping usage of
`dispatchToProp` on the tests.
* Separates StatusFieldContainer into a container and a component.
Unfortunately container can't be tested because mounting `formik` stuff
is painful.
* INSPIR-2515
=> ui: fix leftovers from containers refactoring

inspirehep/records/marshmallow/literature/base.py, tests/integration/records/views/test_views_literature.py, ui/src/literature/components/LiteratureDate.jsx, ui/src/literature/components/LiteratureItem.jsx, ui/src/literature/components/__tests__/__snapshots__/LiteratureDate.test.jsx.snap, ui/src/literature/components/__tests__/__snapshots__/LiteratureItem.test.jsx.snap
* Moves back date formatting to backend where all the edge cases are
handled correctly
* Hides `()` that wraps date in search result if there is no date. This
isn't supposed to happen but it does due to some bugs.
=> literature: fix date formatting

inspirehep/migrator/tasks.py, inspirehep/records/api/literature.py, inspirehep/records/api/mixins.py, inspirehep/records/tasks.py, tests/integration/records/api/test_api_literature.py
* Fixes the bug caused by calling `update_refs_in_citation_table` on records different than LiteratureRecord.
* INSPIR-2563
=> migrator: rename update_refs_in_citation_table

inspirehep/records/api/literature.py, tests/integration-async/records/api/test_base.py, tests/integration-async/records/indexer/test_literature.py
* Reindexes all references for records when earliest_date of the record changes. This is needed to keep the citations_by_year of the references up-to-date.
=> citations: reindex references of records when earliest_date changes

ui/public/config.js, ui/public/index.html, ui/src/__tests__/tracker.test.js, ui/src/index.js, ui/src/tracker.js
Config variables such as SENTRY_DSN could be only set build time which
happens when we build an imagine with nginx and UI assets. This forced
us to create different images for QA and PROD.
Also it was not possible to change FEATURE_FLAGs (which we don't have
currently but plan to have) without rebuilding whole assets and the
imagine itself prior to deployment.
Note: This is the "MVP" as described in the task.
* INSPIR-2548
=> ui: inject config to window on serve time

inspirehep/records/config.py, tests/integration/records/serializers/test_json.py
* added created and updated to the source of the ES query because they were missing from the literature search with ui content-type 
* INSPIR-2582
=> serializers: add created and updated to the search with ui content type

Tiltfile
The current version of skaffold doesn't allow use to run kustomize v3 or on remote repositories.
Tilt is using the same code but is more flexible and let us run kustomize in a shell.
=> Use tilt for local dev.

backend/inspirehep/records/marshmallow/literature/bibtex.py, backend/inspirehep/records/serializers/bibtex.py, backend/tests/integration/orcid/cassettes/TestOrcidPushTask.test_push_new_work_already_existing.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPushTask.test_push_new_work_happy_flow.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPushTask.test_push_new_work_invalid_data_orcid.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherDuplicatedIdentifier.test_duplicated_external_identifier_pusher_exception.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherDuplicatedIdentifier.test_exc_in_apply_celery_task_with_retry.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherDuplicatedIdentifier.test_happy_flow_post.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherDuplicatedIdentifier.test_happy_flow_put.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_already_existing.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_already_existing_putcode_exception.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_already_existing_with_recids.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_happy_flow.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_invalid_data_orcid.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_invalid_data_token.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPutUpdatedWork.test_push_updated_work_happy_flow.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPutUpdatedWork.test_push_updated_work_invalid_data_orcid.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPutUpdatedWork.test_push_updated_work_invalid_data_putcode.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPutUpdatedWork.test_push_updated_work_invalid_data_token.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherRecordDBVersion.test_happy_flow.yaml, backend/tests/integration/orcid/conftest.py, backend/tests/integration/orcid/test_orcid_domain_models.py, backend/tests/integration/records/serializers/test_bibtex.py, backend/tests/unit/records/marshmallow/literature/test_bibtex_schema.py
* Authors and editors were not displayed in the BibTeX output
because the serializer was trying to read `authors` from the schema output,
where it was not present. This logic has now been moved to the
`BibTexCommonSchema`, so it can access the required data.
* INSPIR-2591
=> bibtex: display authors and editors

ui/src/middlewares/__tests__/searchDispatcher.test.js, ui/src/middlewares/searchDispatcher.js
* Implements more explicit way to detect if search actions should be
dispatched or not. Now they are always dispatched if it is page of one
of the collections without an id in the url.
* INSPIR-2627
=> ui: dispatch search even if location.search is empty

backend/inspirehep/records/api/literature.py, backend/tests/integration-async/records/api/__init__.py, backend/tests/integration-async/records/api/test_literature.py, backend/tests/integration-async/records/indexer/__init__.py
* phonetic blocks were not saved to db because we didn't have flag modified on record.model.json so this commit moves adding the phonetic blocks before the super update/create
* INSPIR-2616
=> disambiguation: Save record phonetic blocks to db

backend/inspirehep/migrator/config.py, backend/inspirehep/migrator/tasks.py, backend/tests/integration/migrator/test_migrator_tasks.py, backend/tests/unit/pidstore/api/test_pidstore_base.py
* Now a pid_type for continous migration can be blacklisted
* INSPIR-2666
=> migrator: make pid_types blacklistable

ui/src/common/__tests__/utils.test.js, ui/src/common/utils.js, ui/src/jobs/components/Contact.jsx, ui/src/jobs/components/ContactList.jsx, ui/src/jobs/components/__tests__/ContactList.test.jsx, ui/src/jobs/components/__tests__/__snapshots__/ContactList.test.jsx.snap, ui/src/submissions/jobs/components/JobForm.jsx
* Displays contacts with linked to their author page if they are linked.
* Makes contact.name autocomplete on job submission form in order to
link contacts to athor profile if submitter picks a suggested name.
INSPIR-2620
=> ui: display job contacts linked to author page

ui/src/submissions/common/components/SuggesterField.jsx
SuggesterField was populating `record`, when a suggestion is selected by
using the `self` field in the selected suggestion. But `self` is
deprecated and doesn't exist in some collections such as `authors`. So
now it is using `control_number` and generating the `$ref` url on the
UI side as a quick fix.
=> ui: stop using `self` in suggerter field

ui/src/jobs/components/SubscribeJobsModalButton.jsx, ui/src/jobs/components/__tests__/SubscribeJobsModalButton.test.jsx, ui/src/jobs/components/__tests__/__snapshots__/SubscribeJobsModalButton.test.jsx.snap
Clears the confirmation state for job mails subscription, so that when
subscription modal opened again, it show the form instead of the
confirmation.
=> ui: clear job mails subscription confirmation

backend/inspirehep/disambiguation/utils.py, backend/tests/integration/disambiguation/test_utils.py
* Also avoids unnecessary touching the record, resulting in a new DB
version, if there is no modification because the linked author is the
same as previously.
=> disambiguation: don't touch curated signatures

ui/src/submissions/literature/schemas/constants.js
* INSPIR-2657
There was a validation error caused by a typo in one of the categories in the dropdown
=> ui: fix typo in subject options in literature form

backend/inspirehep/submissions/marshmallow/literature.py, backend/tests/unit/submissions/test_literature.py, e2e/tests/submissions/literature.test.js, ui/src/submissions/literature/schemas/constants.js
* Adds missing INSPIRE categories
* Ignores English language (it's the default, shouldn't usually be present in records)
=> Fix two bugs in literature form

backend/inspirehep/records/indexer/tasks.py, backend/inspirehep/records/indexer/utils.py, backend/tests/integration/records/indexer/test_indexer_literature.py, backend/tests/unit/records/indexer/test_base.py, backend/tests/unit/records/indexer/test_index_record.py
* Adds an auto retry when one of sqlalchemy connection issue Exceptions are thrown
* fixes unit.records.indexer.base tests as they were never executed
INSPIR-2686
=> indexer: Retry indexer after db connection issue

backend/inspirehep/records/config.py, backend/inspirehep/records/marshmallow/literature/es.py, backend/tests/integration/records/views/test_views_literature.py, ui/src/common/components/AggregationFilters.jsx, ui/src/common/components/CheckboxAggregation.jsx, ui/src/common/components/__tests__/AggregationFilters.test.jsx, ui/src/common/components/__tests__/CheckboxAggregation.test.jsx, ui/src/common/components/__tests__/__snapshots__/AggregationFilters.test.jsx.snap, ui/src/common/components/__tests__/__snapshots__/CheckboxAggregation.test.jsx.snap, ui/ui-tests/server.js
* INSPIR-2363
Note: server.js has been modified since the previous default values are not being read at the time of generating the recordings for the UI tests. The url and http schema have to be set via environmental variables.
=> facets: rename peer reviewed to published

e2e/tests/submissions/job.test.js, ui/src/submissions/common/components/RichTextEditor/RichTextEditor.jsx
Quill's default tag after the line break is `p` which has overriden
style inside quill editor, no bottom margin 1em which is a web default
and exist everywhere including job detail page. Since we don't want to
break a web standard by removing margin for `p` inside job description,
this PR changes `P` tag to `DIV` instead, which has consistent
behaviour everywhere.
Note that adding margin back to P tag for Quill instead of changing whole
tag, has a limitation. It doesn't allow linebreaks without spaces.
* INSPIR-2799
=> ui: change rich text editor's text block tag.

backend/inspirehep/config.py, backend/inspirehep/logger/config.py, backend/inspirehep/pidstore/api/base.py, backend/inspirehep/pidstore/minters/base.py, backend/inspirehep/pidstore/providers/recid.py
* This causes all logging in the application to go through structlog and
be rendered as JSON.
Example output:
```json
{"event": "Received task: inspirehep.migrator.tasks.migrate_recids_from_mirror[79ca42a8-60fc-41d5-ab93-6ee5aa0d8265]  ", "logger": "celery.worker.strategy", "level": "info", "timestamp": "2019-11-15T15:32:03.517783Z", "sentry": "skipped"}
{"task_id": "79ca42a8-60fc-41d5-ab93-6ee5aa0d8265", "task": "inspirehep.migrator.tasks.migrate_recids_from_mirror", "event": "Task inspirehep.migrator.tasks.migrate_recids_from_mirror[79ca42a8-60fc-41d5-ab93-6ee5aa0d8265] succeeded in 0.000743832002626732s: None", "logger": "celery.app.trace", "level": "info", "timestamp": "2019-11-15T15:32:03.519666Z", "sentry": "skipped"}
{"event": "Received task: …
```
=> logger: emit JSON also for stdlib logging

backend/inspirehep/pidstore/converters.py, backend/inspirehep/pidstore/minters/doi.py, backend/inspirehep/records/config.py, backend/setup.py, backend/tests/integration-async/records/api/test_base.py, backend/tests/integration/pidstore/minters/test_minters_doi.py, backend/tests/integration/pidstore/test_pidstore_api_base.py
* This commit requires to remove dois from pidstore and records migration. See: [INSPIR-2925](https://its.cern.ch/jira/browse/INSPIR-2925)
* INSPIR-2822
=> pidstore: make doi case insensitive

backend/inspirehep/access_control.py, backend/inspirehep/accounts/decorators.py, backend/inspirehep/records/config.py, backend/tests/integration/accounts/test_decorators.py, backend/tests/integration/records/views/test_views_conferences.py
* PUT is only allowed if request has session of a cataloger.
* Also fixes login_required_with_roles to return `403` when user is
logged in but do not have access for the resource.
INSPIR-2854
=> conferences: auth update view via session

backend/tests/conftest.py, backend/tests/helpers/cleanups.py, backend/tests/integration-async/conftest.py, backend/tests/integration/alembic/test_alembic.py, backend/tests/integration/conftest.py
* don't remove indexes from ES only remove data
* There is ES error on version 5, when you try to remove records using delete_by_query and record have external visioning and it's current version is 0 it's failing. So in this case only way is to remove index. invenio 1.1.1 allows to remove all indexes only. After upgrading to invenio 1.2 we will be able to remove only specified index
=> tests: don't remove all tables, just remove content

backend/tests/integration-async/conftest.py
* Fix for old error which was making async tests to fail randomly
=> tests: ressult not assigned error fix

.travis.yml
* this should speedup travis tests by ~5 minutes on every PR and on every merge to master except first run on every branch.
=> travis: enable caching for poetry virtualenv

backend/inspirehep/records/config.py, backend/inspirehep/records/marshmallow/conferences/common/proceeding_info_item.py, backend/tests/unit/records/marshmallow/conferences/common/test_proceeding_info_item.py, backend/tests/unit/records/marshmallow/conferences/test_base.py, ui/src/actions/conferences.js, ui/src/conferences/components/ProceedingsAction.jsx, ui/src/conferences/components/__tests__/ProceedingsAction.test.jsx, ui/src/conferences/components/__tests__/__snapshots__/ProceedingsAction.test.jsx.snap
* Fix bugs related to conferences ordering, using ui headers for conference detail call and sending control number in the proceedings
* INSPIR-2938, INSPIR-2947, INSPIR-2942
=> conferences: fix bugs

backend/inspirehep/records/marshmallow/conferences/base.py, backend/inspirehep/serializers.py, backend/tests/integration/records/serializers/json/test_conferences.py, backend/tests/integration/records/serializers/json/test_literature.py
* This fixes missing properties from serializers because we were getting a dict before
* INSPIR-2946
=> serializers: use actual record in metadata for serializers

ui/src/submissions/conferences/components/ConferencesExistOnDatesAlert.jsx, ui/src/submissions/conferences/containers/ConferenceSubmissionSuccessPageContainer.jsx, ui/src/submissions/conferences/containers/__tests__/ConferenceSubmissionSuccessPageContainer.test.jsx, ui/src/submissions/conferences/containers/__tests__/__snapshots__/ConferenceSubmissionSuccessPageContainer.test.jsx.snap, ui/src/submissions/conferences/schemas/constants.js
Conferences exist on selected dates alert, includes `start_date=all` in
the search link in order to override default `upcoming`
=> conference submission bugs

ui/src/conferences/components/ConferenceSeries.jsx, ui/src/conferences/components/__tests__/__snapshots__/ConferenceSeries.test.jsx.snap
Link to conference series search in conferece detail pages is fixed to
search in all comforerences, not only upcoming.
=> ui: fix conference series search link

backend/inspirehep/config.py, backend/tests/integration/test_celery.py
* Tasks having `acks_late` set to true automatically retry when they are
interrupted due to a worker crash. However, this doesn't happen by
default when the worker is killed, unless `reject_on_worker_lost` is
also set to true. To ensure this is always the case, this commit uses
the Celery task annotations machinery to automatically annotate tasks
having the former option with the latter.
Note that this won't solve the issue when a task in the head of the chord fails until https://github.com/celery/celery/pull/5700 gets released.
=> celery: don't fail acks_late tasks on worker crash

backend/inspirehep/pidstore/converters.py, backend/inspirehep/pidstore/resolvers.py, backend/inspirehep/records/config.py, backend/setup.py, backend/tests/integration/records/views/test_views.py
Now superuser and catalogers can display records that are marked
`deleted: true`.
* INSPIR-3068
=> pid: return deleted pids if authorized

backend/inspirehep/search/facets.py, backend/inspirehep/search/utils.py
* Scripted aggregations now use built-in methods where possible and are
written on several lines for better readability.
=> search: refactor scripted aggregations

ui/src/literature/components/CitationSummaryBox.jsx, ui/src/literature/components/__tests__/CitationSummaryBox.test.jsx, ui/src/literature/containers/CitationSummaryBoxContainer.jsx, ui/src/literature/containers/__tests__/CitationSummaryBoxContainer.test.jsx
CitationSummaryBoxContainer keeps getting rerendering for some reason
(it will be investigated further) when user is logged in. This
rerendering was triggering endless fetch loop.
=> ui: hot fix for lit citation summary bug

ui/src/actions/__tests__/router.test.js, ui/src/actions/__tests__/search.test.js, ui/src/actions/router.js, ui/src/actions/search.js, ui/src/literature/containers/CitationSummarySwitchContainer.jsx, ui/src/literature/containers/LiteratureSearchContainer.jsx, ui/src/literature/containers/__tests__/CitationSummarySwitchContainer.test.jsx
Since we use location.search strictly for search query in search pages,
using location.hash was the only solution. Otherwise it would mess up
search code unnecessarily too much.
INSPIR-3124
=> ui: move citation summary visibility state to url

backend/inspirehep/files/api/s3.py, backend/inspirehep/records/api/literature.py, backend/inspirehep/records/config.py, backend/inspirehep/records/utils.py, backend/tests/integration/files/test_api_s3.py, backend/tests/integration/migrator/cassettes/test_migrate_record_from_mirror_invalidates_local_file_cache_if_no_local_file.yaml, backend/tests/integration/migrator/test_migrator_tasks.py, backend/tests/integration/records/api/cassettes/test_adding_record_with_documents_with_full_url_without_original_url.yaml, backend/tests/integration/records/api/test_api_literature.py
* Populate original_url with url only if it is not already populated and if it url is not an s3 url and the url is not relative
* Populating the original_url is used in the afs cache in the migration
=> files: change the original_url logic 

build-and-deploy.sh, ui/Dockerfile
* explicitly create sentry releases
* use the current images as docker build cache
=> Travis deploy changes

backend/inspirehep/migrator/tasks.py, backend/inspirehep/migrator/utils.py, backend/tests/integration/migrator/test_migrator_tasks.py
* handle DownloadFileError in the migration so that if the error is not caused by invalid cache and not being able to download local file, the error will be logged properly (instead of throwing hdel is not receiving all arguments) and the error will be on the mirror record too
=> files: properly handle DownloadFileError in migration

ui/package.json, ui/src/App.jsx, ui/src/__tests__/App.test.jsx, ui/src/authors/index.jsx, ui/src/common/VerticalDivider/VerticalDivider.scss, ui/src/conferences/index.jsx, ui/src/jobs/index.jsx, ui/src/literature/index.jsx, ui/src/submissions/index.jsx, ui/yarn.lock
Does not split code into chunks, based on routes anymore. Since this
ends up a lot of dependencies duplicated in multiple bundles. Although
in theory this increases size of assets that need to be downloaded
to render a route, in practice, our preloading strategy does not work
as inteded so browsers ends up downloading most of assets for a route.
So for now admin route and submissions routes are async, others are
not. And there is no preloading as of now, but planned to be introduce
in the future.
(Also adds `yarn analyze` to see report for generated bundle by `yarn
build`)
INSPIR-3232
=> ui: improve initial assets load speed

backend/inspirehep/submissions/marshmallow/literature.py, backend/tests/integration/submissions/test_submissions_views.py
* serialize `pdf_url` into `urls`
* skip arxiv urls
* INSPIR-3322
=> submission: fix serialization for literature submission forms

backend/tests/integration-async/conftest.py, backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py, backend/tests/integration-async/records/indexer/test_authors.py, backend/tests/integration-async/records/indexer/test_conferences.py, backend/tests/integration-async/records/indexer/test_literature.py, backend/tests/integration-async/test_test_utils.py
Refactored most flaky test 'test_indexer_updates_authors_papers_when_name_changes' which was causing 60% of failures il last week.
Other tests also updated and refactored to be more stable.
`retry_until_matched` tool for tests refactored and updated to be more reliable and to return meaningful exceptions.
Added tests for `retry_until_matched` tool
*INSPIR-3313
=> integration-async: improve flaky tests

ui/src/actions/citations.js, ui/src/middlewares/keepPreviousUrl.js, ui/src/reducers/__tests__/search.test.js, ui/src/reducers/search.js
This one only removes the `fetchCitationSummary(emptySearchQuery)`,
there are still other bugs hence the request action is dispatched more
than once.
This only buys us time to fix citation summary issues, and possibly
together with other issues with dispatching fetch requests
INSPIR-3393
=> ui: hotfix multiple citation summary requests

backend/tests/integration/submissions/test_submissions_views.py
* fixes test which was making change to global dict in test,
if it was running before others which was using same global dict others tests were failing.
=> tests: fix flaky test

backend/inspirehep/submissions/errors.py, backend/inspirehep/submissions/loaders.py, backend/inspirehep/submissions/views.py, backend/tests/integration/submissions/test_submissions_views.py
* Returns ```LoaderDataError``` when there is something wrong
while loading the data.
* Refactors the submissions to use loaders instead of
custom calls.
* Reduces the duplicated code.
* INSPIR-3402
=> submissions: handle unexpected errors

ui/src/common/components/SearchScopeSelect.jsx, ui/src/reducers/search.js
Goes back to hiding beta collections in ui component level (SearchScopeSelect)
=> ui: fix search-history for beta collections

backend/inspirehep/alembic/8ba47044154a_add_indexed_to_records_citations_on_is_.py, backend/inspirehep/records/api/mixins.py, backend/inspirehep/records/models.py, backend/tests/integration/alembic/test_alembic.py, backend/tests/unit/records/indexer/test_base.py
*Added indexes for is_self_citation column in records_citations table
*Fix: When feature flag for self-citations is disabled, ignore self-citations queries to speedup migration.
*Removed unnecessary flag from _citations_by_year method
=> self-citations: quick update for self-citations

backend/poetry.lock, backend/pyproject.toml, backend/tests/integration/orcid/cassettes/TestOrcidPushTask.test_push_new_work_already_existing.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPushTask.test_push_new_work_happy_flow.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPushTask.test_push_new_work_invalid_data_orcid.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherDeleteWork.test_delete_work_cache_hit.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherDeleteWork.test_delete_work_cache_miss.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherDeleteWork.test_delete_work_cache_putcode_nonexisting.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherDeleteWork.test_delete_work_force_delete.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherDeleteWork.test_delete_work_invalid_token.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherDuplicatedIdentifier.test_happy_flow_post.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherDuplicatedIdentifier.test_happy_flow_put.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherDuplicatedIdentifier.test_push_unhandled_duplicated_external_identifier_pusher_exception.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_already_existing.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_already_existing_and_delete_duplicated_records_different_putcodes.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_already_existing_duplicated_external_identifier_exception.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_already_existing_with_recids.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_happy_flow.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_invalid_data_orcid.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_invalid_data_token.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPostNewWork.test_push_new_work_invalid_data_xml.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPutUpdatedWork.test_push_updated_work_happy_flow.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPutUpdatedWork.test_push_updated_work_invalid_data_orcid.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPutUpdatedWork.test_push_updated_work_invalid_data_putcode.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPutUpdatedWork.test_push_updated_work_invalid_data_token.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherPutUpdatedWork.test_push_updated_work_no_cache.yaml, backend/tests/integration/orcid/cassettes/TestOrcidPusherRecordDBVersion.test_happy_flow.yaml, backend/tests/integration/orcid/test_orcid_converter.py, backend/tests/integration/orcid/test_orcid_domain_models.py
* upgrade orcid tests which were failing because of switch to newer version (different canonicalisation method was used since 4.4.)
* makes inspire compatibile with inspire-utils
* INSPIR-3477
=> setup: upgrade lxml

backend/inspirehep/accounts/config.py, backend/inspirehep/accounts/views.py, backend/tests/integration/accounts/test_views.py, ui/src/user/components/LoginPage/LoginPage.jsx, ui/src/user/components/LoginPage/__tests__/__snapshots__/LoginPage.test.jsx.snap
* Fix for INSPIR-3349
The problem is that the session is reset on rare occasions probably due to some issues with Redis, so in that situation a KeyError was being thrown when reading `next_url` and `signup_url` from session.
=> login: fix orcid login session issues

ui/src/submissions/common/components/SuggesterField.jsx
Previous code was working around an issue on antd side
since select was called before change. But now that seems to be fixed
and this created a bug on our side, since it required onChange to triggered twice
to be able to clear the `record` field which was set by the previous selection
=> ui: fix suggester field's change after selection bug

ui/src/actions/__tests__/authors.test.js, ui/src/actions/__tests__/citations.test.js, ui/src/actions/__tests__/conferences.test.js, ui/src/actions/__tests__/exceptions.test.js, ui/src/actions/__tests__/experiments.test.js, ui/src/actions/__tests__/inspect.test.js, ui/src/actions/__tests__/institutions.test.js, ui/src/actions/__tests__/jobs.test.js, ui/src/actions/__tests__/literature.test.js, ui/src/actions/__tests__/search.test.js, ui/src/actions/__tests__/seminars.test.js, ui/src/actions/__tests__/submissions.test.js, ui/src/actions/__tests__/user.test.js, ui/src/actions/authors.js, ui/src/actions/citations.js, ui/src/actions/conferences.js, ui/src/actions/experiments.js, ui/src/actions/institutions.js, ui/src/actions/jobs.js, ui/src/actions/literature.js, ui/src/actions/search.js, ui/src/actions/seminars.js, ui/src/common/components/__tests__/Suggester.test.jsx, ui/src/common/http.js, ui/src/literature/__tests__/citeArticle.test.js, ui/src/literature/components/__tests__/CiteAllAction.test.jsx, ui/src/submissions/authors/schemas/__tests__/unqiueOrcid.test.jsx
Adds a wrapper around http client that initially handles `get` requests.
This fixes problems with inconsistent ui especially when user on a
slow network, also avoid unnecessary downlaods.
Example problem:
1. Click on an author on literature page
2. Go back to literature page before citation summary of the author is loaded
This will trigger another citation summary request and
now there will be 2 active citation summary requests.
It will display wrong results if for some reason earlier request
finishes the last.
=> ui: cancel unncessary http requests

backend/inspirehep/serializers.py, backend/tests/integration/records/serializers/json/test_authors.py
=> serializers: do not display search_options on non ui requests

ui/src/common/components/SearchBox/searchHistory.js, ui/src/common/storage.js, ui/src/middlewares/__tests__/statePersister.test.js, ui/src/middlewares/statePersister.js
This is prior work before we move to IndexedDB or some wrapper like
`localForage`.
Current blocker is rehydration of redux state async, requires more work
and can wait until we really needed.
=> ui: separate storage

backend/inspirehep/migrator/tasks.py, backend/inspirehep/pidstore/api/base.py, backend/inspirehep/pidstore/minters/bai.py, backend/inspirehep/pidstore/minters/base.py, backend/inspirehep/pidstore/minters/cnum.py, backend/inspirehep/pidstore/minters/orcid.py, backend/inspirehep/pidstore/providers/cnum.py, backend/inspirehep/pidstore/providers/external.py, backend/tests/helpers/providers/record_provider.py, backend/tests/integration/pidstore/minters/test_minters_arxiv.py, backend/tests/integration/pidstore/minters/test_minters_bai.py, backend/tests/integration/pidstore/minters/test_minters_cnum.py, backend/tests/integration/pidstore/minters/test_minters_control_number.py, backend/tests/integration/pidstore/minters/test_minters_doi.py, backend/tests/integration/pidstore/minters/test_minters_orcid.py
* Additionally fix cnum provider when creating cnum from data provided.
* Fix ORCID generator in tests
* INSPIR-3641
=> pidstore: do not delete all external pids when it's unecessary

backend/inspirehep/records/marshmallow/literature/bibtex.py, backend/inspirehep/records/marshmallow/literature/latex.py, backend/inspirehep/records/marshmallow/literature/utils.py, backend/inspirehep/records/serializers/bibtex.py, backend/inspirehep/records/serializers/latex.py, backend/inspirehep/records/serializers/templates/latex_template.tex, backend/poetry.lock, backend/pyproject.toml, backend/tests/integration/records/serializers/test_bibtex.py, backend/tests/integration/records/serializers/test_latex.py, backend/tests/unit/records/marshmallow/literature/test_bibtex_schema.py, backend/tests/unit/records/marshmallow/literature/test_latex_schema.py, backend/tests/unit/records/marshmallow/literature/test_literature_marshmallow_utils.py
* Moves the encoding from the serializers to the marshmallow schemas,
which allows to selectively encode only some fields and avoid encoding
others (e.g. DOI).
* Also adds encoding to LaTeX US/EU formats, previously only BibTeX was
handled.
* Pins `pylatexenc` to get the bugfix for https://github.com/phfaist/pylatexenc/issues/44 reported by @tsgit (not released yet)
=> Improve latex escaping

ui/src/common/components/Suggester.jsx, ui/src/common/components/__tests__/Suggester.test.jsx, ui/src/common/components/__tests__/__snapshots__/Suggester.test.jsx.snap, ui/src/submissions/common/components/SuggesterField.jsx
* Moves core logic from SuggesterField to Suggester
which now provides a simpler API.
* Fixes bug #1219, also for all suggester fields
* Adds id for suggester requests so that unncessary requests are
cancelled
=> ui: refactor core suggester and the form field

smoke-tests/cypress/support/commands/visual.js
=> cypress: use smaller failure treshold for visual tests

backend/inspirehep/records/config.py, ui/src/common/components/Suggester.jsx, ui/src/common/components/__tests__/Suggester.test.jsx, ui/src/submissions/common/components/SuggesterField.jsx, ui/src/submissions/seminars/components/SeminarForm.jsx
* Fixes suggerter form field bug when there is no custom item completion value
* Calls suggester onSelect only when there is affilated record link to be autocompleted
* Reduces seminar suggester payload to only `control_number` instead of whole record
=> suggesters: fix series suggesters

backend/inspirehep/submissions/marshmallow/literature.py, backend/tests/integration/submissions/test_submissions_views.py, smoke-tests/cypress/integration/literature.test.js
Save proceeding and conference info in `_private_notes` field for literature submission.
Ref: #1430
=> submission: save proceeding and conference info in private_notes

.circleci/config.yml, cypress-tests-run.sh
Container logs wasn't uploaded when tests failed
=> cypress: fix container logs on CI

backend/inspirehep/matcher/tasks.py, backend/tests/integration/matcher/test_tasks.py
Because some records might be deleted after uuids are passed
to the task.
Ref: #1489.
=> matcher: (double) ignore delete records

backend/inspirehep/pidstore/minters/base.py, backend/inspirehep/pidstore/minters/cnum.py, backend/inspirehep/pidstore/minters/texkey.py, backend/inspirehep/pidstore/providers/external.py, backend/inspirehep/pidstore/providers/texkey.py, backend/inspirehep/records/api/base.py
* When querying for `object_uuid` on the pidstore, it's important to
also query on `object_type="rec"`, otherwise the index won't be used,
and queries will be much slower than necessary. This is the case in
the migration, where 20% of the time is spent in the
`Minter.get_all_pidstore_pids` method due to this issue. So I searched
for all occurrences of `object_uuid` and fixed the wrong ones.
=> pidstore: make queries faster by using an index

backend/inspirehep/matcher/tasks.py, backend/inspirehep/migrator/tasks.py
* Also fixes private import from `psycopg2` to use public name.
* Ref #1550.
=> matcher: retry reference matching on ES errors

backend/inspirehep/assign/views.py, backend/inspirehep/disambiguation/tasks.py, backend/inspirehep/disambiguation/utils.py, backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py, backend/tests/integration/disambiguation/test_utils.py
* solves bug with assigning already existing pid to newly created authors
=> disambiguation: pass authors data directly to create_new_author

backend/inspirehep/orcid/domain_models.py
* This was caused by passing the current record version when trying to
push a different record, which in general won't match. The fix is not
to pass any version (which is ok, as the versioning checks is there
only to avoid reading stale data from the DB in case the task is fired
before the update gets commited).
* Ref #1570.
=> orcid: fix StaleRecordDBVersion exception

backend/inspirehep/search/aggregations.py, backend/tests/integration/records/views/test_views_literature.py, backend/tests/integration/search/test_aggregations.py
All the metadata of the records has been modified to conform to the new
way of indicating RPP, so we can remove the old way.
=> search: exclude RPP based on flag-only

.github/workflows/integration.yml, backend/Dockerfile, backend/pyproject.toml
* Also makes the Github CI cache depend on `Dockerfile` and
`pyproject.toml` to avoid incorrect caching as happened during the
Python 3.6 to 3.8 transition.
* Ref #1849.
=> poetry: update to v1.1.6

record-editor/src/app/shared/config/authors.config.ts
`record` field removed from always show since some positions might have no record reference.
Ref: #2025
=> record-editor: fix for loading author record issue.

backend/inspirehep/oai/serializers.py, backend/poetry.lock, backend/pyproject.toml, backend/tests/integration-async/oai/test_views.py
* workaround for
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=994998
* updates lxml to use wheel which doesn't seem to have the issue
* avoids serialization/deserialization to a string in the serializer by
keeping the MARCXML as a tree
=> oai: avoid abstract truncation

ui/src/authors/components/PublicationsSelect.jsx, ui/src/authors/components/__tests__/PublicationsSelect.test.jsx, ui/src/authors/components/__tests__/__snapshots__/PublicationsSelect.test.jsx.snap, ui/src/authors/containers/PublicationSelectContainer.jsx, ui/src/authors/containers/__tests__/PublicationSelectContainer.test.jsx, ui/src/authors/containers/__tests__/__snapshots__/PublicationSelectContainer.test.jsx.snap
* 'select all' checkbox in authors didn't highlight selected papers checkboxes because of missing checked prop. Added missing prop to PublicationsSelect component
* ref: cern-sis/issues-inspire#16
=> ui: bug in select all checkbox in authors

ui/src/authors/components/AssignAction.jsx, ui/src/authors/components/AssignOwnProfileAction.jsx, ui/src/authors/components/__tests__/__snapshots__/AssignAction.test.jsx.snap, ui/src/authors/components/__tests__/__snapshots__/AssignOwnProfileAction.test.jsx.snap, ui/src/authors/containers/AssignAllActionContainer.jsx, ui/src/authors/containers/AssignAllOwnProfileActionContainer.jsx
* on single paper claiming change plural version label and tooltip to singular
* ref: cern-sis/issues-inspire#55
=> ui: fix for always plural version of label and tooltip

backend/inspirehep/disambiguation/tasks.py, backend/inspirehep/records/api/literature.py, backend/tests/integration-async/disambiguation/test_disambiguation_tasks.py
* don't run disambiguation for deleted records instead of handling it with `NoResultFound` exception
=> disambiguation: improve logging & retry

.github/workflows/release.yml
* fix the release workflow:
* action `softprops/action-gh-release@v1` by default uses `tag_name` equal to [`github.ref`](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) where `github.ref` seems not to be a tag for the event [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) which is triggering workflow - instead, tag name is in the `github.event.inputs.tag` field
=> release workflow: fix release step to use a correct tag name

backend/inspirehep/disambiguation/cli.py, backend/tests/integration-async/disambiguation/test_disambiguation_cli.py
* reduces group size for celery tasks since all the tasks in a group are applied in parallel
* sends tasks to the default queue in order to keep track of group tasks & disambiguation tasks better (now they end up in the same queue which is confusing)
=> disambiguation cli: reduce group size for celery task & put group tasks in default queue

.github/workflows/integration.yml, e2e/cypress/support/index.js
* use Firefox v.99 for e2e tests
* ref: https://github.com/cern-sis/issues-inspire/issues/85
=> e2e: add firefox e2e test back to workflow

e2e/cypress/support/index.js, ui/package.json, ui/src/common/layouts/Header/Header.jsx, ui/src/common/layouts/Header/Header.less, ui/src/common/layouts/Header/__tests__/__snapshots__/Header.test.jsx.snap, ui/src/index.js, ui/yarn.lock
- remove use-resize-observer hook and use css instead
- ignore resize observer error in Sentry (as suggested [here](https://stackoverflow.com/questions/65732703/resizeobserver-loop-limit-exceeded-stop-exception))
* ref: cern-sis/issues-inspire#197
=> ui: remove unnecesary use-resize-observer hook

ui/src/authors/containers/DetailPageContainer/DetailPageContainer.tsx
* restoring  lazy render after clicking on tabs in order to trigger fetching search aggregations 
* ref: cern-sis/issues-inspire#187
=> ui: remove force render parameter to trigger fetching searchAggregations

ui/src/actions/__tests__/search.test.js, ui/src/actions/search.ts, ui/src/literature/containers/SearchPageContainer.jsx, ui/src/literature/index.less
* ref: cern-sis/issues-inspire#189
=> ui: gracefully handle search queries

ui/src/errors/components/Error401.jsx, ui/src/errors/components/Error404.jsx, ui/src/errors/components/Error500.jsx, ui/src/errors/components/ErrorAppCrash.jsx, ui/src/errors/components/ErrorPage.jsx, ui/src/errors/components/__tests__/__snapshots__/Error401.test.jsx.snap, ui/src/errors/components/__tests__/__snapshots__/Error404.test.jsx.snap, ui/src/errors/components/__tests__/__snapshots__/Error500.test.jsx.snap, ui/src/errors/components/__tests__/__snapshots__/ErrorAppCrash.test.jsx.snap, ui/src/middlewares/__tests__/redirectToErrorPage.test.js, ui/src/middlewares/redirectToErrorPage.js
* add error causing url to history and display it on error error pages
* ref: cern-sis/issues-inspire#196
=> ui: keep error causing url in history

ui/src/jobs/components/SubscribeJobsForm.jsx, ui/src/jobs/components/__tests__/__snapshots__/SubscribeJobsForm.test.jsx.snap, ui/src/user/components/SignUpPage.tsx, ui/src/user/components/SingUpForm.tsx, ui/src/user/components/__tests__/__snapshots__/SignUpPage.test.tsx.snap, ui/src/user/components/__tests__/__snapshots__/SingUpForm.test.tsx.snap, ui/src/user/containers/__tests__/SignUpPageContainer.test.tsx
* ref: cern-sis/issues-inspire#284
The issue was wrong prop name passed to signup component. Additionally fixed input loosing focus after first letter was typed in signup form as well as in jobs subscribe form.
=> ui: fix for error in signup form

record-editor/src/app/shared/config/authors.config.ts, record-editor/src/app/shared/config/experiments.config.ts, record-editor/src/app/shared/config/hep/core.config.ts, record-editor/src/app/shared/config/index.ts, record-editor/src/app/shared/config/institutions.config.ts, record-editor/src/app/shared/config/journals.config.ts
* Adds config for conferences, experiments, journals
* Changes all schemas to make more ref fields editable
* Closes cern-sis/issues-inspire#15 and closes cern-sis/issues-inspire#62
=> Configure record editor for all collections

backend/poetry.lock, backend/pyproject.toml, docker/jupyter/hep_requirements.txt
* also removes `psycopg2` dep as `psycopg2-binary` now provides wheels for ARM macs.
=> poetry: bump inspire-schemas to v61.5.17

ui/src/common/constants.ts
Closes https://github.com/cern-sis/issues-inspire/issues/400. The issue happens in `RecordUpdateInfo.jsx` because the `LOCAL_TIMEZONE` which is calculated in `common/constants.js` with `Intl.DateTimeFormat().resolvedOptions().timeZone` returns undefined in certain situations. I thought at first that it could be related to https://bugs.chromium.org/p/chromium/issues/detail?id=1487920 but it actually happens with different OS and Chrome versions. I added `UTC` as fallback so that the page doesn't crash in those situations.
=> ui: Fix TypeError on author pages

record-editor/src/app/shared/config/hep/core.config.ts
arXiv recently started redirecting URLs of the form `https://arxiv.org/pdf/yymm.nnnnn.pdf` to
`http://arxiv.org/pdf/yymm.nnnnn`, which breaks the PDF preview in the editor due to security restrictions on mixed active content. This commit fixes the issue by loading the final URL directly with the proper scheme.
=> record-editor: workaround faulty arXiv redirect

backend/poetry.lock, backend/pyproject.toml
we should not just use the branch name of a repo for setting the package version. This sets the he-crawl version to a specific commit of the repo
=> hepcrawl: set package version to celery5 branch sha

.github/workflows/e2e-tests.yml
Remove unnecessary environment variables from e2e tests, as the default setting is `localhost` anyways
=> actions: remove some e2e env vars

docker-compose.services.yml
* Replace rabbitmq docker image tag with one that offers arm as well as linux as a plattform
=> compose: correct mq img tag

backend/inspirehep/editor/views.py, backend/inspirehep/records/api/literature.py, backend/poetry.lock, backend/pyproject.toml
* ref: https://github.com/cern-sis/issues-inspire/issues/546
Also bumps `inspire-schemas` and `inspire-utils`.
=> global: import parsers from inspire-schemas

ui/public/config.js, ui/src/holdingpen-new/containers/DetailPageContainer/AuthorDetailPageContainer.tsx
* ref: cern-sis/issues-inspire#520
=> ui: display error link in new holdingpen

README.md, docker-compose.yml
removes disk mount, which broke the record-editor using the docker setup (by overwriting the copied dist from the dockerfile)
=> editor: remove disk mount

backend/inspirehep/records/marshmallow/authors/ui.py, ui/src/backoffice/components/Links.tsx, ui/src/backoffice/components/__tests__/Links.test.tsx
* related: https://github.com/inspirehep/inspirehep/pull/3324
Bluesky and Mastodon fields were missing from the authors/ui serializer so they weren't being taken from `ids` out into the appropriate metadata field.
Also added both to backoffice.
=> ui: fix bluesky and mastodon not showing up in author profile

ui/src/backoffice/authors/components/AuthorMainInfo.tsx, ui/src/backoffice/authors/containers/AuthorDetailPageContainer.tsx, ui/src/backoffice/authors/containers/__tests__/AuthorDetailPageContainer.test.tsx, ui/src/backoffice/authors/containers/__tests__/__snapshots__/AuthorDetailPageContainer.test.tsx.snap, ui/src/backoffice/utils/__tests__/utils.test.tsx, ui/src/backoffice/utils/utils.tsx
ref: https://github.com/cern-sis/issues-inspire/issues/678
=> fix[ui][backoffice]: remove ORCID from the author links box

ui/src/actions/search.ts, ui/src/common/containers/SearchBoxContainer.tsx, ui/src/common/http.ts
ref: https://github.com/cern-sis/issues-inspire/issues/718
* Queries the AI endpoint on search, just to collect data on the model's performance. 
* The request runs in parallel and doesn't block the search. 
* The implementation is very simple as it's a temporary feature that will be reworked later on.
=> ui: query ai endpoint on search

ui/src/App.less
The position was off in dev, probably due to some kind of race condition, although locally it worked correctly. I changed `position: absolute` to `position: fixed` which makes sure the element is position relative to the viewport and not to the body or nearest positioned ancestor. This should work in all cases.
=> ui: make ant-message position fixed

ui/src/common/components/SearchFeedback/SearchFeedback.tsx
The events when opening the search feedback modal where not being sent correctly to matomo.
The `EventTracker` component by default intercepts the children's `onClick`. However, since the event we want to intercept is the `Card`'s `onClick` and that one is inside of `SearchFeedback`, we need to explicitly pass down this `onClick` to the card and call it.
=> ui: fix matomo events for search feedback modal opening

backend/inspirehep/orcid/tasks.py, backend/tests/integration/orcid/test_orcid_tasks_orcid_push.py
* ref: cern-sis/issues-inspire/issues/881
=> exception: robust to None request

renderer/server.js
hopefully fixes the `Render error: ProtocolError: Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.` error on the renderer pods
=> renderer: add disable-gpu arg

.github/workflows/backend-tests.yml
Hopefully, this will resolve the issue in https://github.com/cern-sis/issues-inspire/issues/915
=> Fix caching of test durations in github CI

renderer/package.json, renderer/server.js
* Add p-limit to limit concurrency
* Add some additional timeouts
* Add more failsafes for page closing
* Add browser instance refresh
* Remove `/healthz` endpoint as we can just use the render endpoint for health checks
=> renderer: add p-limit and other fixes

.github/workflows/test-workflows.yml
`airflow db init`  has been removed on airflow 3
use `airflow db migrate` instead
=> gh wf: update workflow-tests
